### ISSUE TITLE
Increase size limit for tensorflow related packages

### ISSUE THREAD

**Issue by av8ramit** [pypa/packaging-problems#101]
Hi @dstufft, I'm an engineer on TensorFlow. I was wondering if it would be possible to get a size increase for the following packages on upload.pypi.org/legacy/ and test.pypi.org/legacy/?

tf-nightly 100MB
tf-nightly-gpu 200MB
tensorflow 100MB
tensorflow-gpu 200MB

I believe this was mentioned in https://github.com/pypa/packaging-problems/issues/86, I still get the error when I upload tensorflow_gpu, but it seems to accept the file. For tf_nightly* these are new nightly versions of tensorflow.

Thanks!

**Comment by av8ramit** [comment]
@dstufft any chance we can get this bump soon?

**Comment by yifeif** [comment]
@dstufft could you help us increase the sizes for TensorFlow nightly packages? Thank you in advance!

**Comment by gunan** [comment]
@dstufft TensorFlow is blocked on this issue for new releases, could you take a look please?

**Comment by av8ramit** [comment]
@ewdurbin any chance you could help as well? Thanks!

**Comment by dstufft** [comment]
These have been handled.
