### ISSUE TITLE
Require an increase in file-size for uploading Intel's runtimes

### ISSUE THREAD

**Issue by rohit-jamuar** [pypa/packaging-problems#103]
Hi,

I'm from Intel's Scripting, Analyzers and Tools team, and as a part of enabling developers for using Intel's high performance libraries - Intel MKL, IPP, Intel DAAL, Intel MPI, TBB, etc., it was decided that we host our runtimes (static and dynamic) and header files for all platforms on PyPi. I'm currently trying to upload wheels containing dynamic libraries for Intel MKL. The cumulative size of three wheels is 650MB. Could it be possible to extend the file-size upload limit from 60MB? I tried uploading the wheels through `twine` but I keep seeing `400 Client Error: File too large. for url: https://upload.pypi.org/legacy/`. I have been unable to upload these to the `TestPyPi` as well, I keep getting `Received "503: first byte timeout" Package upload appears to have failed`.

Thanks,
Rohit

**Comment by dstufft** [comment]
What's the size of the largest individual file?

**Comment by rohit-jamuar** [comment]
```
mkl_dynamic-2018.0.0-py2.py3-none-linux_x86_64.whl = 210MB 
mkl_dynamic-2018.0.0-py2.py3-none-macosx_x86_64.whl = 244MB 
mkl_dynamic-2018.0.0-py2.py3-none-win_amd64.whl = 173MB 
```

**Comment by dstufft** [comment]
Alright, so a limit of 275MB seems like it would work for you? The limit is per file.

**Comment by rohit-jamuar** [comment]
If it's per file, then yes, 275MB should suffice for uploading `mkl-dynamic`.

**Comment by dstufft** [comment]
Is ``mkl-dynamic`` the only project on PyPI that needs it's limit increased?

**Comment by rohit-jamuar** [comment]
I've only tried uploading dynamic libraries for Intel MKL. I'd eventually try to upload the static libs, header files, and move on to other performance libraries. Would there be a way to request an increase besides this Github Issue?

**Comment by dstufft** [comment]
This is the best way. If you can figure out what file size you'd need for each project, and make sure you have the projects all registered on PyPI, I can increase the limit for them all at the same time if you list the PyPI names for each.

**Comment by rohit-jamuar** [comment]
Alright. Then lets keep this `Issue` open, would get back to you with details once all the wheels and corresponding PyPi projects have have been created.

**Comment by rohit-jamuar** [comment]
Also, I've been having issues with trying to register a project, whenever I invoke `python setup.py register -r pypi `, I keep getting `Server response (410): Project pre-registration is no longer required or supported, so continue directly to uploading files`. I've tried to register with `twine` as well, get the same error message. Is there another way of doing this?

**Comment by rohit-jamuar** [comment]
@dstufft 
These are the PyPI projects that would require you to increase the upload-size for:
```
pypi project-name  | maximum file-size / project
mkl-static         |      300 MB
mkl                |      260 MB 
ipp-static         |      160 MB
ipp                |      150 MB (doesn't exist currently)
daal-static        |      320 MB
daal               |      110 MB 
```
I  wanted to create a project called "ipp" that would host the runtimes for Intel(R) IPP, it already exists but seems to be abandoned (https://pypi.python.org/pypi/ipp). Would it be possible to have this project removed, if unused?

**Comment by rohit-jamuar** [comment]
Bump!

**Comment by dstufft** [comment]
These have all been set to the respective requested sizes.
