### ISSUE TITLE
Installing large wheels to PyPI

### ISSUE THREAD

**Issue by philthompson10** [pypa/packaging-problems#109]
I have a large wheel (approx 100M) that seems to be too large to be accepted by PyPI. This has happened in the past with earlier versions of this wheel and the (per-project?) limit has been increased when I have requested it. How should I now go about requesting a change in the limit?

**Comment by di** [comment]
Hi @philthompson10, an issue here is fine. Can let us know the name of the package in question?

**Comment by philthompson10** [comment]
On 14 Nov 2017, at 1:46 pm, Dustin Ingram <notifications@github.com> wrote:
> 
> Hi @philthompson10, an issue here is fine. Can let us know the name of the package in question?

https://pypi.python.org/pypi/PyQt5

Regards,
Phil

**Comment by di** [comment]
@philthompson10 I've increased the limit for `PyQt5` to 120MB.
