### ISSUE TITLE
Documentation is spread out all over the place

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#11]
The documentation for all the various pieces a user is expected to know is spread out all over the place. There should be one central location where users can go to learn about _everything_.

This is probably solved by the packaging guide.

**Comment by brainwane** [comment]
Now that https://packaging.python.org/ exists and is generally understood to be the home for Python packaging documentation, can we close this issue?

**Comment by ncoghlan** [comment]
Aye, we've resolved this now. There are still a lot of gaps to fill in, but we at least know where the content is *expected* to live :)
