### ISSUE TITLE
PyPI package size limit for deepspeech-gpu

### ISSUE THREAD

**Issue by reuben** [pypa/packaging-problems#110]
We're trying to publish project deepspeech-gpu and are running into the same problem as tensorflow-gpu, as we also include a bunch of compiled libraries for CUDA support. Could you bump our limit to 200MB on upload.pypi.org and test.pypi.org?

Thanks!

**Comment by di** [comment]
Hi @reuben, I'm not seeing a project called `deepspeech-gpu` (https://pypi.org/project/deepspeech-gpu/ is 404).

If you haven't uploaded a version of the project yet, you'll need to upload something before I can increase the limit.

**Comment by reuben** [comment]
Hi @di, sorry about that. I uploaded a package minus the large shared library to both test.pypi.org and pypi.org. Let me know if that's enough for you to bump the limit! Thanks :)

**Comment by reuben** [comment]
Ping? Sorry about the noise, but we're trying to do a release and are blocked by the packages being available.

**Comment by di** [comment]
@reuben I've increased the limits for `deepspeech-gpu` to 200MB.
