### ISSUE TITLE
Package size request for offline learning app Kolibri

### ISSUE THREAD

**Issue by benjaoming** [pypa/packaging-problems#116]
Hi PyPi friends!

We're building an application that is distributed in unconventional ways - offline. It's had a couple of releases at 87 MB. We bundle in dependencies for portability, such that people deploying at remote schools, refugee camps, etc won't be facing an unexpected necessity of dynamic online dependencies.

Just recently, we did some updates to decrease the file size significantly. But I'm not sure if in the future, we might end up making the same choices again.

Am trying to fill in our release history on PyPi, and we did 2 releases at 87 MB, so I was wondering if our repository can be bumped to 100 MB max pkg size?

https://pypi.python.org/pypi/kolibri/

**Comment by di** [comment]
@benjaoming I've increased the limit for `kolibri` to 100MB.

**Comment by benjaoming** [comment]
Thanks so much @di - really appreciate it!!

**Comment by benjaoming** [comment]
@di 

I wanted to note that there seems to be some potential problems with larger files, failing with a 503 without any further error msg:

```
$ twine upload -s dist/kolibri-0.6.1-py2.py3-none-any.whl                          
Uploading distributions to https://upload.pypi.org/legacy/
Signing kolibri-0.6.1-py2.py3-none-any.whl

Uploading kolibri-0.6.1-py2.py3-none-any.whl
Received "503: Service Unavailable" Package upload appears to have failed.  Retry 1 of 5                                                               
```

Upon second attempt, it worked, however the previous command I issued, had failures on all 5 retries.

**Comment by ewdurbin** [comment]
@benjaoming how's you're internet connection relative to AWS us-east-1?

for the time being the upload backend is hosted there and may be getting caught up in the mire of the tubes, particularly for larger uploads.

we'll be on new hosting soon for upload.pypi.org, but until then there isn't much we can do :(

**Comment by benjaoming** [comment]
I was doing this on a 200 mbit upload.. the errors occured at 100% uploaded, would suspect that something went wrong when processing the file at the endpoint?

**Comment by benjaoming** [comment]
> we'll be on new hosting soon for upload.pypi.org, but until then there isn't much we can do :(

That sounds cool, thanks for the response @ewdurbin - I will mention this again if I experience it after the migration.
