### ISSUE TITLE
Legacy PyPI Destroy Documentation button fails

### ISSUE THREAD

**Issue by RobinD42** [pypa/packaging-problems#117]
I experimented with uploading the wxPython docs to the PythonHosted site a while back but wasn't satisfied with it's speed. I've moved the docs to another site and am now trying to removed it from PythonHosted, but when I try the Destroy Documentation button on the wxPython PyPI package page but it just sits there spinning the throbber for a very long while and then fails. I'm guessing it's just too large and is timing out somewhere. Could somebody just manually blow it away for me?

Thanks.

**Comment by brainwane** [comment]
@RobinD42 just to be certain, you're talking about https://pypi.python.org/pypi/wxPython ?

I'm wondering whether this is the same issue as pypa/pypi-legacy#700 . @ewdurbin could I ask you to confirm?

**Comment by RobinD42** [comment]
> @RobinD42 just to be certain, you're talking about https://pypi.python.org/pypi/wxPython ?

Yes. Specifically, I would like the documentation at http://pythonhosted.org/wxPython/ to be removed and the automatic link to it on the wxPython pypi page to be hidden.

> I'm wondering whether this is the same issue as pypa/pypi-legacy#700 . @ewdurbin could I ask you to confirm?

Yes, it sounds like it is likely the same. Comments there are also reporting that using the destroy documentation button fails.

**Comment by brainwane** [comment]
@RobinD42 does the new PyPI documentation deletion functionality work for you? See https://github.com/pypa/warehouse/pull/3413 .

**Comment by RobinD42** [comment]
Yes, it appears that it does.

**Comment by brainwane** [comment]
Thank you!
