### ISSUE TITLE
Requested package size increase for "tagnews"

### ISSUE THREAD

**Issue by kbrose** [pypa/packaging-problems#119]
Hello,

I publish a package that contains several built-in machine learning models. The size of the current tarball is about 85 MB. Would it be possible to increase the allowed publication size to 100 MB? The package is called "tagnews": https://pypi.python.org/pypi/tagnews/

Thanks!

**Comment by di** [comment]
Hi @kbrose, I've set the upload limit for `tagnews` to 100MB.
