### ISSUE TITLE
Service Unavailable when uploading packages

### ISSUE THREAD

**Issue by soumith** [pypa/packaging-problems#120]
I am trying to `twine upload` packages for PyTorch, i.e. the PyPI `torch` package. They are ~500MB (490ish). I got an exception for large package sizes in https://github.com/pypa/packaging-problems/issues/96#issuecomment-334893976

However, when actually trying to upload the packages with:

```
twine upload torch-0.3.1-cp35-cp35m-linux_x86_64.whl
```

The upload progress bar reaches 100%, and then I get the error message:

```
Received "503: Service Unavailable" Package upload appears to have failed.
```

I have a high speed connection to the upload server, and upload happens at 30MBytes/sec and in less than 20 seconds for the entire upload.

Is there any chance someone can help me investigate this further / help upload the packages?

p.s.: on the note of package size, I've found a way to shave off ~150MB (possibly more) off it, so it should start shrinking from next release.

**Comment by ewdurbin** [comment]
This is a known limitation of the current hosting for the uploads endpoint. The upload process requires processing of the uploaded file and even if an upload occurs quickly enough to avoid timeout, the processing of a large file may eat up the remainder of the time.

Our current timeout is 60s, but we plan to raise that when we move to next gen infrastructure for Warehouse in the coming weeks.

**Comment by AlJohri** [comment]
@soumith @ewdurbin does this mean it's ready to go? 😀 https://twitter.com/EWDurbin/status/974424840429080578

**Comment by ewdurbin** [comment]
:-p @AlJohri indeed, we now have a more gracious timeout of 240s.

Been monitoring and tuning so it's not "ready" necessarily but it should be marginally better. continue to report issues here as they come up.

**Comment by sknop** [comment]
If I do not specify the url explicitly, it defaults to https://upload.pypi.io:

HTTPError: 503 Server Error: Service Unavailable for url: https://upload.pypi.io/legacy/

The correct URL is https://upload.pypi.org/legacy. With that URL set in my .pypirc file, I can successfully upload my wheels.

**Comment by ewdurbin** [comment]
@sknop based on the timing of this report I think you may have hit our maintenance window this morning: https://status.python.org/incidents/53f806wts00d

**Comment by soumith** [comment]
@brainwane I am hitting file size limits, but I am no longer hitting timeouts. I've posted a comment at https://github.com/pypa/packaging-problems/issues/96

Since I'm not hitting timeouts anymore, closing this issue.

**Comment by brainwane** [comment]
Thank you @soumith! And please check out [the Warehouse beta announcement](https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html) and consider joining us at a livechat.
