### ISSUE TITLE
Request for size limit increase for CuPy

### ISSUE THREAD

**Issue by kmaehashi** [pypa/packaging-problems#121]
Hello,

We [CuPy](http://github.com/cupy/cupy) dev team would like to start distributing wheels on PyPI.
I would like to request a size limit increase for the following packages, as these packages need to contain dependency libraries (CUDA etc.) and the size of each package become larger than 60 MB.

* cupy-cuda75: 100 MB
* cupy-cuda80: 240 MB
* cupy-cuda90: 290 MB

Thanks in advance!

**Comment by di** [comment]
@kmaehashi I've set the upload limit for `cupy-cuda75`, `cupy-cuda80`, and `cupy-cuda90` to 300MB.

**Comment by kmaehashi** [comment]
Thank you!
