### ISSUE TITLE
Increase maximum size limit for turicreate

### ISSUE THREAD

**Issue by znation** [pypa/packaging-problems#123]
As in #86 and #103, we need a larger size limit for the [turicreate](https://pypi.python.org/pypi/turicreate/) package. In the 4.2 release, we are adding native Linux visualization based on CEF (Chromium Embedded Framework), which brings our package size above the current 60 MB limit on Linux. The largest .so in our Linux packages is now `libcef.so`, at 120MB by itself. Could we please have an increased limit for this package?

**Comment by di** [comment]
@znation What would you like the limit to be?

**Comment by znation** [comment]
@di How about 150 MB? The zipped wheels are currently under 100 MB, but 150 would give us some breathing room.

**Comment by di** [comment]
@znation I've set the limit for `turicreate` to 150MB for both pypi and test-pypi.

**Comment by znation** [comment]
Thanks @di!
