### ISSUE TITLE
PyPI size limit increase for CNTK GPU

### ISSUE THREAD

**Issue by mx-iao** [pypa/packaging-problems#125]
Hi @di @dstufft ,

We are working to get CNTK on PyPI and would like to request a size increase to `200MB` for the `cntk-gpu` package for pypi.org and test.pypi.org. [CNTK](https://github.com/Microsoft/CNTK) (Cognitive Toolkit) is Microsoft's open-source deep learning framework, and similar to the requests coming from PyTorch (#96 ) and TensorFlow (#92), we currently exceed the PyPI package limit due to the compiled libraries for CUDA support that our binaries include. 

We have our 2.5 release slated for mid next week, so it'd be great if we could get a size increase before then. Thanks so much!

**Comment by di** [comment]
@mx-iao I've set the limit for `cntk-gpu` on pypi.org to 200MB, but I'm not seeing a project named `cntk-gpu` on TestPyPI.

**Comment by mx-iao** [comment]
It looks like we're having some issues uploading onto TestPyPI. I can let you know once we get that resolved. For now pypi.org is good. Thanks for your help!

**Comment by di** [comment]
OK, I'll leave this issue open until that's resolved then. Let me know if we can help.

**Comment by mx-iao** [comment]
Sounds good. Thanks so much for the super quick response!

**Comment by mx-iao** [comment]
Hi @di, we now have `cntk-gpu` up on test.pypi.org. Can you increase the size limit to 200mb for that?
We have another issue where there is an existing cntk project on test.pypi.org with the name `cntk` that was created without the knowledge of the CNTK team (https://test.pypi.org/project/cntk/#description). This isn't an official project and we need the `cntk` name to distribute our cpu package. Let me know the best way to proceed with this.

**Comment by di** [comment]
@mx-iao I've increased the limit for `cntk-gpu` on TestPyPI to 200MB. I've also removed the existing `cntk` package, so you should be able to register it now.

Let me know if you need anything else! Good luck with your release.

**Comment by mx-iao** [comment]
Thanks @di! Can you also remove the account that created that project? The email that appears to be associated with that account is actually for an internal company CNTK discussion mailing list & shouldn't be used on PyPI.

**Comment by di** [comment]
@mx-iao I think you're referring to the `Author-Email` metadata, which is set per-release and was removed along with the project. The email address for the user who had uploaded it originally seems to be a private address to me.

**Comment by mx-iao** [comment]
Got it. Thanks again for all your help

**Comment by mx-iao** [comment]
Hi @di,
Can we get a size increase to 500mb for `cntk-gpu` on pypi.org and test.pypi.org similar to what PyTorch has (#96)? We are hitting the current size limit when including the CUDA/CuDNN/MKL dependencies we need. Thanks so much!

**Comment by di** [comment]
@mx-iao I've set the limit to 500MB, but please be aware that this is about the maximum that we're currently willing to set for a given package. Please also be considerate about how often you make a release this large to PyPI.

**Comment by mx-iao** [comment]
Thanks @di! Duly noted.
One last issue - we are hitting a 60mb limit for our CNTK CPU package `cntk`. Could we get a size increase for that package to 100mb? Thanks again for all your help.

**Comment by di** [comment]
@mx-iao Done.

**Comment by thiagocrepaldi** [comment]
@di We are facing this issue with cntk-gpu again. Was our limit downgraded again?

**Comment by di** [comment]
@thiagocrepaldi No, the limit for `cntk-gpu` is still 500MB for uploads and 20GB for the total project. To my knowledge the only changes are what's documented in this issue, when was it downgraded before?

**Comment by thiagocrepaldi** [comment]
I am trying to push artifacts into test.pypi.org today and it is failing with 
Received "503: first byte timeout" Package upload appears to have failed.  Retry 2 of 5

**Comment by thiagocrepaldi** [comment]
@di I think we have limit > 300MB for pypi.org, but not for test.pypi.or
I've managed to upload it to pypi.org, but it keeps failing on test.pypi.org

**Comment by di** [comment]
@thiagocrepaldi No, the limit is 500MB for TestPyPI as well per my comment above. That error looks like our backend is timing out. TestPyPI is far more resource constrained than PyPI... I'd recommend trying again (looks like issues might have been transient) and if it's still a problem we can look into it more.
