### ISSUE TITLE
TLSv1.0/TLSv1.1 rolling brownouts lasting beyond scheduled window

### ISSUE THREAD

**Issue by currankaushik** [pypa/packaging-problems#132]
Hi,

On the status website, it says that the brownouts should be effective "for the first ten (10) minutes of each hour." However, I've been trying intermittently over the past hour and have consistently seen the 403 error message that seems to be stemming from the brownout. I've included some sample output below. Am I misunderstanding the status page message?

Thanks

```
$ pip install -vvv -U pip
1 location(s) to search for versions of pip:
* https://pypi.python.org/simple/pip/
Getting page https://pypi.python.org/simple/pip/
Looking up "https://pypi.python.org/simple/pip/" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /simple/pip/ HTTP/1.1" 302 98
Status code 302 not in [200, 203, 300, 301]
Looking up "https://pypi.org/simple/pip/" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.org
"GET /simple/pip/ HTTP/1.1" 403 161
Status code 403 not in [200, 203, 300, 301]
Could not fetch URL https://pypi.python.org/simple/pip/: 403 Client Error: TLSv1.2+ is required for url: https://pypi.org/simple/pip/ - skipping
Installed version (9.0.1) is most up-to-date (past versions: none)
Requirement already up-to-date: pip in ./.virtualenvs/scratch2/lib/python2.7/site-packages
Cleaning up...
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by dstufft** [comment]
You're actually being affected by https://status.python.org/incidents/tx01j0cl7gv6 which is doing a load test by redirecting traffic to the new PyPI. The new PyPI is already mandating TLSv1.2.

**Comment by ewdurbin** [comment]
Ah yes, we've updated the current status page to note this.

@currankaushik may I ask what host operating system you're using pip 9.0.1 from?

**Comment by currankaushik** [comment]
Ah I see - I'm on a Mac (OSX). Is the recommended solution here to just upgrade OpenSSL?

**Comment by ewdurbin** [comment]
@currankaushik you can upgrade via bootstrap.pypa.io

```
curl https://bootstrap.pypa.io/get-pip.py | python
```

**Comment by dstufft** [comment]
On macOS you can just use pip 9.0.3 to fix it (and you can use ``get-pip.py`` to get that pip).

**Comment by ewdurbin** [comment]
Explicitly, pip 9.0.2+ has a built in transport that supports TLSv1.2 on MacOS/OSX < 10.13

**Comment by currankaushik** [comment]
That worked, thanks!
