### ISSUE TITLE
OSX 10.9 + Py3.4 + pip9.0.3 - error fetching source packages

### ISSUE THREAD

**Issue by jnews0n** [pypa/packaging-problems#135]
pip list:
Package      Version
------------ -------
asn1crypto   0.24.0
cffi         1.11.5
coverage     4.5.1
cryptography 2.2.2
idna         2.6
pip          9.0.3
pycparser    2.18
pyOpenSSL    17.5.0
setuptools   39.0.1
six          1.11.0
urllib3      1.22

pip install fs==0.5.4
 pip install fs==0.5.4 -v
Collecting fs==0.5.4
  1 location(s) to search for versions of fs:
  * https://pypi.python.org/pypi/fs/
  Getting page https://pypi.python.org/pypi/fs/
  Looking up "https://pypi.python.org/pypi/fs/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  https://pypi.python.org:443 "GET /pypi/fs/ HTTP/1.1" 200 18896
  Updating cache with response from "https://pypi.python.org/pypi/fs/"
  Analyzing links from page https://pypi.python.org/pypi/fs/
    Skipping link http://www.python.org (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.org (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html (from https://pypi.python.org/pypi/fs/); unsupported archive format: .html
    Skipping link https://pypi.python.org/pypi/fs/#left-hand-navigation (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi/fs/#content-body (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=browse (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=list_classifiers (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=rss (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=packages_rss (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/tos (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://wiki.python.org/moin/CheeseShopTutorial (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/security (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://sourceforge.net/tracker/?group_id=66150&atid=513504 (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://github.com/pypa/pypi-legacy/issues (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.python.org/sigs/distutils-sig/ (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://wiki.python.org/moin/CheeseShopDev (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.python.org/about (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.python.org/news (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.python.org/doc (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.python.org/download (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.python.org/community (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.python.org/psf (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.python.org/dev (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi/fs (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=login_form (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=register_form (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi?%3Aaction=forgotten_password_form (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/openid_login (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/openid_login?provider=Launchpad (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/google_login (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.python.org/pypi/fs/2.0.20 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .20
    Skipping link https://pypi.python.org/pypi/fs/2.0.19 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .19
    Skipping link https://pypi.python.org/pypi/fs/2.0.18 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .18
    Skipping link https://pypi.python.org/pypi/fs/2.0.17 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .17
    Skipping link https://pypi.python.org/pypi/fs/2.0.16 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .16
    Skipping link https://pypi.python.org/pypi/fs/2.0.15 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .15
    Skipping link https://pypi.python.org/pypi/fs/2.0.14 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .14
    Skipping link https://pypi.python.org/pypi/fs/2.0.12 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .12
    Skipping link https://pypi.python.org/pypi/fs/2.0.12a1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .12a1
    Skipping link https://pypi.python.org/pypi/fs/2.0.12a0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .12a0
    Skipping link https://pypi.python.org/pypi/fs/2.0.11 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .11
    Skipping link https://pypi.python.org/pypi/fs/2.0.11a0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .11a0
    Skipping link https://pypi.python.org/pypi/fs/2.0.10 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .10
    Skipping link https://pypi.python.org/pypi/fs/2.0.10a2 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .10a2
    Skipping link https://pypi.python.org/pypi/fs/2.0.10a1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .10a1
    Skipping link https://pypi.python.org/pypi/fs/2.0.10a0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .10a0
    Skipping link https://pypi.python.org/pypi/fs/2.0.9 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .9
    Skipping link https://pypi.python.org/pypi/fs/2.0.8 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .8
    Skipping link https://pypi.python.org/pypi/fs/2.0.8a1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .8a1
    Skipping link https://pypi.python.org/pypi/fs/2.0.7 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .7
    Skipping link https://pypi.python.org/pypi/fs/2.0.6 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .6
    Skipping link https://pypi.python.org/pypi/fs/2.0.6a2 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .6a2
    Skipping link https://pypi.python.org/pypi/fs/2.0.6a1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .6a1
    Skipping link https://pypi.python.org/pypi/fs/2.0.6a0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .6a0
    Skipping link https://pypi.python.org/pypi/fs/2.0.5 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .5
    Skipping link https://pypi.python.org/pypi/fs/2.0.5a0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .5a0
    Skipping link https://pypi.python.org/pypi/fs/2.0.4 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .4
    Skipping link https://pypi.python.org/pypi/fs/2.0.4a3 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .4a3
    Skipping link https://pypi.python.org/pypi/fs/2.0.4a1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .4a1
    Skipping link https://pypi.python.org/pypi/fs/2.0.4a0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .4a0
    Skipping link https://pypi.python.org/pypi/fs/2.0.3 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .3
    Skipping link https://pypi.python.org/pypi/fs/2.0.2 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .2
    Skipping link https://pypi.python.org/pypi/fs/2.0.1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .1
    Skipping link https://pypi.python.org/pypi/fs/2.0.1a0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .1a0
    Skipping link https://pypi.python.org/pypi/fs/2.0.0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0
    Skipping link https://pypi.python.org/pypi/fs/2.0.0a6 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0a6
    Skipping link https://pypi.python.org/pypi/fs/2.0.0a5 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0a5
    Skipping link https://pypi.python.org/pypi/fs/2.0.0a4 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0a4
    Skipping link https://pypi.python.org/pypi/fs/2.0.0a3 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0a3
    Skipping link https://pypi.python.org/pypi/fs/2.0.0a2 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0a2
    Skipping link https://pypi.python.org/pypi/fs/2.0.0a1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0a1
    Skipping link https://pypi.python.org/pypi/fs/2.0.0a0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0a0
    Skipping link https://pypi.python.org/pypi/fs/0.5.5a1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .5a1
    Skipping link https://pypi.python.org/pypi/fs/0.5.4 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .4
    Skipping link https://pypi.python.org/pypi/fs/0.5.3 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .3
    Skipping link https://pypi.python.org/pypi/fs/0.5.2 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .2
    Skipping link https://pypi.python.org/pypi/fs/0.5.1 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .1
    Skipping link https://pypi.python.org/pypi/fs/0.5.0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0
    Skipping link https://pypi.python.org/pypi/fs/0.4.0 (from https://pypi.python.org/pypi/fs/); unsupported archive format: .0
    Skipping link http://www.python.org/about/website (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://www.fastly.com/ (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://developer.rackspace.com/ (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://aws.amazon.com/s3/ (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link http://www.timparkin.co.uk/ (from https://pypi.python.org/pypi/fs/); not a file
    Skipping link https://pypi.org/policy/terms-of-use/ (from https://pypi.python.org/pypi/fs/); not a file
  Could not find a version that satisfies the requirement fs==0.5.4 (from versions: )
Cleaning up...
No matching distribution found for fs==0.5.4
Exception information:
Traceback (most recent call last):
  File "/Users/user/scram/environment/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/user/scram/environment/lib/python3.4/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Users/user/scram/environment/lib/python3.4/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/user/scram/environment/lib/python3.4/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/Users/user/scram/environment/lib/python3.4/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/user/scram/environment/lib/python3.4/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for fs==0.5.4

**Comment by di** [comment]
What does your `~/.pypirc` look like? What's the result of running `echo $PIP_INDEX_URL`?

**Comment by jnews0n** [comment]
echo $PIP_INDEX_URL
yields no entry, and ~/.pypirc does not exist...but
there is .pip/pip.conf:
[global]
index-url=https://pypi.python.org/pypi/

I have removed the .pip directory.  That appears to have been the cause.

**Comment by brainwane** [comment]
@jnews0n Thanks for working this out with us. Do you think this should be added to https://packaging.python.org/guides/migrating-to-pypi-org/#downloading-packages ?

**Comment by jnews0n** [comment]
Perhaps.
