### ISSUE TITLE
Increase package size limit for mlpack3

### ISSUE THREAD

**Issue by rcurtin** [pypa/packaging-problems#136]
Hi there,

I'd like to request a package size limit increase for the 'mlpack3' package on both the test and regular PyPI site:  https://test.pypi.org/project/mlpack3/

The package is built on a C++ library so there are lots of .so's that must be distributed with it.  This causes the package to be quite large.

Right now the package is 65MB, but it would be nice to avoid any future problems if the library grows, so could I request a size limit increase to 100MB please?

Thank you!

**Comment by di** [comment]
I've set the limit for `mlpack3` to 100MB.

**Comment by rcurtin** [comment]
Hi @di, thanks so much for the quick response. :)
