### ISSUE TITLE
error: Upload failed (403): TLSv1.2+ is required

### ISSUE THREAD

**Issue by mouday** [pypa/packaging-problems#137]
i use this code
```
$ python setup.py sdist upload
```
log is :
```
running sdist
running egg_info
writing consolecolor.egg-info/PKG-INFO
writing top-level names to consolecolor.egg-info/top_level.txt
writing dependency_links to consolecolor.egg-info/dependency_links.txt
reading manifest file 'consolecolor.egg-info/SOURCES.txt'
writing manifest file 'consolecolor.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating consolecolor-0.0.1
creating consolecolor-0.0.1/consolecolor
creating consolecolor-0.0.1/consolecolor.egg-info
making hard links in consolecolor-0.0.1...
hard linking setup.py -> consolecolor-0.0.1
hard linking consolecolor/__init__.py -> consolecolor-0.0.1/consolecolor
hard linking consolecolor/consolecolor.py -> consolecolor-0.0.1/consolecolor
hard linking consolecolor.egg-info/PKG-INFO -> consolecolor-0.0.1/consolecolor.egg-info
hard linking consolecolor.egg-info/SOURCES.txt -> consolecolor-0.0.1/consolecolor.egg-info
hard linking consolecolor.egg-info/dependency_links.txt -> consolecolor-0.0.1/consolecolor.egg-info
hard linking consolecolor.egg-info/top_level.txt -> consolecolor-0.0.1/consolecolor.egg-info
Writing consolecolor-0.0.1/setup.cfg
Creating tar archive
removing 'consolecolor-0.0.1' (and everything under it)
running upload
Submitting dist/consolecolor-0.0.1.tar.gz to https://pypi.python.org/pypi
Upload failed (403): TLSv1.2+ is required
error: Upload failed (403): TLSv1.2+ is required
```

in the end ：

```
Upload failed (403): TLSv1.2+ is required
error: Upload failed (403): TLSv1.2+ is required

```
i don't know i need do some...

i use:
 Python 2.7.10 
 mac os

**Comment by ncoghlan** [comment]
The OpenSSL module in Python 2.7.10 is too old to support TLS v1.2, which is now required for package uploads. (See https://pyfound.blogspot.com.au/2017/01/time-to-upgrade-your-python-tls-v12.html for more details)

Your simplest option will likely be to use `twine` to handle the upload instead: https://github.com/pypa/twine#installation

A newer Python installation should also be able to handle the upload correctly.

**Comment by alex** [comment]
`pip install requests[security]` is probably the quickest way to resolving this.

**Comment by ncoghlan** [comment]
Based on https://github.com/pypa/warehouse/issues/3411#issuecomment-379711780 and https://github.com/pypa/warehouse/issues/3293#issuecomment-378468534, it sounds like simply switching to `twine` may not resolve this yet (and the Python 2.7.15 update to the python.org installers is also still several days away).

Given you're facing this issue on upload, you're also likely to face it on download as well, so if you get an error while trying @alex's suggestion, and don't already have `pip` 9.0.3, then you may need to upgrade that first as described in https://mail.python.org/pipermail/python-announce-list/2018-April/011885.html

**Comment by mouday** [comment]
ok ,thank you! I  goto 

https://pypi.org/  

verify my email ,it is work！！！

and I reference article: https://blog.csdn.net/mouday/article/details/79875119
