### ISSUE TITLE
Size limit increase for gym-retro

### ISSUE THREAD

**Issue by endrift** [pypa/packaging-problems#140]
I've uploaded an sdist for https://pypi.org/project/gym-retro/ that has to delete a good chunk of the data to fit in 60MB. It would be appreciated if I could get a 150MB limit so I can upload all of the data. Thanks.

**Comment by di** [comment]
@endrift Can you explain what this package is and why it needs to be so large?

**Comment by endrift** [comment]
Some details are here: https://blog.openai.com/retro-contest/

Each game has a series of initial states, which vary in size from a few kilobytes to a few hundred kilobytes, and there are simply too many of these to fit in 60MB.

**Comment by di** [comment]
Thanks! I've set the limit for `gym-retro` to 150MB on both `pypi.org` and `test.pypi.org`.

**Comment by endrift** [comment]
Thank you!
