### ISSUE TITLE
clarify and add redundancy to distutils-sig admin ownership

### ISSUE THREAD

**Issue by ncoghlan** [pypa/packaging-problems#141]
@brainwane Did you ever get a clear resolution as to who the current admins for distutils-sig actually are?

The list metadata just points to distutils-sig-owner@python.org, which doesn't provide any indication as to who might be in a position to handle requests like adding another admin, migrating the list to mailman 3, or requesting a name change (probably post MM3 migration).

**Comment by ncoghlan** [comment]
(The context here is that I'd like to finally get the ball rolling on an MM3 upgrade, but I'm not a list admin myself, and writing to distutils-sig-owner to request it seems weird without any idea as to who I'm actually sending the request to)

**Comment by brainwane** [comment]
@ncoghlan I did not. The only person I know to be (or to have recently been) one of its owners is @dstufft.

**Comment by tjguk** [comment]
I'm a moderator in the sense that amk mentioned. (And I definitely do moderate messages here and elsewhere). I do actually follow distutils-sig although I don't consider myself a core part of that community.

I'm happy for the list to be upgraded.

**Comment by dstufft** [comment]
Yea I haven’t figured out how to drop moderator privs yet, and I never interact with the moderated email because I forget how to do it. I get those emails though. I’m happy for it be moved to mm3 though.

**Comment by tjguk** [comment]
The distinction which @akuchling makes above between list ownership and connection to the relevant community is perhaps worth a wider consideration. I own or moderate several Python lists as a service to the community (including speed, win32, uk, list, announce, checkins, docs and core-mentorship) but I'm not necessarily engaged in all those communities, and I'm not even subscribed to some of the lists.

However, ISTM that trying to tie together those-who-represent-a-subcommunity and those-who-manage-mailing-lists is unnecessary unless there's any sort of question over, eg, the parameters of the list contents or -- as here -- the question of where it's hosted.

**Comment by ncoghlan** [comment]
OK, I've started the list migration process by posting to the list to say we're going to be migrating it: https://mail.python.org/pipermail/distutils-sig/2018-April/032215.html

While I wouldn't be active on the actual moderation side of things, it would probably make sense to add me as a list owner (post-migration) so I can handle tasks like updating the list description, etc.

**Comment by pradyunsg** [comment]
@ncoghlan It seems like this is resolved now. Can we close this?

**Comment by ncoghlan** [comment]
Aye, it's resolved, even if I don't necessarily love that the interim answer is "Me" :)

**Comment by brainwane** [comment]
@ncoghlan I think there's been a bit more spam recently. Would you like for me to become one of the list admins so I can do something about that?

**Comment by ncoghlan** [comment]
@brainwane Good idea, and thanks - I've added you with the same full level of access I have.
