### ISSUE TITLE
Unable to specify several author emails

### ISSUE THREAD

**Issue by Juanlu001** [pypa/packaging-problems#143]
When one searches how to include more than one author email in `setup.py`, the most promising result is this bug from 2009:

https://bugs.python.org/issue6992

Which was closed with a reference to [PEP 345 (Metadata 1.2)](https://www.python.org/dev/peps/pep-0345/). That one, however, specifies that:

> It can contain a name and e-mail address in the legal forms for a RFC-822 `From: ` header.

An email can come only from _one_ person, therefore I understand that several `author_emails` are not possible.

Also, none of this was modified in [PEP 566 (Metadata 2.1)](https://www.python.org/dev/peps/pep-0566/).

Is there any ongoing discussion on how to support this feature? In case there's a workaround, can it be documented more clearly?

**Comment by di** [comment]
Several email addresses in `author_emails` (and in a RFC-822 `From` header) are possible.

See https://packaging.python.org/specifications/core-metadata/#author-email for an example.

**Comment by Juanlu001** [comment]
That means I'm bad at reading RFCs I suppose :slightly_smiling_face: Thanks a lot for your lightning fast response! This is not a "problem" in any sense (perhaps the SEO could be improved) so I'm closing.
