### ISSUE TITLE
package redirect leads to 404 page

### ISSUE THREAD

**Issue by JeremyEnns** [pypa/packaging-problems#144]
The source url in the [Jpype1](https://pypi.org/project/JPype1/) package contains a link to the source file: https://pypi.org/packages/source/j/jpype1/jpype1-0.6.3.tar.gz 

This is a 301 redirection to:
https://files.pythonhosted.org/packages/source/j/jpype1/jpype1-0.6.3.tar.gz 

Which ends in a 404 error, I am not sure where to direct this to as its likely IT related rather than package related

**Comment by di** [comment]
Where is the URL `https://pypi.org/packages/source/j/jpype1/jpype1-0.6.3.tar.gz` listed? I'm not seeing it anywhere.

The correct URL would be `https://pypi.org/packages/source/j/jpype1/JPype1-0.6.3.tar.gz`, which redirects to `https://files.pythonhosted.org/packages/source/j/jpype1/JPype1-0.6.3.tar.gz`, which redirects to `https://files.pythonhosted.org/packages/c4/4b/60a3e63d51714d4d7ef1b1efdf84315d118a0a80a5b085bb52a7e2428cdc/JPype1-0.6.3.tar.gz`, which resolves.

**Comment by JeremyEnns** [comment]
Thanks that helps, I see that the link my user sent me is all lowercase and the redirects are working if the file has a capital JPype1-0.6.3.tar.gz vs jpype1-0.6.3.tar.gz

I will make sure they are not manually entering the value with all lowercase somewhere in their build process.
