### ISSUE TITLE
Need larger size for new project: tf-nightly-xla-gpu

### ISSUE THREAD

**Issue by annarev** [pypa/packaging-problems#145]
Hi,
I am trying to upload a package to new project tf-nightly-xla-gpu and hitting "File too large. Limit for project 'tf-nightly-xla-gpu' is 60MB."

Package size is 229MB. With added room just in case, can we get exception for 260MB for the project tf-nightly-xla-gpu?

Thank you,
Anna

**Comment by di** [comment]
@annarev You'll need to create the project by uploading an initial release that's smaller than 60MB before we can increase the limit for it.

**Comment by annarev** [comment]
Thank you for a quick reply!
I just uploaded a small version:
https://pypi.org/project/tf-nightly-xla-gpu/#history

**Comment by di** [comment]
I've increased the limit for the project `tf-nightly-xla-gpu` to 260MB.
