### ISSUE TITLE
Unable to manage pypa projects in Appveyor

### ISSUE THREAD

**Issue by jaraco** [pypa/packaging-problems#148]
Currently, setuptools is deployed to Appveyor under my personal account and not under the pypa umbrella. His means other maintainers can’t manage the project builds there. I believe the proper way for teams to collaboratively manage these builds is to authenticate as the org. I don’t have pypa listed as an org when I authenticate via GitHub.

Could someone grant the necessary access such that Setuptools Developers could add and manage he project there?

**Comment by pfmoore** [comment]
I've added you to the "Appveyor admins" team under the PyPA account. I think that should be enough to get you the ability to sign on as pypa. If not, I'm honestly not sure what is needed. But I'm happy to help if you can find out what *is* required...

**Comment by jaraco** [comment]
That did the trick. Thanks Paul!

**Comment by pganssle** [comment]
@jaraco I still don't seem to be able to restart Appveyor jobs in the Appveyor UI.

**Comment by jaraco** [comment]
Here's another friendly team trying to do the same thing and running into similar challenges: https://github.com/jazzband/roadies/issues/74

**Comment by jaraco** [comment]
@pradyunsg I've added `Pip committers` to the `Build Managers` role in the Appveyor pypa team. Let us know if that provides the access you need (or not) and confirm which sign-in technique you used/tried.

**Comment by pradyunsg** [comment]
Yep. That worked out! Thanks @jaraco. :)

**Comment by pganssle** [comment]
Works for me now with the `pypa` login. Closing this.
