### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Schmoobenstein** [pypa/packaging-problems#153]
Hi,

I tried following the tutorial here https://packaging.python.org/tutorials/packaging-projects/. 

I'm told to create a project containing, amongst other things, the file README.**md**. However, the template setup.py, references the file README.**rst**

    with open("README.rst", "r") as fh:...

This causes the command 

     python setup.py sdist bdist_wheel

to fail., Changing to 

    with open("README.md", "r") as fh:...

works. Perhaps the text in the tutorial should be changed? Or is  the setup.py template correct and I botched it some other place?

**Comment by pganssle** [comment]
Another thing to note here is that this will cause failures on Python 2.7 if README.* contains non-ASCII characters.

I'm not sure I love the idea of including polyglot-specific code in documentation, but considering it's for libraries and *most* libraries are 2/3 compatible, it might be worth a footnote.

To make it 2/3 compatible it needs to me `io.open(..., encoding='utf-8')`.

**Comment by theacodes** [comment]
Filename issue fixed here: https://github.com/pypa/python-packaging-user-guide/pull/507

The 2/3 split is a weird one. We also avoid Python 2 specific instructions in the other tutorials, but the guides offer advice on supporting multiple versions. Might be worthwhile to file a bug on the user guide so we can discuss it separately from this issue.
