### ISSUE TITLE
Can't pip install after uploading to pypi

### ISSUE THREAD

**Issue by hkvision** [pypa/packaging-problems#158]
* Pip version: 9.0.1
* Python version: 2.7
* Operating system: Ubuntu 16.04

I uploaded `analytics-zoo` dev version 0.1.0.dev1 to pypi using twine yesterday: https://pypi.org/project/analytics-zoo/
But if I use `pip install analytics-zoo`, it will say no distribution found:
```
Could not find any downloads that satisfy the requirement analytics-zoo
Cleaning up...
No distributions at all found for analytics-zoo
```
Can anyone help on this? Thanks so much in advance!

More information: Previously when I uploaded 0.1.0.dev0, it immediately took effect. Not knowing the fact that package name can't be reused, I deleted 0.1.0.dev0 and I now used 0.1.0.dev1.
The change maybe the package size from around 2MB to 54MB.

**Comment by pradyunsg** [comment]
Could you try running pip with --verbose and see what the output is?

It shows which candidates pip considered and decided to not use.

**Comment by theacodes** [comment]
Since `analytics-zoo` *only* has a manylinux wheel, you'll need to make sure whatever you're installing from also supports that platform tag. `pip install --verbose` will tell you if/why it's skipping the wheel.

I strongly recommend you always upload a source distribution as well.

**Comment by hkvision** [comment]
Thank you so much for your prompt reply! @pradyunsg @theacodes 
After using --verbose, I got the following:
```
Collecting analytics-zoo
  1 location(s) to search for versions of analytics-zoo:
  * https://pypi.tuna.tsinghua.edu.cn/simple/analytics-zoo/
  Getting page https://pypi.tuna.tsinghua.edu.cn/simple/analytics-zoo/
  Looking up "https://pypi.tuna.tsinghua.edu.cn/simple/analytics-zoo/" in the cache
  Current age based on date: 69459
  Freshness lifetime from request max-age: 600
  Starting new HTTPS connection (1): pypi.tuna.tsinghua.edu.cn
  "GET /simple/analytics-zoo/ HTTP/1.1" 404 169
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/analytics-zoo/: 404 Client Error: Not Found for url: https://pypi.tuna.tsinghua.edu.cn/simple/analytics-zoo/ - skipping
  Could not find a version that satisfies the requirement analytics-zoo (from versions: )
Cleaning up...
No matching distribution found for analytics-zoo
```
I am using the mirror image of tsinghua. After removing the image, it started downloading, but the speed is really slow lol.
But during my first release of 0.1.0.dev0, even I use this mirror, it can still find the distribution.
Any idea why this becomes a problem now?
I will try to upload a source distribution. Thanks for the suggestion.

**Comment by hkvision** [comment]
In another server machine, that I don't use any mirror image, the output of `--verbose` is the following:
```
Downloading/unpacking analytics-zoo
  Could not find any downloads that satisfy the requirement analytics-zoo
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for analytics-zoo
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for analytics-zoo

Storing debug log for failure in /root/.pip/pip.log
```
Any idea why this machine can't install?

**Comment by pradyunsg** [comment]
It seems that your package's `0.1.0.dev1` is not available on http://pypi.tuna.tsinghua.edu.cn/simple/analytics-zoo.

Further, you'd need to pass `--pre` to pip to be able to install development versions of packages (i.e. with the `.dev1` suffix).

> the output of --verbose is the following:

Is this `pip download`? Please provide the commands you're running as well. :)

**Comment by hkvision** [comment]
Yeah, the package is not on the mirror image.
The other problem is related to the wrong installation of pip.
Now the problem got resolved.
Thank you so much for the quick response and your time! @pradyunsg @theacodes
