### ISSUE TITLE
Question: When packaging, can I uninstall a certain package before installing my package?

### ISSUE THREAD

**Issue by hkvision** [pypa/packaging-problems#159]
This is not an issue but a question. I didn't find the solution from my searching...

Just opposite to `install_requires` in setup, is there any way to pip __ uninstall__ a package before installing my package?

Thanks so much in advance for the help!

**Comment by merwok** [comment]
There is now way at the moment.  What is needed is a metadata key to let your distribution declare a conflict with another one, and then a UI in installers like pip to ask the user what they want to do (remove the installed package and its dependent or uninstall them and install the other one).

**Comment by hkvision** [comment]
Thanks so much for your reply!
