### ISSUE TITLE
Package Cleanup?

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#16]
There are a lot of test packages, never used packages, etc that do nothing but take up names in the namespace. Is there any way we can periodically clean these out to free up names?

**Comment by pradyunsg** [comment]
What's the state of this now?

**Comment by ncoghlan** [comment]
https://www.python.org/dev/peps/pep-0541/ defines a process for PyPI admins to follow in response to requests to take over abandoned names, and is currently with the relevant PSF staff for review and approval to put it into effect.

So I think we can mark this issue resolved.

**Comment by pradyunsg** [comment]
Awesome! ^>^

**Comment by pradyunsg** [comment]
Do we have any idea as to how long it would take for PEP 541 to get reviewed and approved?

**Comment by ncoghlan** [comment]
Not too much longer - Mark Mangoba just got back from vacation recently, and has been working on a grant proposal since he got back, so we'll hopefully see it move forward within the next week or two.

**Comment by brainwane** [comment]
Per https://github.com/pypa/warehouse/issues/1506#issuecomment-375726502 , PEP 541 was approved, and now @di and others are working out the step-by-step process for dealing with abandoned projects.
