### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by lwanger** [pypa/packaging-problems#160]
I have a package on pypi called

 cooked-input (https://pypi.org/project/cooked-input/). I have been trying to get the README to render using restructuredtext and can't figure out why it won't work. I have stripped the README.rst program to the bare minimum (taken out images, links, etc.), run it through linters (e.g. rst-lint), checked and re-checked the setup.py file (long_description and long_description_content_type setting, etc.) and can't figure it out.

The git repository is: https://github.com/lwanger/cooked_input -- including the setup.py, README.rst files, etc.

Any help would be appreciated!

Len

**Comment by ncoghlan** [comment]
Hmm, `Description-Content-Type: text/x-rst` is showing up correctly on the PyPI page, so that doesn't seem to be the problem.

Does `readme_renderer` successfully render the page when running it locally? https://github.com/pypa/readme_renderer#check-description-locally

**Comment by lwanger** [comment]
Nick,

Thanks for looking at this. readme_remderer is happy. The output is:

$ python setup.py check -r -s
running check
The project's long description is valid RST.

Len

**Comment by di** [comment]
@lwanger What version of `wheel`/`setuptools` have you used to build the latest distribution on PyPI? It looks like the metadata for the wheel isn't being built correctly, it has additional fields after the message body:

```
Metadata-Version: 2.0
Name: cooked-input
Version: 0.3.4
Summary: Get, clean, convert and validate input.
Home-page: https://github.com/lwanger/cooked_input
Author: Len Wanger
Author-email: len_wanger@hotmail.com
License: MIT
Description: 
Requires-Dist: dateparser
Requires-Dist: future
Requires-Dist: setuptools-git
Requires-Dist: validus
Requires-Dist: veryprettytable

        Cooked Input Project

        ====================

        

        ``cooked_input`` is a Python package for getting, cleaning, converting, and validating input.

        If you think of input (raw_input in legacy Python) as raw input, then this is cooked input.

        

        ``cooked_input`` provides a simple and safe way to get validated command line input that ranges 

        from the simplest of Python programs to sophisticated database driven applications. Beginner's

        can use the provided convenience classes to get simple inputs from the user. Following the

        running in minutes.

        

        
Keywords: command line tool development input raw_input
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: MIT License
Classifier: Topic :: Database :: Front-Ends
Classifier: Topic :: Software Development
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Description-Content-Type: text/x-rst
```

When I build the wheel with the latest versions of `setuptools` and `wheel`, I get this:

```
Metadata-Version: 2.1
Name: cooked-input
Version: 0.3.3
Summary: Get, clean, convert and validate input.
Home-page: https://github.com/lwanger/cooked_input
Author: Len Wanger
Author-email: len_wanger@hotmail.com
License: MIT
Keywords: command line tool development input raw_input
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: MIT License
Classifier: Topic :: Database :: Front-Ends
Classifier: Topic :: Software Development
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Description-Content-Type: text/x-rst
Requires-Dist: setuptools-git
Requires-Dist: future
Requires-Dist: veryprettytable
Requires-Dist: dateparser
Requires-Dist: validus


.. image:: https://img.shields.io/pypi/v/cooked_input.svg
    :target: https://pypi.org/project/cooked-input/

.. image:: https://img.shields.io/pypi/dm/cooked_input.svg
    :target: https://pypi.org/project/cooked-input/

.. image:: https://img.shields.io/pypi/l/cooked_input.svg
    :target: https://pypi.org/project/cooked-input/

.. image:: https://readthedocs.org/projects/cooked_input/badge/?version=latest
    :target: https://pypi.org/project/cooked-input/

.. image:: https://img.shields.io/pypi/pyversions/cooked-input.svg
    :target: https://pypi.org/project/cooked-input/

Cooked Input Project
====================

``cooked_input`` is a Python package for getting, cleaning, converting, and validating input.
If you think of input (raw_input in legacy Python) as raw input, then this is cooked input.

``cooked_input`` provides a simple and safe way to get validated command line input that ranges from the simplest
of Python programs to sophisticated database driven applications. Beginner's can use the provided convenience classes
to get simple inputs from the user. Following the `tutorial <http://cooked-input.readthedocs.io/en/latest/tutorial.html>`_
you can be up and running in minutes.

More advanced users can easily create custom classes for sophisticated cleaning and validation. ``Cooked_input`` can
also be used to create menus and data tables. The latter tutorials and examples show several examples ranging from
simple to sophisticated calls.

``Cooked_input`` also provides a pathway to use the same cleaning and validation logic used in the command line
for validating web or GUI based inputs.

Documentation
-------------

The documentation is available at: http://cooked-input.readthedocs.io/en/latest/


Python 2/3 Support
------------------

cooked_input has been tested on Python: 2.7. 3.5, and 3.6


Installation
------------

  pip install cooked_input


Project Page
------------

Project information and source code is available at: https://github.com/lwanger/cooked_input


Tutorial
--------

The best way to get started is to read the quick start at: http://cooked-input.readthedocs.io/en/latest/quick_start.html

After that, more advanced usage can be learned from the tutorial at: http://cooked-input.readthedocs.io/en/latest/tutorial.html
```

which should correctly render on PyPI.

**Comment by lwanger** [comment]
setuptools: 39.2.0
wheel; 0.31.1

and calling setup.py from Python 3.6.2 with:

python setup.py bdist_wheel --universal

and

python setup.py build_sphinx


BTW: How do you get a dump of the metadata for a project?

Len

**Comment by di** [comment]
@lwanger `wheel==0.31.1` should be writing `Metadata-Version: 2.1` as in my example, rather than `Metadata-Version: 2.0` in the version you published to PyPI.

So perhaps you've either updated your version of `wheel` since that distribution was built, or you had an old distribution in the `./dist` directory that got mistakenly uploaded?

You can get the metadata for a wheel after building it like so:

```
$ unzip -c dist/cooked_input-0.3.3-py2.py3-none-any.whl cooked_input-0.3.3.dist-info/METADATA
```

**Comment by di** [comment]
Looking at [`cooked-input==0.3.4`](https://pypi.org/project/cooked-input/0.3.4/#files), it seems like you built this with `wheel==0.29.0`:

```
$ unzip -c cooked_input-0.3.4-py2.py3-none-any.whl cooked_input-0.3.4.dist-info/WHEEL
Archive:  cooked_input-0.3.4-py2.py3-none-any.whl
  inflating: cooked_input-0.3.4.dist-info/WHEEL
Wheel-Version: 1.0
Generator: bdist_wheel (0.29.0)
Root-Is-Purelib: true
Tag: py2-none-any
Tag: py3-none-any
```

I'd recommend trying to build the wheel again with the latest version of `wheel`, and see if the `METADATA` file looks like my example.

**Comment by lwanger** [comment]
This is frustrating!

I made sure wheel was upgraded. I rebuilt the distribution -- the metadata looks the same except for some ordering of the lines (metadata and wheel data
[metadata.txt](https://github.com/pypa/packaging-problems/files/2066471/metadata.txt)
[wheel.txt](https://github.com/pypa/packaging-problems/files/2066472/wheel.txt)

 attached). Uploaded again with twine... and still not getting rst formatting.

The README.rst does pass readme-renderer (output attached for "setup.py check
 -r -s" -- 
[check.txt](https://github.com/pypa/packaging-problems/files/2066480/check.txt)
)

Any more help?  

The only thing that I can think of to mention is twine uploads to: "https://upload.pypi.org/legacy"

Len

**Comment by di** [comment]
@lwanger It's still putting your long_description in the middle of the metadata, it should be at the end, after all the other fields.

I still can't reproduce it with the latest version of your repository, perhaps if you raise this issue over at https://github.com/pypa/wheel/issues the maintainers there can help.

**Comment by ncoghlan** [comment]
It may be worth trying removing the "description-file" entry from https://github.com/lwanger/cooked_input/blob/master/setup.cfg (I'm not actually sure what that will do - the `setuptools` docs only mention it in a side note)

**Comment by lwanger** [comment]
Found it!

The culprit was the line (which came from: https://github.com/pypa/sampleproject/blob/master/setup.py)::

    from codecs import open

For some reason that changed the ordering in the metadata.

Thanks to everyone for their help. I really appreciate it!

Len

**Comment by ncoghlan** [comment]
Ah, heck, looking at https://docs.python.org/3/library/codecs.html#codecs.open, I think that's an outright error in the sample project, as `codecs.open` doesn't default to universal newlines mode the way that `io.open` (and hence builtin `open()`) does.

Are you building the package on Windows, and does your `README.rst` use CRLF line breaks?

Given that Python 2.5 is now a dim and distant memory that essentially zero new projects are going to want to support, we should probably change the sample project to use this snippet instead of the current `codecs` module import:

    from io import open # Only needed for projects that want to support Python 2.7

**Comment by lwanger** [comment]
Yes I'm on Windows. I try to use Unix style line breaks, but in the Windows environment they get changed to CRLF from time to time as they did here.

The proposed change to the sample project makes sense to me.

Thanks again for the help!

**Comment by pradyunsg** [comment]
Is there anything else actionable here?

**Comment by lwanger** [comment]
Nothing else actionable as far as I'm concerned.

Thanks again for the help!

Len
