### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by onstash** [pypa/packaging-problems#161]
After installing `twine` via `pip`, I ran `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`. This is what I received - `zsh: command not found: twine`. My machine is a Macbook Pro. Please let me know how I can contribute to fix this.

**Comment by ncoghlan** [comment]
@onstash Could you let us know:

- which version of Mac OS X you're running
- the command line used to install `twine`
- the contents of `PATH`

(As https://github.com/pypa/python-packaging-user-guide/issues/396 discusses in more depth, there are a lot of different ways for environment set up to go awry based on exactly where folks started from in setting up their systems)

**Comment by onstash** [comment]
Thanks for the detailed comment, @ncoghlan. Much appreciated. :)

* macOS Sierra 10.12.6
* `python3 -m pip install --user --upgrade twine` (from the packaging tutorial)
* `echo $PATH` => `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by benoit-pierre** [comment]
Don't you get a warning about the path where twine was installed not being in your `PATH` (when installing twine with pip)?

**Comment by pradyunsg** [comment]
If you don't, what version of pip are you on?

**Comment by onstash** [comment]
I uninstalled and re-installed `twine` to see if I had missed the warning. It seems I did missing the warning the first time. 
```bash
Installing collected packages: twine
  The script twine is installed in '/Users/santoshvenkatraman/Library/Python/3.6/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

So sorry about the trouble @ncoghlan, @benoit-pierre, and @pradyunsg. Thanks for helping me out patiently. Will be closing the issue. 😄
