### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by eliasdabbas** [pypa/packaging-problems#163]
I'm getting the TypeError below in both cases, while trying to upload to test and by `twine upload dist/*`

>twine upload --repository-url https://test.pypi.org/legacy/ dist/*
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: eliasdabbas
Enter your password: 
TypeError: expected string or bytes-like object

> twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
TypeError: expected string or bytes-like object

> python --version
Python 3.6.5 :: Anaconda custom (64-bit)

Anything wrong I might be doing? 

Thanks a lot!

**Comment by ncoghlan** [comment]
@eliasdabbas That looks to me like it might be better filed directly as a twine issue, giving them your operating system information in addition to the Python interpreter version.

**Comment by eliasdabbas** [comment]
Thanks @ncoghlan I'll check with twine.
