### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by jimmyahalpara** [pypa/packaging-problems#164]
sir i did as you told but, is prepared the directory and also uploaded them on github then also they are telling that package directory not found.

**Comment by pradyunsg** [comment]
Hey @jimmyahalpara! Could you provide more details? Your current description does not provide enough information to help you here.

Which part of the tutorial are you facing issues with? Where have you uploaded your package on GitHub?

Who are "they" that are "telling that package directory not found"? Is it some output that was shown when you typed a command?

PS: Not everyone here is a "sir". :)
