### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by jimmyahalpara** [pypa/packaging-problems#165]
i did as you told and it got sucessfully uploaded on pypi.org but when i install on any other python it gives error like.
C:\Users\Jimmy>c:\Python27\Scripts\pip install Pytable-jim
Collecting Pytable-jim
  Using cached https://files.pythonhosted.org/packages/96/04/7410cf43447a2fb95a343f56d44412a5bb829b169fb27884278ae8f9dfcb/Pytable_jim-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: 'c:\\users\\jimmy\\appdata\\local\\temp\\pip-install-3ebmlf\\Pytable-jim\\setup.py'

**Comment by pradyunsg** [comment]
Hey @jimmyahalpara!

Did you figure this out? I seem to be able to install pytable-jim.

```sh-session
$ pip install Pytable-jim
Collecting Pytable-jim
  Downloading https://files.pythonhosted.org/packages/47/4e/ef4ffca3053cd211cea87d45391fc5f890984bbbe835192e0a0e31ca1ceb/Pytable_jim-1.0.3-py3-none-any.whl
Installing collected packages: Pytable-jim
Successfully installed Pytable-jim-1.0.3
```

**Comment by jimmyahalpara** [comment]
thanks for you reply, and i'll take care about that 'sir' thing,
i have uploaded total of three packages, i have the python files written of
them, i follow the steps given on
https://packaging.python.org/tutorials/packaging-projects/
and all the things works fine about uploading. but during download
something fishy happens. on my computer it installs in python 3 i cant
import it in python idle
and it dosent works properly or some times this happens.
this simplegui2pygamemodule i uploaded on pypi
c:\Python27\Scripts>pip install simplegui2pygamemodule
Collecting simplegui2pygamemodule
  Using cached
https://files.pythonhosted.org/packages/76/45/c48fdf386cfdf25a462c617e2da46849da86a6b1fe8a15f52f75ef7c1542/simplegui2pygamemodule-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory:
'c:\\users\\jimmy\\appdata\\local\\temp\\pip-install-smxxay\\simplegui2pygamemodule\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
c:\users\jimmy\appdata\local\temp\pip-install-smxxay\simplegui2pygamemodule\


i have total of three python code uploaded on pypi that are as follows on
pypi and their github link is as follows
PytableBox -   https://github.com/jimmyahalpara/Pytable/tree/Pytable
simplegui2pygamemodule -
https://github.com/jimmyahalpara/Pytable/tree/simplegui2pygamemodule
Pytable-jim - https://github.com/jimmyahalpara/Pytable/tree/Pytable

python code for all the modules is working well without any error
i exactly followed the procedure thet was specified in python website, i
created the directories and files in my computer as specified, uploaded
using some twine
the are showing all the packages on pypi also but all the error things
occure at installing.
https://pypi.org/project/simplegui2pygamemodule/
https://pypi.org/project/Pytable-jim/
https://pypi.org/project/PytableBox/

here pytable-jimmy and PytableBox module is same but Pytable- jim module
was occuring some problem with '-' dash so i uploaded another code with
name renamed
so ill be grateful if you help me, and as u told that the module will be
installed but not work in python as i cant import the module
thank you
