### ISSUE TITLE
Increase size limit request

### ISSUE THREAD

**Issue by Dapid** [pypa/packaging-problems#167]
Hi,

As said in #86, I'd like to request [PconsC4][1]. It is a trained deep learning model that requires 126 MB of storage.

We will be releasing a second version in the future (weeks-months) that will require almost double the space, is it better to request the whole thing now, or wait until it is ready?

Thank you!

   [1]: https://pypi.org/project/pconsc4/

**Comment by di** [comment]
Hi @Dapid, if this is still needed, please file an issue at https://github.com/pypa/warehouse/issues.
