### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by kcwayne53** [pypa/packaging-problems#173]
I am having trouble with installing my package.  Here is the output of creating the dist.  
I was able to upload the dist, but when it installs, it does not run the setup.py custom installation 

python3 setup.py sdist bdist_wheel
running sdist
running egg_info
writing top-level names to src/veriteem.egg-info/top_level.txt
writing dependency_links to src/veriteem.egg-info/dependency_links.txt
writing requirements to src/veriteem.egg-info/requires.txt
writing src/veriteem.egg-info/PKG-INFO
reading manifest file 'src/veriteem.egg-info/SOURCES.txt'
writing manifest file 'src/veriteem.egg-info/SOURCES.txt'
running check
creating veriteem-0.1.1
creating veriteem-0.1.1/src
creating veriteem-0.1.1/src/veriteem
creating veriteem-0.1.1/src/veriteem.egg-info
creating veriteem-0.1.1/src/veriteem/assets
creating veriteem-0.1.1/src/veriteem/bin
creating veriteem-0.1.1/src/veriteem/scripts
copying files to veriteem-0.1.1...
copying README.md -> veriteem-0.1.1
copying setup.py -> veriteem-0.1.1
copying src/veriteem/AccessControl.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem/AutoRun.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem/Config.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem/Configure.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem/InitGeth.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem/StartMiner.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem/Veriteem.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem/VeriteemConfig.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem/__init__.py -> veriteem-0.1.1/src/veriteem
copying src/veriteem.egg-info/PKG-INFO -> veriteem-0.1.1/src/veriteem.egg-info
copying src/veriteem.egg-info/SOURCES.txt -> veriteem-0.1.1/src/veriteem.egg-info
copying src/veriteem.egg-info/dependency_links.txt -> veriteem-0.1.1/src/veriteem.egg-info
copying src/veriteem.egg-info/requires.txt -> veriteem-0.1.1/src/veriteem.egg-info
copying src/veriteem.egg-info/top_level.txt -> veriteem-0.1.1/src/veriteem.egg-info
copying src/veriteem/assets/Config.json -> veriteem-0.1.1/src/veriteem/assets
copying src/veriteem/assets/LoadZigBee.js -> veriteem-0.1.1/src/veriteem/assets
copying src/veriteem/assets/errors.go -> veriteem-0.1.1/src/veriteem/assets
copying src/veriteem/assets/evm.go -> veriteem-0.1.1/src/veriteem/assets
copying src/veriteem/assets/genesis.json -> veriteem-0.1.1/src/veriteem/assets
copying src/veriteem/bin/installgo.sh -> veriteem-0.1.1/src/veriteem/bin
copying src/veriteem/scripts/AccessRights.js -> veriteem-0.1.1/src/veriteem/scripts
copying src/veriteem/scripts/AccessRights.sol -> veriteem-0.1.1/src/veriteem/scripts
copying src/veriteem/scripts/AccessRightsAddress.js -> veriteem-0.1.1/src/veriteem/scripts
copying src/veriteem/scripts/AddAccessRights.js -> veriteem-0.1.1/src/veriteem/scripts
copying src/veriteem/scripts/LoadAccessRights.js -> veriteem-0.1.1/src/veriteem/scripts
copying src/veriteem/scripts/LoadComplianceLedger.js -> veriteem-0.1.1/src/veriteem/scripts
Writing veriteem-0.1.1/setup.cfg
Creating tar archive
removing 'veriteem-0.1.1' (and everything under it)
running bdist_wheel
running build
running build_py
running build_scripts
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/Config.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/InitGeth.py -> build/bdist.linux-x86_64/wheel/veriteem
creating build/bdist.linux-x86_64/wheel/veriteem/bin
copying build/lib/veriteem/bin/veriteem -> build/bdist.linux-x86_64/wheel/veriteem/bin
copying build/lib/veriteem/bin/installgo.sh -> build/bdist.linux-x86_64/wheel/veriteem/bin
creating build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/AddAccessRights.js -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/Access.js -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/AccessRights.js -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/AccessRightsAddress.js -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/LoadComplianceLedger.js -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/AccessRights.sol -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/Alias.js -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/Password.js -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/scripts/LoadAccessRights.js -> build/bdist.linux-x86_64/wheel/veriteem/scripts
copying build/lib/veriteem/VeriteemConfig.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/AccessControl.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/__init__.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/Configure.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/AttachGeth.py -> build/bdist.linux-x86_64/wheel/veriteem
creating build/bdist.linux-x86_64/wheel/veriteem/assets
copying build/lib/veriteem/assets/udp.go -> build/bdist.linux-x86_64/wheel/veriteem/assets
copying build/lib/veriteem/assets/Config.json -> build/bdist.linux-x86_64/wheel/veriteem/assets
copying build/lib/veriteem/assets/errors.go -> build/bdist.linux-x86_64/wheel/veriteem/assets
copying build/lib/veriteem/assets/genesis.json -> build/bdist.linux-x86_64/wheel/veriteem/assets
copying build/lib/veriteem/assets/evm.go -> build/bdist.linux-x86_64/wheel/veriteem/assets
copying build/lib/veriteem/assets/LoadZigBee.js -> build/bdist.linux-x86_64/wheel/veriteem/assets
copying build/lib/veriteem/AutoRun.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/AttachVeriteem.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/StartMiner.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/VeriteemAttach.py -> build/bdist.linux-x86_64/wheel/veriteem
copying build/lib/veriteem/Veriteem.py -> build/bdist.linux-x86_64/wheel/veriteem
running install_egg_info
Copying src/veriteem.egg-info to build/bdist.linux-x86_64/wheel/veriteem-0.1.1-py3.5.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/veriteem-0.1.1.data
creating build/bdist.linux-x86_64/wheel/veriteem-0.1.1.data/scripts
copying build/scripts-3.5/VeriteemConfig.py -> build/bdist.linux-x86_64/wheel/veriteem-0.1.1.data/scripts
copying build/scripts-3.5/VeriteemAttach.py -> build/bdist.linux-x86_64/wheel/veriteem-0.1.1.data/scripts
copying build/scripts-3.5/Veriteem.py -> build/bdist.linux-x86_64/wheel/veriteem-0.1.1.data/scripts
changing mode of build/bdist.linux-x86_64/wheel/veriteem-0.1.1.data/scripts/VeriteemConfig.py to 775
changing mode of build/bdist.linux-x86_64/wheel/veriteem-0.1.1.data/scripts/VeriteemAttach.py to 775
changing mode of build/bdist.linux-x86_64/wheel/veriteem-0.1.1.data/scripts/Veriteem.py to 775
creating build/bdist.linux-x86_64/wheel/veriteem-0.1.1.dist-info/WHEEL
creating '/home/ubuntu/Veriteem/dist/veriteem-0.1.1-py3-none-any.whl' and adding '.' to it
adding 'veriteem/AccessControl.py'
adding 'veriteem/AttachGeth.py'
adding 'veriteem/AttachVeriteem.py'
adding 'veriteem/AutoRun.py'
adding 'veriteem/Config.py'
adding 'veriteem/Configure.py'
adding 'veriteem/InitGeth.py'
adding 'veriteem/StartMiner.py'
adding 'veriteem/Veriteem.py'
adding 'veriteem/VeriteemAttach.py'
adding 'veriteem/VeriteemConfig.py'
adding 'veriteem/__init__.py'
adding 'veriteem/assets/Config.json'
adding 'veriteem/assets/LoadZigBee.js'
adding 'veriteem/assets/errors.go'
adding 'veriteem/assets/evm.go'
adding 'veriteem/assets/genesis.json'
adding 'veriteem/assets/udp.go'
adding 'veriteem/bin/installgo.sh'
adding 'veriteem/bin/veriteem'
adding 'veriteem/scripts/Access.js'
adding 'veriteem/scripts/AccessRights.js'
adding 'veriteem/scripts/AccessRights.sol'
adding 'veriteem/scripts/AccessRightsAddress.js'
adding 'veriteem/scripts/AddAccessRights.js'
adding 'veriteem/scripts/Alias.js'
adding 'veriteem/scripts/LoadAccessRights.js'
adding 'veriteem/scripts/LoadComplianceLedger.js'
adding 'veriteem/scripts/Password.js'
adding 'veriteem-0.1.1.data/scripts/Veriteem.py'
adding 'veriteem-0.1.1.data/scripts/VeriteemAttach.py'
adding 'veriteem-0.1.1.data/scripts/VeriteemConfig.py'
adding 'veriteem-0.1.1.dist-info/top_level.txt'
adding 'veriteem-0.1.1.dist-info/WHEEL'
adding 'veriteem-0.1.1.dist-info/METADATA'
adding 'veriteem-0.1.1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
ERROR - Could not install veriteem package

**Comment by pradyunsg** [comment]
Hey @kcwayne53!

It's not clear to me from what you've posted why setup.py couldn't build your wheel. What do you mean by your "custom installation"?

**Comment by kcwayne53** [comment]
setup.py has the ability to define a custom install function that is run when the package is installed with python3 setup.py install via the 

setup(
   cmdclass={'install': CustomInstall},
   ....

declaration.  Install is a keyword in setup.py, CustomInstall is my custom function I wanted to have executed.

When using pip3 to install however, this is not executed.

I worked around the problem by moving the functionality I had specified in the CustomInstall method outside of the setup.py and built it into my app.   I do not like the approach, because the work it is doing is setup related, and it is not known whether the setup is complete until the first time I run the app and it detects it still has setup/installation work to do.

**Comment by pradyunsg** [comment]
Ah. Right.

When you build a wheel or mostly use pip to install a package, `setup.py install` is not a command that's run. Instead, a wheel is built using `bdist_wheel`.

I think what you're doing currently is indeed the best approach here -- if there's post installation logic, it would need to be executed separately after pip installing the project.

**Comment by webknjaz** [comment]
Running `setup.py` directly is no longer supported: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html. It needs to be replaced by automation in one of the workflow tools: https://packaging.python.org/en/latest/guides/tool-recommendations/#workflow-tools.
