### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by mahbubk9** [pypa/packaging-problems#175]
Hi, although i installed pip installed twin in previous step, it's showing this error
\Users\Mahbub>twine upload --repository-url https://test.pypi.org/legacy/ dist/*
'twine' is not recognized as an internal or external command,
operable program or batch file.

Please help

**Comment by merwok** [comment]
Did you install twine?

**Comment by pradyunsg** [comment]
It seems like @mahbubk9 did install twine.

@mahbubk9 Does using `python -m twine` work? If not, could you tell us what OS are you working on and what version of Python you're using?
