### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by NapsterInBlue** [pypa/packaging-problems#176]
Have gotten through building/[hosting a simple package on test.pypi](https://test.pypi.org/simple/example-pkg-napsterinblue/) via

```
python setup.py sdist bdist_wheel
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```

but am now running into an error when I run (with `--trusted-host` because I'm on my work network and was getting SSL errors)
 
```
python -m pip install --trusted-host --index-url https://test.pypi.org/legacy/ example_pkg_napsterinblue
 ```
that reads
 
```
Cannot unpack file C:\Users\NHOUNS~1\AppData\Local\Temp\pip-unpack-zv61608h\simple (downloaded from C:\Users\NHOUNS~1\AppData\Local\Temp\pip-req-build-9b1hvdiv, content-type: text/html; charset=UTF-8); cannot detect archive format
Cannot determine archive format of C:\Users\NHOUNS~1\AppData\Local\Temp\pip-req-build-9b1hvdiv
```
 
Can anybody hazard a guess why this might be happening? [Link to the repository here.](https://github.com/NapsterInBlue/example_pkg_napsterinblue)

**Comment by benoit-pierre** [comment]
`--trusted-host` expect an argument, so the command line should be:
```
python -m pip install --trusted-host test.pypi.org --index-url https://test.pypi.org/legacy/ example_pkg_napsterinblue
```
You also might need to add `--trusted-host test-files.pythonhosted.org`.

**Comment by NapsterInBlue** [comment]
Hey, that did the trick. Thank you!

For anyone in the future reading this, command I wound up running was 

```
python -m pip install --trusted-host test.pypi.org --trusted-host test-files.pythonhosted.org --index-url https://test.pypi.org/simple/ example_pkg_napsterinblue
```

#### Follow-up question in that regard

I initially pushed up to test.pypi/**legacy** per, [this chunk of the tutorial](https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives)

However, I had to change the aforementioned pip install command to pull from `simple`, not `legacy`.

Is that typical/intended?

**Comment by benoit-pierre** [comment]
It looks like this section needs to be updated, as per [Using TestPyPI with pip](https://packaging.python.org/guides/using-testpypi/#using-testpypi-with-pip).

**Comment by NapsterInBlue** [comment]
Right on. Thanks for all of your help! Really appreciate you taking the time to help me get my head on straight.
