### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by yhkun** [pypa/packaging-problems#179]
python setup.py sdist bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

**Comment by benoit-pierre** [comment]
You need the `wheel` package to be installed for the `bdist_wheel` command to be available.

**Comment by 15920384819** [comment]
My system is Windows, what is the command?

**Comment by benoit-pierre** [comment]
`python -m pip install wheel`

**Comment by 15920384819** [comment]
I have installed wheel
Requirement already satisfied: wheel in f:\pythonanaconda3\lib\site-packages (0.31.1)

**Comment by benoit-pierre** [comment]
Are you sure your `setup.py` is using setuptools? (and not distutils).

**Comment by 15920384819** [comment]
I used distutils, how should I change it?

**Comment by benoit-pierre** [comment]
See the tutorial: https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py
