### ISSUE TITLE
Simple mirroring of PyPI

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#18]
People would like to be able to simply mirror PyPI without much fuss. Does bandersnatch work for them? If not what does bandersnatch or a hypothetical new client need to have?

**Comment by brainwane** [comment]
We now have explicit recommendations for this scenario so I'm going to call this closed. People can reopen it if there's a need that bandersnatch and devpi do not fulfill.

**Comment by merwok** [comment]
Link was broken → https://packaging.python.org/guides/index-mirrors-and-caches/
