### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Syndace** [pypa/packaging-problems#184]
Yo!

I want to publish a package on pip and tried to do so [here](https://test.pypi.org/project/XEdDSA/).

For some reason, everything works fine but when I try to install the package pip thinks the available versions do not fit my system.

This is how I try to install the package:

```bash
$ pip3 --no-cache-dir install -i https://test.pypi.org/simple/ xeddsa
Looking in indexes: https://test.pypi.org/simple/
Collecting xeddsa
  Could not find a version that satisfies the requirement xeddsa (from versions: 0.3.0.linux-x86_64, 0.3.1.linux-x86_64, 0.3.2.linux-x86_64)
No matching distribution found for xeddsa
```

pip finds three version, but none of them seem good enough ^^

I guess I screwed something up in the [setup.py](https://pastebin.com/iai5iBmR).

As you can see, my first idea was to comment out the `python_requires` declaration but it does not fix the problem.

Any idea what could disqualify the package for my pip?

**Comment by merwok** [comment]
What is your system?

**Comment by Syndace** [comment]
A 64-bit Linux (xubuntu, if that's important).

I'm trying to install the package on the same system I created it on.

**Comment by Syndace** [comment]
Could it be wrong Classifiers? Do they get checked by pip?

**Comment by Syndace** [comment]
Crap I ran `bdist` instead of `sdist`, my bad.

Thanks anyway :D
