### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Ikiz** [pypa/packaging-problems#190]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?  Windows 10

2. What is your Python version?
3.6.5

3. What version of pip do you have?
18.0

4. Could you describe your issue in as much detail as possible?
The input "python3" is not recognized as an internal or external comman, operable program or batch file.

**Comment by merwok** [comment]
Did you follow the [official installation steps](https://docs.python.org/3/using/windows.html#installation-steps) ?
