### ISSUE TITLE
or call settings.configure

### ISSUE THREAD

**Issue by navyhan** [pypa/packaging-problems#194]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. Could you describe your issue in as much detail as possible?

**Comment by di** [comment]
Closing, there doesn't seem to be any content here. Feel free to update if this was a mistake.
