### ISSUE TITLE
Size limit increase for gym-retro

### ISSUE THREAD

**Issue by endrift** [pypa/packaging-problems#195]
New version of gym-retro adds a lot of data and the packages end up being roughly 151MB on Linux. If we could get a size limit increase to somewhere between 180 to 200MB or so that would let me upload the latest builds with enough room for a little more growth (though I don't expect them to get much larger).

(See also #140)

**Comment by di** [comment]
I've set the upload limit for `gym-retro` to 200MB on both PyPI and TestPyPI.

**Comment by endrift** [comment]
Thanks!
