### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by lesatdgl** [pypa/packaging-problems#198]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version? - linux ubuntu 16.04

2. What is your Python version? 3.6.6

3. What version of pip do you have? pipenv, version 2018.05.18

4. Could you describe your issue in as much detail as possible? Building a package , egg-info pkg being built - with bad info - specifically pkg name "dgl_lib" being changed to "dgl-lib"  - no errors

Used instruction in https://packaging.python.org/tutorials/packaging-projects/

+++++++++++++++ Console ++++++++++++++
xenial)les@localhost:~/dgl-home/dgl_lib$ python setup.py sdist bdist_wheel
running sdist
running egg_info
creating dgl_lib.egg-info
writing dgl_lib.egg-info/PKG-INFO
writing dependency_links to dgl_lib.egg-info/dependency_links.txt
writing top-level names to dgl_lib.egg-info/top_level.txt
writing manifest file 'dgl_lib.egg-info/SOURCES.txt'
reading manifest file 'dgl_lib.egg-info/SOURCES.txt'
writing manifest file 'dgl_lib.egg-info/SOURCES.txt'
running check
creating dgl_lib-0.0.1
creating dgl_lib-0.0.1/dgl_lib.egg-info
creating dgl_lib-0.0.1/test
copying files to dgl_lib-0.0.1...
copying README.md -> dgl_lib-0.0.1
copying setup.py -> dgl_lib-0.0.1
copying dgl_lib.egg-info/PKG-INFO -> dgl_lib-0.0.1/dgl_lib.egg-info
copying dgl_lib.egg-info/SOURCES.txt -> dgl_lib-0.0.1/dgl_lib.egg-info
copying dgl_lib.egg-info/dependency_links.txt -> dgl_lib-0.0.1/dgl_lib.egg-info
copying dgl_lib.egg-info/top_level.txt -> dgl_lib-0.0.1/dgl_lib.egg-info
copying test/testDglContainers.py -> dgl_lib-0.0.1/test
Writing dgl_lib-0.0.1/setup.cfg
creating dist
Creating tar archive
removing 'dgl_lib-0.0.1' (and everything under it)
running bdist_wheel
running build
installing to build/bdist.linux-x86_64/wheel
running install
running install_egg_info
Copying dgl_lib.egg-info to build/bdist.linux-x86_64/wheel/dgl_lib-0.0.1-py3.6.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/dgl_lib-0.0.1.dist-info/WHEEL
(xenial)les@localhost:~/dgl-home/dgl_lib$ ls -atl
total 120
drwxrwxr-x  2 les les   4096 Sep  8 19:18 dist
drwxrwxr-x  8 les les   4096 Sep  8 19:18 .
drwxrwxr-x  3 les les   4096 Sep  8 19:18 build
drwxrwxr-x  2 les les   4096 Sep  8 19:18 dgl_lib.egg-info
drwxr-xr-x 10 les root  4096 Sep  8 17:15 ..
drwxrwxr-x  7 les les   4096 Sep  8 16:24 .git
-rw-rw-r--  1 les les  20500 Sep  3 18:34 dglContactsClasses.py
-rw-rw-r--  1 les les    190 Aug 28 19:56 README.md
-rw-rw-r--  1 les les    625 Aug 28 19:53 setup.py
-rw-rw-r--  1 les les  34502 Aug 28 19:52 LICENSE
-rw-rw-r--  1 les les     17 Aug 28 19:42 __init__.py
drwxrwxr-x  2 les les   4096 Aug 27 19:40 doc
-rw-rw-r--  1 les les   4349 Aug 18 15:01 dglPickleToS3BucketClasses.py
drwxrwxr-x  2 les les   4096 Aug 17 16:50 test
-rwxrwxrwx  1 les les   1911 Jun 16 14:31 .gitignore
-rw-rw-r--  1 les les    784 Jun 10 00:24 gaicClasses.py

++++++++++++++++++ setup.py +++++++++++++
import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="dgl_lib",
    version="0.0.1",
    author="Les Dunaway",
    author_email="les@dunawaygroupllc.com",
    description="Python 3 Class library for DGL Contacts apps",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/pypa/dgl_lib",
    packages=setuptools.find_packages(),
    classifiers=(
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GNU License",
        "Operating System :: OS Independent",
    ),
)

**Comment by benoit-pierre** [comment]
That's not a bug, as per [PEP 426](https://www.python.org/dev/peps/pep-0426/#name), hyphens and underscores are considered to be equivalent: setuptools will normalize the name, replacing underscores by hyphens (among other things).

**Comment by lesatdgl** [comment]
Well, linux file systems SURE don't agree with that and it makes pipenv crazy during install - only the egg-info gets messed-with nowhere else.
In any case, thanks, I'll fix it another way
