### ISSUE TITLE
Confusion about easy_install vs pip

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#2]
There is confusion about if users should be using `easy_install` or if they should be using `pip`. A lot of documentation exists currently that points in one direction or the other with varying levels of snark involved. How best can we guide users to "one way to do it"?

**Comment by hickford** [comment]
The docs at https://pythonhosted.org/setuptools/easy_install.html should at least mention Pip, I think

**Comment by brainwane** [comment]
Now that packaging.python.org is the official packaging documentation site and [officially recommends pip](https://packaging.python.org/tutorials/installing-packages/#use-pip-for-installing), can we close this issue?

**Comment by ncoghlan** [comment]
Aye, we clearly recommend pip, and https://packaging.python.org/discussions/pip-vs-easy-install/ discusses the trade-offs between them.

https://github.com/pypa/setuptools/issues/917 is an open setuptools issue discussing the various barriers to deprecating easy_install and switching setuptools entirely over to relying on pip.

So I don't think there's any further ecosystem level questions here - it's just an internal question for the setuptools devs as to how they want to handle this in their documentation and code.
