### ISSUE TITLE
Description not displayed when it contains newlines

### ISSUE THREAD

**Issue by bittner** [pypa/packaging-problems#201]
Environment
--------
- OS/distro: Ubuntu 18.04.1 Bionic
- Python 3.7.0
- pip 18.0 (python 3.7)
- twine version 1.12.1 (pkginfo: 1.4.2, requests: 2.19.1, setuptools: 40.4.3, requests-toolbelt: 0.8.0, tqdm: 4.26.0)

Problem Description
-------------
When publishing a project, and the `description` key value contains newlines at the beginning and/or the end then PyPI seems to have trouble to display it.

The fix is using `strip()` e.g.
```python
setup(
    name=package.name,
    version=package.__version__,
    description=package.__doc__.strip(),
    long_description=read_file('README.md'),
    long_description_content_type='text/markdown',
    ...
```

Suggested Correction
------------

PyPI and/or the uploading tool should automatically strip the short description key.

Example Project
------------

- https://test.pypi.org/manage/project/PythonTurtle/releases/

**Comment by di** [comment]
Related:
* https://github.com/pypa/twine/issues/262
* https://github.com/pypa/setuptools/issues/1390

**Comment by bittner** [comment]
This is the very same issue that leads to #202: The tools that generate the PKG-INFO file must ensure that data that is supposed to be a single line of text doesn't contain line breaks.

The correct behavior of those tools should be to abort the processing, requiring the data format or content to be fixed.

**Comment by bittner** [comment]
Closing in favor of https://github.com/pypa/setuptools/issues/1390 (duplicate).
