### ISSUE TITLE
Markdown README not displaying on PyPI (despite Description-Content-Type: text/markdown)

### ISSUE THREAD

**Issue by bittner** [pypa/packaging-problems#202]
Environment
--------
- OS/distro: Ubuntu 18.04.1 Bionic
- Python 3.7.0
- pip 18.0 (python 3.7)
- twine version 1.12.1 (pkginfo: 1.4.2, requests: 2.19.1, setuptools: 40.4.3, requests-toolbelt: 0.8.0, tqdm: 4.26.0)

Problem Description
-------------
When publishing a project with a README.md (Markdown) as the `long_description` and `long_description_content_type='text/markdown'` then PyPI displays all the submitted content in raw text format (instead of converted to HTML).

```python
def read_file(filename):
    with open(os.path.join(os.path.dirname(__file__), filename)) as file:
        return file.read()

setup(
    name=package.name,
    version=package.__version__,
    description=package.__doc__.strip(),
    long_description=read_file('README.md'),
    long_description_content_type='text/markdown',
    ...
```

Expected Behavior
------------

1. PyPI should display the README correctly (e.g. as on GitHub) on PyPI.
1. If there is a conversion problem the uploading tool should report an error, and abort; ideally, PyPI should refuse to accept content it won't display nicely.

Example Project
------------

- https://test.pypi.org/manage/project/PythonTurtle/releases/

See also: https://github.com/cool-RR/PythonTurtle/pull/121

**Comment by benoit-pierre** [comment]
You're getting hit by this issue: https://github.com/pypa/setuptools/issues/1390.

**Comment by bittner** [comment]
It bug was: `description` must by all means be a single line. I'm now parsing it out of `__doc__`:
```python
description=package.__doc__.strip().split('\n')[0]
```
Would be cool if there was a way to detect that as a problem and abort the upload.

**Comment by benoit-pierre** [comment]
You can't detect this at the upload level: it is valid, the problem must be detected at build time by setuptools.

**Comment by bittner** [comment]
Closing in favor of https://github.com/pypa/setuptools/issues/1390 (duplicate).
