### ISSUE TITLE
Require an increase in file size for Intel's cpu-optimized tensorflow lib

### ISSUE THREAD

**Issue by s1113950** [pypa/packaging-problems#206]
I am having the same issue as https://github.com/pypa/packaging-problems/issues/103. I'm a part of Intel as well and I'm trying to publish `tensorflow-mkl`, essentially a copy of `tensorflow` but optimized for CPU using the Intel MKL library. AFAIK previously we didn't publish it and only have dockerfiles with a compile flag for users, but now we've been asked to provide our own library. 

I'm currently trying to do this with our `test.pypi.org` account of `IntelAI` before I push the real thing to our prod account `nervanasys`. I either get this:
```
robertso@robertso-mac02:~/Nervana$ twine upload --repository-url https://test.pypi.org/legacy/ tensorflow_mkl-1.11.0-cp*
Enter your username: IntelAI
Enter your password:
Uploading distributions to https://test.pypi.org/legacy/
Uploading tensorflow_mkl-1.11.0-cp27-cp27mu-linux_x86_64.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 413M/413M [03:08<00:00, 2.30MB/s]
Received "502: Bad Gateway" Package upload appears to have failed.  Retry 1 of 5
Uploading tensorflow_mkl-1.11.0-cp27-cp27mu-linux_x86_64.whl
```
Or I get `Received "503: first byte timeout" Package upload appears to have failed` (often on subsequent retries).

The `whl` we're trying to publish is 413MB in size

**Comment by s1113950** [comment]
I just learned that we have another `mkl` account here: https://pypi.org/project/mkl/#files with very large files. I am waiting on getting credentials to that account and then would like to publish this `mkl` package there if possible

**Comment by s1113950** [comment]
Ahh I screwed something up with wheel creation. The real wheel size should be closer to 106 MB

**Comment by s1113950** [comment]
Latest wheel sizes: 
```
-rw-r--r--. 1 robertso jenkins 107066238 Nov  1 13:41 intel_tensorflow-1.11.0-cp27-cp27mu-linux_x86_64.whl
-rw-r--r--. 1 robertso jenkins 107058950 Nov  1 13:42 intel_tensorflow-1.11.0-cp34-cp34m-linux_x86_64.whl
-rw-r--r--. 1 robertso jenkins 107057417 Nov  1 13:43 intel_tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl
-rw-r--r--. 1 robertso jenkins 107057167 Nov  1 13:44 intel_tensorflow-1.11.0-cp35-cp35m-linux_x86_64.whl
```

**Comment by di** [comment]
The warehouse tracker is the right place for these requests.
