### ISSUE TITLE
pmxbot has been banned from pypa and pypa-dev

### ISSUE THREAD

**Issue by jaraco** [pypa/packaging-problems#207]
In a conversation today, I learned that the `#pypa` and `pypa-dev` channels have been set to `+r` (requiring authentication). As a result, the pmxbot is not there and the channels aren't being logged as intended.

There is at least some interest in retaining that setting, so let's investigate what it takes to (a) create credentials for pmxbot in Freenode and (b) enable the bot to use those credentials.

- [x] Create an e-mail address for pmxbot on Freenode.
- [x] Create credentials for pmxbot on Freenode.
- [x] Configure the bot with the credentials.

**Comment by jaraco** [comment]
Looking at the [registration docs](https://freenode.net/kb/answer/registration), a real e-mail address is required. So pmxbot now needs an e-mail address. I'll have to think a bit about the implications of this and where the e-mail should be.

**Comment by dstufft** [comment]
FWIW I don't think Freenode has ever sent me an email to my registered email address except for the initial one to verify that the email is real. I'm pretty sure the requirement is just to make it harder for spam bots to make registered nicks, and not for any actual communication or the like.

I think they might also support account recovery via email as well?

**Comment by KOLANICH** [comment]
>I think they might also support account recovery via email as well?

They do.

**Comment by pradyunsg** [comment]
> I'll have to think a bit about the implications of this and where the e-mail should be.

@jaraco Have you had the time to give this a thought?

**Comment by jaraco** [comment]
I currently have the address `pmxbot@jaraco.com`, so I'll plan to use that.
