### ISSUE TITLE
PyPi size limit for GeoPySpark

### ISSUE THREAD

**Issue by echeipesh** [pypa/packaging-problems#221]
Similar to https://github.com/pypa/packaging-problems/issues/90 GeoPySpark needs to ship yet more jars to geosnatially enable `pyspark`. 

The side-load process we're doing suffers in usability, it would be ideal to distribute jars with the python code through PyPI.

https://pypi.org/project/geopyspark/

Current size of `geopyspark-0.4.3-py3.7.egg` with jars is `123M`.

**Comment by metasim** [comment]
FWIW, `locationtech/rasterframes` has similar requirements (just not quite as big): `pyrasterframes-0.8.0.dev0-py2.py3-none-any.whl` is `62M`.

**Comment by pradyunsg** [comment]
Hi @echeipesh!

Thanks for your patience! I've gone I've set the upload limit for geopyspark to 250MB on PyPI.

Please be mindful of how often you make releases at this size.

**Comment by pradyunsg** [comment]
@metasim I am not sure what you're requesting -- if you have a specific upload limit request, please file a new issue over at https://github.com/pypa/warehouse/issues (see https://github.com/pypa/warehouse/issues/5542 for reference).

**Comment by metasim** [comment]
@pradyunsg Sorry.... not asking for anything, just indicating that a number of us in the Spark community run into this issue, in case community awareness was helpful.

**Comment by pradyunsg** [comment]
> just indicating that a number of us in the Spark community run into this issue, in case community awareness was helpful.

Yep yep; it definitely is; thanks for the information! :)
