### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by MacLake** [pypa/packaging-problems#229]
1. What is your operating system and version?
Linux Debian 9 Stretch

2. What is your Python version?
Python 3.5.3

3. What version of pip do you have?
pip 18.1

4. Could you describe your issue in as much detail as possible?
I followed the [tutorial Packaging Python Projects](https://packaging.python.org/tutorials/packaging-projects/#generating-archives) to create a pip package of a Django CMS plug-in.  Everything seemed to work fine, but it turned out that the `static` and `templates` directories are missing in the archive files. They are both non-code directories with no `__init__.py` in it, I guess that’ſ the reason why they aren’ŧ included, but these static files and CMS templates belong to the project, and probably it’s bot a so exotic thing to include non-Python files in a pip package. So it should be described in the tutorial how to tell setuptools to include these files.

Jens

**Comment by MacLake** [comment]
Okay, I’f found the solution in the meantime. Nevertheless, it should be mentioned in the tutorial.

**Comment by merwok** [comment]
If you are using setuptools, you need to define «package data» options.

With flit, it is automatic.

**Comment by njsmith** [comment]
You also need to set up MANIFEST.in correctly, which makes it easy to get wrong...

**Comment by merwok** [comment]
> You also need to set up MANIFEST.in correctly

Not for package_data (unless I remember wrong or things have changed)
