### ISSUE TITLE
Interaction with the Science Community

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#23]
The science community has it's own packaging tools and there doesn't seem to be a lot of cross pollination.

**Comment by pradyunsg** [comment]
Is this still relevant?

**Comment by ncoghlan** [comment]
While there's still work to be done in getting `conda` and `pip` to play nice, we have pretty good communication both ways between PyPA and folks working on more data-science-centric tools, so I don't think we're gaining anything from keeping this open.
