### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by ShankarCat** [pypa/packaging-problems#233]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows XP Service Pack 2

2. What is your Python version?

Python 3.4.3

3. What version of pip do you have?

Version 18.1

4. Could you describe your issue in as much detail as possible?

I first installed and upgraded setuptools and wheel.
It successfully upgraded.
Then I ran the Command-python setup.py sdist bdist_wheel.
It gives error - invalid command 'bdist_wheel'

If i use the command-python setup.py sdist 
It works and creates the distrubution.

please help me to create wheels.

**Comment by merwok** [comment]
Can you say what guide you followed about wheels?
