### ISSUE TITLE
Pypi package size limit for Analytics Zoo

### ISSUE THREAD

**Issue by jason-dai** [pypa/packaging-problems#236]
I wonder if it is possible to increase the limit of https://pypi.org/project/analytics-zoo/ to 120MB? Analytics Zoo (https://github.com/intel-analytics/analytics-zoo) is a unified analytics + AI platform for distributed TensorFlow, Keras and BigDL on Apache Spark; and the reason for the large size (esp. for the upcoming releases) is that it will include more .so files for hardware accelerations, model optimizations, etc.

**Comment by pradyunsg** [comment]
Please request on github.com/pypa/warehouse.

**Comment by theacodes** [comment]
Actually it's totally fine ot be here.

**Comment by theacodes** [comment]
@jason-dai can you help me understand why all of this needs to be in one package? Can some of these optimizations be in other packages (that `analytics-zoo` can then depend on)?

**Comment by jamadden** [comment]
This was resolved in https://github.com/pypa/warehouse/issues/5359
