### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Bdukester10** [pypa/packaging-problems#237]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?
3.7.1

3. What version of pip do you have?

19.0.1

4. Could you describe your issue in as much detail as possible?

I used the command python setup.py sdist bdist_wheel and it returned this:
File "setup.py", line 15
    packages = setuptools.find_packages(),
           ^
SyntaxError: invalid syntax
I made sure everything was good, idk what is wrong.

**Comment by merwok** [comment]
This error must be caused by something on a previous line.
Can you include the whole setup script?

**Comment by Bdukester10** [comment]
import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="python_siri_project_bdukester10",
    version = "1.5.0",
    author = "Ben Duke",
    author_email = "baduke01@gmail.com",
    description = " This is a customizable Siri for your windows 10 machine",
    long_description = long_description,
    long_description_content_type = "text/markdown",
    url = "https://github.com/Bdukester10/custom_siri_project"
    packages = setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: Windows 10:",
    ],
)

**Comment by di** [comment]
You're missing a comma here:

```diff
import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="python_siri_project_bdukester10",
    version="1.5.0",
    author="",
    author_email="",
    description=" This is a customizable Siri for your windows 10 machine",
    long_description=long_description,
    long_description_content_type="text/markdown",
-   url="https://github.com/Bdukester10/custom_siri_project"
+   url="https://github.com/Bdukester10/custom_siri_project",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: Windows 10:",
    ],
)
```

**Comment by Bdukester10** [comment]
I feel dumb... thanks though

**Comment by theacodes** [comment]
Happens to all of us! I recommend checking out tools such as flake8 or IDEs
with integrated syntax checking (like PyCharm) - they're super helpful for
sussing this stuff out.
