### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by QuassarLunar** [pypa/packaging-problems#241]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

 Windows 10

2. What is your Python version?

 Python 3.7.2

3. What version of pip do you have?

 pip 18.1

4. Could you describe your issue in as much detail as possible?

        error : invalid command 'bdist_wheel'

**Comment by merwok** [comment]
What instructions are you following?

Have you installed wheel in your Python environment?
