### ISSUE TITLE
Frozen (WeakREF)

### ISSUE THREAD

**Issue by DenDog1** [pypa/packaging-problems#243]
u0_a482@localhost [~]: python -v
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# /data/data/com.termux/files/usr/lib/python3.7/encodings/__pycache__/__init__.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/encodings/__init__.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/encodings/__pycache__/__init__.cpython-37.pyc'
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/codecs.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/codecs.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/codecs.cpython-37.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b24a470>
# /data/data/com.termux/files/usr/lib/python3.7/encodings/__pycache__/aliases.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/encodings/aliases.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/encodings/__pycache__/aliases.cpython-37.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b257e48>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b2bdeb8>
# /data/data/com.termux/files/usr/lib/python3.7/encodings/__pycache__/utf_8.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/encodings/utf_8.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/encodings/__pycache__/utf_8.cpython-37.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b267b70>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /data/data/com.termux/files/usr/lib/python3.7/encodings/__pycache__/latin_1.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/encodings/latin_1.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/encodings/__pycache__/latin_1.cpython-37.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b26a5f8>
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/io.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/io.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/io.cpython-37.pyc'
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/abc.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/abc.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/abc.cpython-37.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b26aba8>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b26a7f0>
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/_bootlocale.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/_bootlocale.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/_bootlocale.cpython-37.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b26aa58>
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/site.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/site.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/site.cpython-37.pyc'
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/os.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/os.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/os.cpython-37.pyc'
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/stat.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/stat.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/stat.cpython-37.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b20a0b8>
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/posixpath.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/posixpath.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/posixpath.cpython-37.pyc'
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/genericpath.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/genericpath.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/genericpath.cpython-37.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b210b70>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b20a7f0>
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/_collections_abc.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/_collections_abc.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/_collections_abc.cpython-37.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b219208>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b27acf8>
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/_sitebuiltins.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/_sitebuiltins.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/_sitebuiltins.cpython-37.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b27afd0>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b2719e8>
Python 3.7.2 (default, Jan 16 2019, 21:05:09)
[Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242d on linux
Type "help", "copyright", "credits" or "license" for more information.
# extension module 'readline' loaded from '/data/data/com.termux/files/usr/lib/python3.7/lib-dynload/readline.cpython-37m.so'
# extension module 'readline' executed from '/data/data/com.termux/files/usr/lib/python3.7/lib-dynload/readline.cpython-37m.so'
import 'readline' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7f2b23c630>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# /data/data/com.termux/files/usr/lib/python3.7/__pycache__/rlcompleter.cpython-37.pyc matches /data/data/com.termux/files/usr/lib/python3.7/rlcompleter.py
# code object from '/data/data/com.termux/files/usr/lib/python3.7/__pycache__/rlcompleter.cpython-37.pyc'
import 'rlcompleter' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2b23c748

# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _thread
# cleanup[2] removing _warnings
# cleanup[2] removing _weakref
# cleanup[2] removing zipimport
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing posix
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing codecs
# cleanup[2] removing _codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing io
# destroy io
# cleanup[2] removing abc
# cleanup[2] removing _abc
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing _locale
# cleanup[2] removing site
# destroy site
# cleanup[2] removing os
# cleanup[2] removing stat
# cleanup[2] removing _stat
# cleanup[2] removing posixpath
# cleanup[2] removing genericpath
# cleanup[2] removing os.path
# cleanup[2] removing _collections_abc
# destroy _collections_abc
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing readline
# cleanup[2] removing atexit
# cleanup[2] removing rlcompleter
# destroy rlcompleter
# destroy zipimport
# destroy _signal
# destroy _abc
# destroy _locale
# destroy _sitebuiltins
# destroy abc
# destroy posixpath
# destroy _stat
# destroy genericpath
# destroy os
# destroy stat
# destroy atexit
# destroy __main__
# destroy readline
# cleanup[3] wiping _frozen_importlib
# destroy _frozen_importlib_external
# cleanup[3] wiping _imp
# cleanup[3] wiping _thread
# cleanup[3] wiping _warnings
# cleanup[3] wiping _weakref
# cleanup[3] wiping _io
# cleanup[3] wiping marshal
# cleanup[3] wiping posix
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
u0_a482@localhost [~]:

**Comment by KOLANICH** [comment]
What is it?

**Comment by DenDog1** [comment]
because my be little brother does not know how to keep his hands to him self..

**Comment by KOLANICH** [comment]
Could you remove this long log then?
