### ISSUE TITLE
Requesting increase of Pypi package size limit

### ISSUE THREAD

**Issue by sbonaretti** [pypa/packaging-problems#245]
Hi,
I would like to ask you an increase of package size limit for my package pyKNEEr: https://pypi.org/project/pykneer/. I have already uploaded a smaller version. The .whl file I would like to uploas is 75.6MB.
Please, let me know if I should provide further information. 
Thanks,
Serena

**Comment by theacodes** [comment]
Hi @sbonaretti, I've set the upload limit for `pykneer` to `100mb`. Happy publishing!
