### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by BenLHedgepeth** [pypa/packaging-problems#253]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

 Windows 10

2. What is your Python version?

Python 3.7.2

3. What version of pip do you have?

pip 19.0.3

4. Could you describe your issue in as much detail as possible?

https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

The error I encountered is as follows:

>>>setup.py sdist bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

**Comment by theacodes** [comment]
Hi, you'll need to `python3 -m pip install wheel`, then that command will work. 

I'm going to close this issue, but let me know if you have any other questions.

**Comment by BenLHedgepeth** [comment]
I edited my original question to reflect a new problem I'm encountering.

**Comment by theacodes** [comment]
can you provide the output of running `python3 setup.py sdist bdist_wheel`?

(also, please don't edit the original issue in these cases, it makes it difficult to comprehend stuff when others look at this issue).

**Comment by BenLHedgepeth** [comment]
running sdist
running egg_info
writing test_package1_binny_bit.egg-info\PKG-INFO
writing dependency_links to test_package1_binny_bit.egg-info\dependency_links.txt
writing requirements to test_package1_binny_bit.egg-info\requires.txt
writing top-level names to test_package1_binny_bit.egg-info\top_level.txt
reading manifest file 'test_package1_binny_bit.egg-info\SOURCES.txt'
writing manifest file 'test_package1_binny_bit.egg-info\SOURCES.txt'
running check
creating test_package1_binny_bit-1.0
creating test_package1_binny_bit-1.0\app
creating test_package1_binny_bit-1.0\test_package1_binny_bit.egg-info
copying files to test_package1_binny_bit-1.0...
copying README.md -> test_package1_binny_bit-1.0
copying setup.py -> test_package1_binny_bit-1.0
copying app\__init__.py -> test_package1_binny_bit-1.0\app
copying app\main.py -> test_package1_binny_bit-1.0\app
copying test_package1_binny_bit.egg-info\PKG-INFO -> test_package1_binny_bit-1.0\test_package1_binny_bit.egg-info
copying test_package1_binny_bit.egg-info\SOURCES.txt -> test_package1_binny_bit-1.0\test_package1_binny_bit.egg-info
copying test_package1_binny_bit.egg-info\dependency_links.txt -> test_package1_binny_bit-1.0\test_package1_binny_bit.egg-info
copying test_package1_binny_bit.egg-info\requires.txt -> test_package1_binny_bit-1.0\test_package1_binny_bit.egg-info
copying test_package1_binny_bit.egg-info\top_level.txt -> test_package1_binny_bit-1.0\test_package1_binny_bit.egg-info
Writing test_package1_binny_bit-1.0\setup.cfg
Creating tar archive
removing 'test_package1_binny_bit-1.0' (and everything under it)
running bdist_wheel
running build
running build_py
installing to build\bdist.win-amd64\wheel
running install
running install_lib
creating build\bdist.win-amd64\wheel
creating build\bdist.win-amd64\wheel\app
copying build\lib\app\main.py -> build\bdist.win-amd64\wheel\.\app
copying build\lib\app\__init__.py -> build\bdist.win-amd64\wheel\.\app
running install_egg_info
Copying test_package1_binny_bit.egg-info to build\bdist.win-amd64\wheel\.\test_package1_binny_bit-1.0-py3.7.egg-info
running install_scripts
creating build\bdist.win-amd64\wheel\test_package1_binny_bit-1.0.dist-info\WHEEL
creating 'dist\test_package1_binny_bit-1.0-py3-none-any.whl' and adding 'build\bdist.win-amd64\wheel' to it
adding 'app/__init__.py'
adding 'app/main.py'
adding 'test_package1_binny_bit-1.0.dist-info/METADATA'
adding 'test_package1_binny_bit-1.0.dist-info/WHEEL'
adding 'test_package1_binny_bit-1.0.dist-info/top_level.txt'
adding 'test_package1_binny_bit-1.0.dist-info/RECORD'
removing build\bdist.win-amd64\wheel

**Comment by merwok** [comment]
You have to run the build commands first (bdist_wheel and sdist), then twine upload.
