### ISSUE TITLE
How to propose a new topic in the classifiers

### ISSUE THREAD

**Issue by raoulcollenteur** [pypa/packaging-problems#254]
Not sure if this is the right place but hopefully someone can help. I would like to add a topic in the classifiers, to be able to document/collect python packages in the field of Hydrology. There are many packages being developed in this field (see e.g., https://github.com/raoulcollenteur/Python-Hydrology-Tools) and centrally documenting this would be beneficial (similar to the atmospheric sciences topic).  I would like to be able to put this in my setup.py: 

`Topic :: Scientific/Engineering :: Hydrology`

Who to contact to add such a classifier?

**Comment by pradyunsg** [comment]
You can request a classifier over at Warehouse's issue tracker: https://github.com/pypa/warehouse/issues/new?template=new-trove-classifier.md.

**Comment by raoulcollenteur** [comment]
Thanks for your help! Closing the issue :)
