### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by ESalamanca** [pypa/packaging-problems#255]
Thank you for providing feedback on Python packaging!

1. OS: Mac OS High Sierra 10.13.6

2. Python version : Python 3.6.6 :: Anaconda, Inc.

3. pip 19.0.3 version 

4. Could you describe your issue in as much detail as possible?
When running the command : "python3 setup.py sdist bdist_wheel" in the ProgrammePy directory (containing the setup.py, LICENCE and README.md files + example_pkg directory) 
this is what I get: 

running sdist
running egg_info
creating example_pkg_ElisaSalamanca.egg-info
writing example_pkg_ElisaSalamanca.egg-info/PKG-INFO
writing dependency_links to example_pkg_ElisaSalamanca.egg-info/dependency_links.txt
writing top-level names to example_pkg_ElisaSalamanca.egg-info/top_level.txt
writing manifest file 'example_pkg_ElisaSalamanca.egg-info/SOURCES.txt'
error: package directory 'ProgrammePy' does not exist_

It creates a directory "example_pkg_ElisaSalamanca.egg-info" with several files inside  : 
dependecy_links.txt
not-zip-safe
PKG-INFO
SOURCES.txt
top_level.txt 

It does not create the two files you mention in the tutorial. Is this normal?

**Comment by merwok** [comment]
Did you notice the error message in the output:

```
error: package directory 'ProgrammePy' does not exist_
```

This means that you probably have `packages=["ProgrammePy"]` in your setup.py, but no such package in your directory (e.g. `ProgrammyPy/__init__.py`).

What is the layout of the code you’re trying to package?

**Comment by ESalamanca** [comment]
Thank you! 
I corrected the setup.py file and it works just fine.
