### ISSUE TITLE
Platform specific requirements are hard to get right

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#26]
There is confusion about how to do platform specific requirements. Wheel introduces it's own way as well. How can we make this cleaner?

**Comment by pradyunsg** [comment]
[PEP 508] handled this.

[PEP 508]: https://www.python.org/dev/peps/pep-0508/

**Comment by ncoghlan** [comment]
@pradyunsg Did you mean to reopen this? I think your comment above is right, as Donald originally filed this before environment markers had been standardised.
