### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by jcanose81** [pypa/packaging-problems#262]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

19.0.3

4. Could you describe your issue in as much detail as possible?

H:\packaging_tutorial\example_pkg>py setup.py dist bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    with open("README.md", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

**Comment by merwok** [comment]
Is there a file named README.md in the same directory as setup.py?

**Comment by jcanose81** [comment]
Yes.

**Comment by jcanose81** [comment]
![Capture](https://user-images.githubusercontent.com/50759336/58492591-35614280-813f-11e9-878b-7e30ed722b73.PNG)

**Comment by merwok** [comment]
If you look at the complete filenames, I think you’ll see that you have README.md.txt

**Comment by jcanose81** [comment]
That was it. Thank you.

**Comment by merwok** [comment]
Great!

Another thing: to make a package (a wheel that you can distribute) of a package (a module that you can import and that has submodules), you’ll need to create a directory `example_pkg` and move `__init__.py` there.  Or use a single module until you need a package: `example_module.py` with `setup(py_modules=["exmaple_module"])`.

**Comment by jcanose81** [comment]
I had to run "py -3 setup.py sdist bdist_wheel" to get the command to run.  
This is great. I've been using HTML5 and CSS for years but am now teaching myself any and all languages I can (Python, Solidity, etc) 

Thank you for the very fast reply and fix!
