### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by mateusnobre** [pypa/packaging-problems#275]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. Could you describe your issue in as much detail as possible?

**Comment by mateusnobre** [comment]
Error when i try to package my module. I've installed wheel previously, with the command in python3 -m pip install --user --upgrade setuptools wheel

**Comment by merwok** [comment]
Could you edit your original post to answer the questions?

In `4.`, please make sure to copy the exact command you are running (`python setup.py ...` or `pip something` or `python3 -m pip`)
