### ISSUE TITLE
python3 setup.py sdist bdist_wheelTrouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Easonqsp** [pypa/packaging-problems#281]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. Could you describe your issue in as much detail as possible?

**Comment by merwok** [comment]
Hello, you did not answer any of the questions so it will be hard for people to help you!
