### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by KathrynJones1** [pypa/packaging-problems#288]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

MacOS version 10.13.4

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

19.2.3

4. Could you describe your issue in as much detail as possible?

I have made sure that the wheel and setup tools are installed and up to date but then when I run `python3 setup.py sdist bdist_wheel` it brings up to error `error: invalid command 'bdist_wheel'` and I'm not sure how I can rid of this.

**Comment by ncoghlan** [comment]
@KathrynJones1 Hmm, that sounds like either the setup.py isn't finding `setuptools` properly, or `setuptools` isn't finding the `wheel` project.

What output do you get from `python3 -m pip list`?

**Comment by KathrynJones1** [comment]
@ncoghlan I tried something I found in stack exchange where I changed in the setup.py file : `from distutils.core import setup` to `from setuptools import setup` and then it seems to be working okay now?

**Comment by ncoghlan** [comment]
Indeed, I was initially going to ask about that specifically, as it's a common problem if folks are following older distutils-based tutorials.

I should have confirmed that the tutorial you were following was the packaging.python.org one, as that includes a sample setup.py that imports setuptools: 

https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py

**Comment by KathrynJones1** [comment]
Ah I see, thank you for your help!
