### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by ade711** [pypa/packaging-problems#292]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 7

2. What is your Python version?

Python 3.4.5
3. What version of pip do you have?
pip9.0.1
4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?
Following the tutorial successfully and the package is created but when I try to create a conda environment with the package. I get an error stating the readme does not exist. the open command in setup.py subsequently fails. when I inspect the tar.gz file, the readme is indeed missing. do you have any ideas why this might be happening

**Comment by merwok** [comment]
It seems that the tutorial is missing mention of `MANIFEST.in` file containing `include README.rst LICENSE`

**Comment by merwok** [comment]
@layday I would keep this one open, per my previous comment

**Comment by layday** [comment]
Readmes should not require a manifest entry.  We'd need more information to understand why the readme's not being packaged here, but seeing as it's a 1.5-year-old issue, I elected to close it.

**Comment by henryiii** [comment]
> README.rst (Python 3.7+ or setuptools 0.6.27+)

This was Python 3.4. Probably no/old setuptools. A link to https://packaging.python.org/guides/using-manifest-in/ would be useful though, probably.

**Comment by layday** [comment]
I've opened https://github.com/pypa/packaging.python.org/issues/867 to track this.

**Comment by layday** [comment]
See also https://github.com/pypa/packaging-problems/issues/229.

**Comment by layday** [comment]
Addressed in https://github.com/pypa/packaging.python.org/pull/868.
