### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by leticiacechinel** [pypa/packaging-problems#294]
hank you for providing feedback on Python packaging!
To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 18.04

2. What is your Python version?
3.7.4

3. What version of pip do you have?

19.2.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

When i type 
python3 setup.py sdist bdist_wheel

 I am having a problem that results in this message:

Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    packages = setuptools.find_packages(),
NameError: name 'setuptools' is not defined

i have setuptools installed and up-to-date, and i import it in my 'setup.py' file

**Comment by merwok** [comment]
> i have setuptools installed and up-to-date, and i import it in my 'setup.py' file

Can you show the setup.py file?

**Comment by leticiacechinel** [comment]
from setuptools import setup, find_packages

setup(
 	name='pacotebio',
 	version = '1.0.0',
 	author = 'Leticia, Savio, Jessica, Lucas',
 	description = 'Test',
 	url='#',
 	packages = setuptools.find_packages(),
 	license = 'N/D',
 	zip_safe = False,
 	install_requires = ['pandas', 'numpy', 'streamlit', 'reverse_geocode'], 
 	python_requires = '>=3.6'
)

**Comment by merwok** [comment]
You imported individual functions, not the setuptools module.  These forms can work:

```python
import setuptools

setuptools.setup(
    ...,
    packages=setuptools.find_packages(),
   ...,
)
```

or 

```python
from setuptools import setup, find_packages

setup(
    ...,
    packages=find_packages(),
   ...,
)
```

**Comment by leticiacechinel** [comment]
The problem was solved, thank you very much for your feedback.

**Comment by merwok** [comment]
Alright!  Please close the issue then :slightly_smiling_face:
