### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by anantvikas123** [pypa/packaging-problems#295]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

HTTPError: 400 Client Error: File already exists. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/

**Comment by merwok** [comment]
It seems like you are trying to reupload an existing file, which is not possible as documented on the linked page.  You’ll have to bump your version number.

For future tickets, please answer the 5 questions.
