### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by ogarland** [pypa/packaging-problems#296]
1. What is your operating system and version?

Windows 10

2. What is your Python version?

3.7.3

3. What version of pip do you have?

19.0.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

Section: Generating distribution archives
https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

Error I am getting is:
"error: can't copy '<foldername>': doesn't exist or not a regular file"

Maybe this is an easy thing to fix but I cannot seem to figure it out. Any feedback would be helpful!!

**Comment by merwok** [comment]
Hello!  To help you, people would need more details, such as your project layout (list of filenames that you are trying to package) and setup.py script.
