### ISSUE TITLE
PyPI package size limit increase for `sudachidict-{core,full}`

### ISSUE THREAD

**Issue by sorami** [pypa/packaging-problems#299]
Hello!

We are trying to add resources for the following two packages, and we would like to ask for the size limit increase (which is by default 60MB);

1. `sudachidict-core`: 75MB
2. `sudachidict-full`: 160MB

We would like the limit increase for both `pypi.org` and `test.pypi.org`;
- https://pypi.org/project/SudachiDict-core/
- https://pypi.org/project/SudachiDict-full/
- https://test.pypi.org/project/SudachiDict-core/
- https://test.pypi.org/project/SudachiDict-full/

Thank you very much for your help!

**Comment by sorami** [comment]
Hi, any chance this can get checked out? Thank you!

**Comment by polm** [comment]
@jamadden Hello, sorry to ping you but I noticed you addressed [a similar ticket](https://github.com/pypa/pypi-support/issues/104) recently. Is there anything else this ticket needs to be addressed? I'm not a maintainer of SudachiPy but as a user it'd be great to have dictionaries installable via Pypi.

**Comment by jamadden** [comment]
The PyPI moderators monitor https://github.com/pypa/pypi-support for issues like this. There's an issue template there that requests further information. (This tracker is for general packaging support, not PyPI-specific issues.)

**Comment by sorami** [comment]
Thank you for letting us know!

I have opened a limit request issue there; https://github.com/pypa/pypi-support/issues/131
