### ISSUE TITLE
People tend not to close file descriptors in their setup.py

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#30]
While a social problem, one person pointed out that people do not close their file descriptors in their setup.py files.

**Comment by pradyunsg** [comment]
Is this still relevant?

**Comment by ncoghlan** [comment]
While I'm sure this is still frequently the case, I don't think there's really anything meaningful we can do about it beyond advising build tool developers to run builds in a subprocess (so the descriptors at least get closed when the process terminates).
