### ISSUE TITLE
Impossible to enter password for Twine / 403 Client Error

### ISSUE THREAD

**Issue by gakonorde** [pypa/packaging-problems#300]
1. What is your operating system and version?

Win10 Pro 1803 Biuld 17134.1069 64 bit

2. What is your Python version?

Python 3.7.5 32 bit

3. What version of pip do you have?

pip 19.3.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

I successfully created tar. and whl. in the dist folder, registered on https://pypi.org/ with e-mail confirmation and started to upload. 

I checked both files with command line ('PASSED')

and did the following:

```D:\Corpus\Gersyll\packaging_tutorial>python -m twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: gakonorde
Enter your password:
Uploading gersyll-Alpha.release-py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████| 6.43k/6.43k [00:01<00:00, 5.12kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
```

The command line does not allow me to enter password after username. I only can press ENTER.

I tried 

```
Password for 'your-username' in 'https://upload.pypi.org/legacy/':
```

And again, I can press nothing except of ENTER.

Then I created .pypirc file with credentials for https://pypi.org/ and its test version and run ```python -m twine upload dist/*``` again

I was not asked for a password, but got the same error:

```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading gersyll-Alpha.release-py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████| 6.43k/6.43k [00:01<00:00, 5.46kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
```

I can enter my account on https://pypi.org/, so it obviously exists (and e-mail is verified).

Here is my setup.py:

```
import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="gersyll",
    version="Alpha release",
    author="gakonorde",
    author_email="gabrielko@yandex.ru",
    description="This module counts the number of words of different syllable length for all texts in a directory",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/gakonorde/gersyll",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3.7",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.7',
)
```

Please help.

**Comment by gakonorde** [comment]
Sloved with 

```
python -m twine upload -u USERNAME -p PASSWORD dist/*
```

**Comment by merwok** [comment]
> The command line does not allow me to enter password after username. I only can press ENTER.

Are you sure about this?  The code is probably using the getpass module, which will prevent echoing the characters typed or pasted for security, but the characters are read.

**Comment by cjcbusatto** [comment]
I did not have the same problem of @gakonorde, but I was also struggling to authenticate. All the times I tried (even using the token login), I got HTTP 403. Sending the username and password direct on the command worked for me.
