### ISSUE TITLE
Syntax Error on the first "p" in pip

### ISSUE THREAD

**Issue by OlofolusRexus** [pypa/packaging-problems#304]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.8.0

3. What version of pip do you have?

pip-9.0.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://pip.pypa.io/en/stable/installing/

5. Could you describe your issue in as much detail as possible?

Hi! My problem is that I'm quite young and want to learn how to program with PyGame, so I followed the tutorial on this website (I'm stuck on the 1:st video since I have this problem) https://pythonprogramming.net/pygame-python-3-part-1-intro/ And now for the past 20-30 minutes I've tried to figure out how to download pip and install PyGame. I managed to download pip after 15 minutes of confusion and then when I try to use any of the commands like curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py or python3 -m pip install -U pygame --user it gives me the syntax error on the first p in pip. I've tried this in both shell and in the source code and it gives me the same error all the time. I'm stumed after nearly an hour. If you could help me soon it would be appreciate it. ![nhgdf](https://user-images.githubusercontent.com/58604098/70341597-95a21100-1853-11ea-9e63-8b370a958231.png)

**Comment by merwok** [comment]
These commands are meant to be typed in a terminal (also known as console or command prompt), not in the Python interactive interpreter :slightly_smiling_face:
