### ISSUE TITLE
Archive pypa/pipenv 

### ISSUE THREAD

**Issue by Pomax** [pypa/packaging-problems#307]
As a project that is no longer maintained, please have the pypa/pipenv project owner(s) archive the repo on github (and pypi if possible) so that people can start planning their migrations to newer, maintained solutions, and new projects don't reach for an unmaintained solution anymore. Archiving will still leave the code fully accessible, and will not affect any existing direct dependencies based on github url.

If possible, also please respond on https://github.com/pypa/pipenv/issues/4058 so that the community doesn't have to keep guessing at whether anyone should still be using pipenv (especially as all signs point to that they shouldn't).

**Comment by benatkin** [comment]
Archiving isn't a very nice feature. There's a reason github took so long to implement it. I think it would be nice to move out of pypa so it's on equal footing with Poetry and other alternatives, though.

**Comment by Pomax** [comment]
Also fine; the main concern is to have a clear indication about whether it's still maintained or should be considered a legacy solution. I see Dan responded on the linked issue about its activity status, so If moving it out of the pypa org is an option, then that'd be an excellent thing to do at the same.

**Comment by pganssle** [comment]
A maintainer has already commented on that thread. We will not be archiving `pipenv`.
