### ISSUE TITLE
Trouble packaging

### ISSUE THREAD

**Issue by ghost** [pypa/packaging-problems#309]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Chrome OS

2. What is your Python version?
Python 3.8.0

3. What version of pip do you have?
pip 19.3.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
I followed this tutorial:
[Packaging Python Projects — Python Packaging User Guide](https://packaging.python.org/tutorials/packaging-projects/) 

5. Could you describe your issue in as much detail as possible?
I was working to upload my pachage to PyPA,
but when I ran `python3 setup.py sdist bdist_wheel` I get the error:
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'

The same thing happens when I run `python3 setup.py sdist`

It says my setuptools is installed:
Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages (42.0.2)

but then says it doesn't exist.

Thank you for your help.

**Comment by merwok** [comment]
> It says my setuptools is installed:
> Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages (42.0.2)

Could you say what `it` is?  The exact command you are running (maybe `pip3 install setuptools`)

Also can you copy the output of `which python3`?

**Comment by coderkearns** [comment]
I am using pip3

'which python3' returned:
/use/local/bin/python

Thanks again for your help!

**Comment by merwok** [comment]
I don’t see how `/usr/local/bin/python` can be invoked for `python3`.

Could you run these and copy the exact output:

```
type python3
which python3
python3 -m site
python3 -m pip install setuptools
```

**Comment by coderkearns** [comment]
Sorry, it was /usr/local/bin/python3.
I just typed it wrong.

I think I have found the problem though, just not the solution. I was
working on another package of mine and found I get the same error. It seems
that the problem is in 'pip'.
I recently upgraded to python 3.8, and I believe that is when the problems
first started. I am using a Chromebook, which runs Debian 9 in a container.
Thank you for all your help!

**Comment by coderkearns** [comment]
I am having this problem with everything I try to install using pip.

**Comment by merwok** [comment]
With multiple Python versions installed in different places, it is a very common issue that a pip command does not install in the right place. Please run the commands I gave you, otherwise it is impossible to help you at a distance.

**Comment by coderkearns** [comment]
Thank You,

`type python3`
python3 is hashed (/usr/local/bin/python3)

`which python3`
/usr/local/bin/python3

`python3 -m site`
sys.path = [
    '/home/carterkearns05',
    '/home/carterkearns05/serve',
    '/home/carterkearns05/pyqt',
    '/usr/local/lib/python3.8',
    '/usr/local/lib',
    '/usr/local/lib/python38.zip',
    '/usr/local/lib/python3.8/lib-dynload',
    '/usr/local/lib/python3.8/site-packages',
]
USER_BASE: '/home/carterkearns05/.local' (exists)
USER_SITE: '/home/carterkearns05/.local/lib/python3.8/site-packages'
(doesn't exist)
ENABLE_USER_SITE: True

`python3 -m pip install setuptools`
/usr/local/bin/python3: No module named pip

I also just realized I have an alias:
alias pip="pip3"
I don't know if that matters, but I hope it helps!

>

**Comment by merwok** [comment]
> `python3 -m pip install setuptools`
> /usr/local/bin/python3: No module named pip

This shows that your Python3 global environment is not the one that’s used when you run `pip install`!

Can you check: `which pip3`?

**Comment by coderkearns** [comment]
/usr/local/bin/pip3

**Comment by merwok** [comment]
Can you check the shebang of the pip script?  (the first line of `/usr/local/bin/pip3`, that defines which Python interpreter is used to run the script)

**Comment by coderkearns** [comment]
#!/usr/bin/python3

**Comment by merwok** [comment]
That’s your issue.  You have an installation in `/usr`, another one in `/usr/local`.  pip installs packages to `/usr/lib/python3.x/site-packages`, but your `python3` command (which is `/usr/local/bin/python3`) looks in `/usr/local/lib/python3.x/site-packages`.

Two possible ways to solve this:
- run with your system Python explicitly, for example `/usr/bin/python3 setup.py sdist`
- install pip for your local Python: `python3 -m ensurepip` then `python3 -m pip install setuptools, wheel` then `python3 setup.py sdist`

**Comment by coderkearns** [comment]
Would the second option mean all my packages would work if I reinstall the
ones that had been broken?

**Comment by coderkearns** [comment]
I get a error:
can't compress data; zlib not available

**Comment by coderkearns** [comment]
I get this during the ensurepip

**Comment by ncoghlan** [comment]
Where did your "/usr/local/bin/python3" installation come from? If it's a local build without the zlib headers installed, then you would get that error.

https://devguide.python.org/setup/#build-dependencies covers installing those if that is what has happened.
