### ISSUE TITLE
When I run the command "setup.py sdist bdist_wheel", I get the following error :error: "no commands supplied", *wheel is installed 

### ISSUE THREAD

**Issue by re1220** [pypa/packaging-problems#311]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

**Comment by re1220** [comment]
I used with python 3.8

**Comment by di** [comment]
Are you running the command `setup.py sdist bdist_wheel` or `python setup.py sdist bdist_wheel`? It should be the latter.

**Comment by jaraco** [comment]
Thanks di for answering.
