### ISSUE TITLE
Trouble following packaging libraries tutorial: upload

### ISSUE THREAD

**Issue by ottok** [pypa/packaging-problems#313]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 18.04.

2. What is your Python version?

Python 3.6.9

3. What version of pip do you have?

pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

Upload step

5. Could you describe your issue in as much detail as possible?

When I try to upload I get an 403 error. However, there is not indication what is wrong, my username, my key, my token, my package name or what.

```
$ python3 -m twine upload --verbose rdiff-backup-1.4.0b1.dev34+g1cce874.d20200119.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading rdiff-backup-1.4.0b1.dev34+g1cce874.d20200119.tar.gz
100%|| 301k/301k [00:01<00:00, 249kB/s]
Content received from server:
<html>
 <head>
  <title>403 Invalid or non-existent authentication information.</title>
 </head>
 <body>
  <h1>403 Invalid or non-existent authentication information.</h1>
  Access was denied to this resource.<br/><br/>
Invalid or non-existent authentication information.
 </body>
</html>
```

From the page https://pypi.org/manage/account/ I can see that my token states "newer used". But in this context I don't know why. The scope of the token is rhe rdiff-backup project (as I want to upload there).

It error message is the same no matter if I enter the credentials interactively or via `.pypirc`.

**Comment by ottok** [comment]
BTW, you might want to update in the tutorial the Twine installation command so it includes a dependency that otherwise yields errors: `python3 -m pip install --user --upgrade twine keyrings.alt`

**Comment by merwok** [comment]
I don’t know that the legacy interface supports API tokens.

The help at https://pypi.org/help/#apitoken doesn’t say which upload URL to use.
The doc at https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives uses legacy URL for TestPyPI, but the notes later in https://packaging.python.org/tutorials/packaging-projects/#next-steps say that default repo URL for twine is `https://pypi.org/`, but I don’t know if that means «exactly this URL» or is a shortcut to mean «real PyPI and not Test»

**Comment by merwok** [comment]
Twine docs is equally silent about the exact PyPI upload URL.
The section about keyring hints that the legacy URL is the one used: https://pypi.org/project/twine/#keyring-support

So I agree that 1) various docs should spell out the exact URL for clarity  2) error message could be more helpful

**Comment by bhrutledge** [comment]
Thanks for reporting this. It prompted me to dive into the existing docs, and update an open issue to improve them: https://github.com/pypa/packaging.python.org/issues/297#issuecomment-576409783.

I'm not sure I can resolve your issue with tokens, but I'm hoping to clear up some confusion about URLs.

> The doc...uses legacy URL for TestPyPI, but the notes later...say that default repo URL for twine is `https://pypi.org/`, but I don’t know if that means «exactly this URL» or is a shortcut to mean «real PyPI and not Test»

The correct URLs for the repositories are `https://upload.pypi.org/legacy/` and `https://test.pypi.org/legacy/`. And yes, the `legacy` in there is confusing. However, you shouldn't need to specify them. `twine upload` will default to PyPI, and you can use `twine upload --repository testpypi` to use TestPyPI.

[To use an API token](https://pypi.org/help/#apitoken), you need to set the username to `__token__`, and the password to the token. This can be done on the [twine command line](https://twine.readthedocs.io/en/latest/#twine-upload), via [environment variables](https://twine.readthedocs.io/en/latest/#environment-variables), or in your [`~/.pypirc`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#create-an-account) (noting that again, you don't need to specify the repository URL).

If you prefer not to store your token in plain text, you can use [keyring](https://twine.readthedocs.io/en/latest/#keyring-support). I *think* that would look like:

```
$ keyring set https://upload.pypi.org/legacy/ __token__
```

Followed by entering the token as the password.

**Comment by bhrutledge** [comment]
> BTW, you might want to update in the tutorial the Twine installation command so it includes a dependency that otherwise yields errors: `python3 -m pip install --user --upgrade twine keyrings.alt`

@ottok This sounds like it might relate to an open issue with twine. Can you add a comment with as much detail as you can provide to https://github.com/pypa/twine/issues/554?

**Comment by ottok** [comment]
I still don't understand how to upload. I always get this:
```
$ python3 -m twine upload --verbose dist/rdiff-backup-1.4.0b1.dev34+g1cce874.d20200119.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading rdiff-backup-1.4.0b1.dev34+g1cce874.d20200119.tar.gz
100%| 301k/301k [00:01<00:00, 212kB/s]
Content received from server:
<html>
 <head>
  <title>403 Invalid or non-existent authentication information.</title>
 </head>
 <body>
  <h1>403 Invalid or non-existent authentication information.</h1>
  Access was denied to this resource.<br/><br/>
Invalid or non-existent authentication information.


 </body>
</html>
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
```

I have tried both:
```
$ cat $HOME/.pypirc
[pypi]
  username = otto
  password = pypi-AgEIc[redacted]

$ cat $HOME/.pypirc
[pypi]
  username = rdiff-backup-new-version
  password = pypi-AgEIc[redacted]
```

Why can't the API tell me if the username or the password is wrong? Now the error message is almost useless.

My pypi account 'otto' has only this one token:
![image](https://user-images.githubusercontent.com/668724/72756309-75e16500-3bd5-11ea-8124-6d459bee3008.png)

**Comment by merwok** [comment]
Have you tried with `username = __token__` (litteral string underscore underscore t o k e n underscore underscore)?

**Comment by ottok** [comment]
Ok, this works:
```
$ cat $HOME/.pypirc
[pypi]
  username = __token__
  password = pypi-[redacted]
```

This worked, thanks!

```
$ python3 -m twine upload --verbose dist/rdiff-backup-1.4.0b1.dev34+g1cce874.d20200119.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading rdiff-backup-1.4.0b1.dev34+g1cce874.d20200119.tar.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 301k/301k [00:01<00:00, 253kB/s]
Content received from server:
<html>
 <head>
  <title>400 '1.4.0b1.dev34+g1cce874.d20200119' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata</title>
 </head>
 <body>
  <h1>400 '1.4.0b1.dev34+g1cce874.d20200119' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
&#x27;1.4.0b1.dev34+g1cce874.d20200119&#x27; is an invalid value for Version. Error: Can&#x27;t use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata


 </body>
</html>
HTTPError: 400 Client Error: '1.4.0b1.dev34+g1cce874.d20200119' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata for url: https://upload.pypi.org/legacy/
```
This is now another problem, and I'll look into it later. The upload itself at least now works.

It is a bit confusing though to use a variable name, as to a Python programmer that smells like something that should be replace with a value. Also, why on earth does it ask the user to input a string that if fixed for everybody? It should ask just for the password, not username at all.

**Comment by merwok** [comment]
The constraints for .pypirc here are working with existing systems, like an older distutils version bundled with a system install of Python.  The file format requires username and password, and implementations of package index (devpi, pypimirror, other) probably require username and password in their API.  So to introduct a new thing and avoid breaking existing systems, the devs decided to repurpose the existing fields with a fixed value as username and a token as password.  This is a solution I’ve also seen with HTTP Basic or Digest auth for example.

**Comment by ncoghlan** [comment]
It would make sense for twine to report a more specific error on a 403 error if the password looks like an API token, but the username isn't "__token__".

As far as the spelling goes, the special "__token__" username tells the server "My username is encoded into the API token provided in the password field". Passwords can be arbitrary strings, so the server can't infer the use of the token API just from the password prefix.

**Comment by ottok** [comment]
Considering that if no URL is given to Twine if defaults to uploading to PyPi, one could perhaps expect that Twine also had embedded some kind of default username/password handling that is "compatible" with PyPi conventions..

Anyway, I have now successfully uploaded https://pypi.org/project/rdiff-backup/1.4.0b2/
Thanks for your help!

**Comment by bhrutledge** [comment]
@ottok Thanks for sticking with it, and for the usability suggestion for Twine. I've created https://github.com/pypa/twine/issues/561 to take it under consideration.

I'm going to close this issue, but feel free to comment or reopen if appropriate.
