### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by kothasatya** [pypa/packaging-problems#315]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Win10

2. What is your Python version?
3.5

3. What version of pip do you have?
20.0

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?
.whl package in dist folder is only updating if i click rebuild, nothing is updating if i just do build

**Comment by merwok** [comment]
Can you give more details?  We don’t know what you mean with `click rebuild` or `do build`.  The official tutorials all document how to use setuptools, twine, pip on the command line, so you must be using something else.

**Comment by kothasatya** [comment]
I tried to include the python project in my VS2017 and installed python3.5, pip20.0, wheel, and pyspark. then I configured pyprog file with before build and after build
<Target Name="CoreCompile" />
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
    <Exec Command="python setup.py bdist_wheel" WorkingDirectory="$(ProjectDir)\Libraries" />
  </Target>
after all these changes, i tried to build the solution but whl file in libraries is not updated. Updated when i click rebuild the solution

**Comment by kothasatya** [comment]
<Target Name="CoreCompile" />
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
    <Exec Command="python setup.py bdist_wheel" WorkingDirectory="$(ProjectDir)\Libraries" />
  </Target>

**Comment by kothasatya** [comment]
I have given <target name="beforebuild><target name="afterbuild"><exec command=python setup.pu bdist_wheel workingdirectory=""/> in pyproj

**Comment by merwok** [comment]
Sorry, I don’t know VS2017 so I won’t be able to help.
You will get more people to read your message if you post on Discourse: https://discuss.python.org/c/users/7
Best wishes!

**Comment by kothasatya** [comment]
Thanks for that
