### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by vanrein** [pypa/packaging-problems#319]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Mac OS X 10.15.3

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

pip 19.0.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#uploading-your-project-to-pypi

5. Could you describe your issue in as much detail as possible?

I created software under a namespace package `arpa2` for our cohesive project that will have more packages to share.  The intention is to allow `from arpa2 import wsgi.byoid` in user code.  I think it makes sense then to name the package `arpa2.wsgi` so as to have the same naming structure on PyPi as on the system.  Maybe the dot is interfering -- but it does seem the logical thing to do.

Although the first upload went through fine, newer ones keep reporting *400 Only one sdist may be uploaded per release.* and, in more detail, *The server could not comply with the request since it is either malformed or otherwise incorrect.*

Of course I did update versions, both from 0.4.0 to 0.4.1 and to 0.5.  That changed nothing.

Could the PyPi environment be misreading the dot and seeing a funny part of the upload as a version?  Interestingly, the [packages do seem to be uploaded](https://pypi.org/project/arpa2.wsgi/) in spite of the error report?!?

**Comment by vanrein** [comment]
Could this error about the `README.MD` be a difference between `sdist`, `bdist_egg` and `bdist_wheel`?

**Comment by di** [comment]
Can you tell us exactly the files in the `dist` directory that you are uploading?

**Comment by merwok** [comment]
To add details to Dustin’s request: please copy the list of files present in `dist`, and the exact upload command you ran.

**Comment by vanrein** [comment]
Hmm, that state is gone, and I've continued hammering at it.  I don't know why, but it may have "resolved itself".  I'd love to know why, but my best bet lies in this direction:

I originally could not build a wheel (no idea why) and now I can (no idea why).  That seems to be the necessary change.  Instead of `python3 setup.py build sdist bdist` which created a `.tar.gz` and ` .egg` I can now use `python3 setup.py build sdist bdist_wheel` and that does work.

Propose to close the issue, and I could reopen with this information if needed.  Thanks for reaching out!

**Comment by merwok** [comment]
Indeed, `bdist` is not the documented command, you need to write `bdist_wheel`.
I think this can be closed (the docs don’t mention `bdist`).

**Comment by merwok** [comment]
Also for future bug reports, note that you didn’t include in your original post the command you ran or the output / error message, which makes it hard to diagnose the problem! :slightly_smiling_face:
