### ISSUE TITLE
Public database of general project metadata

### ISSUE THREAD

**Issue by Melykuti** [pypa/packaging-problems#323]
Similarly to how [the Linehaul project streams PyPI download data](https://packaging.python.org/guides/analyzing-pypi-package-downloads/#public-dataset) into a [Google BigQuery public dataset](https://cloud.google.com/bigquery/public-data) (into tables called \`the-psf:pypi.downloadsYYYYMMDD\`), I wish to be able to query a public dataset that contains the project metadata from PyPI, for example [how it is presented by Warehouse JSON API calls](https://warehouse.readthedocs.io/api-reference/json/).

I would like to analyse project licenses. In fact, [I would not be the only one interested in this data to do a study.](https://snyk.io/blog/over-10-of-python-packages-on-pypi-are-distributed-without-any-license/) This data is technically simpler to collect than the downloads data and would be similarly informative about the totality of Python packages. I'd be thankful if such a database were created.

**Comment by KOLANICH** [comment]
>I would like to analyse project licenses.

I don't think that copyright trolls should be gifted with a tool for tyeir needs.

>Implementing new specifications like PEP 517

They have forgotten to notice `setup.cfg`.

Also IMHO using wheels should be encouraged. How about banning all uploads to pypy that are not wheels or their signatures?

**Comment by ncoghlan** [comment]
Tidelift provide such a database at libraries.io: https://libraries.io/languages/Python

The relevant libraries.io page is linked from the "Statistics" section on each PyPI project page.

There aren't any plans to build a Python specific version of this dataset (since a language independent one is generally more useful).

**Comment by ChillarAnand** [comment]
Does tidelift dump has all the metadata provided by PyPi or does it provide only a subset of the metadata?
