### ISSUE TITLE
test package upload issue

### ISSUE THREAD

**Issue by ewuramaminka** [pypa/packaging-problems#326]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

MAC OS HIGH SIERRA 10.13.6

2. What is your Python version?

3.7.4

3. What version of pip do you have?

pip 19.2.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/ 

5. Could you describe your issue in as much detail as possible?

$ python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: __token__
Enter your password: 
Uploading pkg_FL-0.0.1-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.34k/5.34k [00:00<00:00, 10.0kB/s]
Content received from server:

400 Invalid value for classifiers. Error: 'License :: OSI Approved :: Academic Free License 1.1 (AFL-1.1)Operating System :: OS Independent' is not a valid choice for this field

400 Invalid value for classifiers. Error: 'License :: OSI Approved :: Academic Free License 1.1 (AFL-1.1)Operating System :: OS Independent' is not a valid choice for this field
  The server could not comply with the request since it is either malformed or otherwise incorrect.

Invalid value for classifiers. Error: &#x27;License :: OSI Approved :: Academic Free License 1.1 (AFL-1.1)Operating System :: OS Independent&#x27; is not a valid choice for this field

HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'License :: OSI Approved :: Academic Free License 1.1 (AFL-1.1)Operating System :: OS Independent' is not a valid choice for this field for url: https://test.pypi.org/legacy/

**Comment by merwok** [comment]
Hello!  You did not answer any of the questions :slightly_smiling_face:

**Comment by ewuramaminka** [comment]
> Hello! You did not answer any of the questions 🙂

i did but was formatted and appeared invisible

**Comment by uranusjr** [comment]
> 400 Invalid value for classifiers. Error: 'License :: OSI Approved :: Academic Free License 1.1 (AFL-1.1)Operating System :: OS Independent' is not a valid choice for this field

This suggests to me that there’s an [implicit line joining](https://docs.python.org/3/reference/lexical_analysis.html#implicit-line-joining) going on. Check your `setup.py` and see whether there’s a comma missing;

```python
classifiers=[
    'License :: OSI Approved :: Academic Free License 1.1 (AFL-1.1)',  # <- Here!
    'Operating System :: OS Independent',
]
```

**Comment by ewuramaminka** [comment]
Thanks! uploaded

Uploading pkg_FL-0.0.1-py3-none-any.whl
  0%|                                                                                                                                                                | 0.00/5.39k [00:00<?, ?B/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.39k/5.39k [00:01<00:00, 3.74kB/s]
Uploading pkg-FL-0.0.1.tar.gz
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.33k/4.33k [00:00<00:00, 4.56kB/s]

View at:

**Comment by merwok** [comment]
Alright!  Please close the ticket :slightly_smiling_face:
