### ISSUE TITLE
How to Help?

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#33]
I've had a few responses about people asking how they can help. However I don't have a good place to point them to in order to get them bootstrapped into helping. Perhaps this is another topic for the packaging guide? A How to get involved type of thing?

**Comment by brainwane** [comment]
The ["how to help" section on pypa.io](https://www.pypa.io/en/latest/help/) could use some fleshing out). But when people want to help, we can point them to [the Warehouse "getting started" docs](https://warehouse.readthedocs.io/development/getting-started/) and [the Python Packaging User Guide "Contribute to this guide" doc](https://packaging.python.org/contribute/). I am calling that good enough for now.
