### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by mgutierrez32** [pypa/packaging-problems#331]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

macOS 10.15.3

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

pip 20.0.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/ and https://devarea.com/deploying-a-new-python-package-to-pypi/#.Xl8Cti2ZN27

5. Could you describe your issue in as much detail as possible?

  File "setup.py", line 13
    
     ^
SyntaxError: unexpected EOF while parsing 

setup.py:
from setuptools import setup, find_packages
setup(
    name = 'pygrins',
    packages = find_packages(include=['pygrins', 'pygrins.*'], # this must be the same as the name above               
    version = '0.0.1.dev1',
    description = 'Spectral Line Parameter Calculator with emphasis on IGRINS data',
    author = 'Miguel Gutierrez',
    author_email = 'ggmiguel98@gmail.com',
    license='MIT',
    url = 'https://github.com/mgutierrez32/pygrins',
    python_requires='>=3',                                                                                            
)

**Comment by merwok** [comment]
The call to find_packages is missing a closing parenthese
