### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by JimmyLamothe** [pypa/packaging-problems#337]
1. What is your operating system and version?

Mac OS 10.14.6

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

19.0.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

"Installing your newly uploaded package"

5. Could you describe your issue in as much detail as possible?

I followed the tutorial twice and uploaded two different versions, one typing things in by hand and the other one by copy-pasting everything. Works great, except for the final test, I can't import the module:

"ModuleNotFoundError: No module named 'example_pkg'"

When I look in my virtual environment site-packages, the only relevant directory is named:

example_pkg_JMLAPRISE-0.0.1.dist-info

As all other packages like pip and setuptools have a "dist-info" directory and a similarly named directory without the "dist-info", I'm assuming the install (or upload) didn't function correctly, which explains the import error.

Here's the link to the project. I had the same problem with version 0.0.1 so I tried deleting the project and creating an identical version called 0.0.2, which is the one you see there.

https://test.pypi.org/project/example-pkg-JMLAPRISE/

Any ideas why this would happen? Thanks!

**Comment by merwok** [comment]
Did you rename the Python package?  That is, do you have `example_pkg/__init__.py` or `example_pkg_JMLAPRISE/__init__.py`?

**Comment by JimmyLamothe** [comment]
I just found out what it was. I actually created `__init__.py` using the bash command `touch __init__.py`. I assumed from memory that this would create a file, but in fact it created a directory. So obviously `setuptools.find_package()` wasn't finding it.

I just created a proper empty `__init__.py` file and it works.

**Comment by merwok** [comment]
touch creates a file, you need mkdir for a directory.  But glad you solved your issue!
