### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by InsaneDhina** [pypa/packaging-problems#340]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.7.2.

3. What version of pip do you have?

pip 20.0.2. 

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/ 

5. Could you describe your issue in as much detail as possible?

 
so after going through no. of blogs and stackoverflow answers I am still unable to upload the project Pypi , the command throws the same error "403 The user 'dhina0078' isn't allowed to upload to project 'example-pkg-YOUR-USERNAME-HERE'. See https://pypi.org/help/#project-name for more information.
  Access was denied to this resource." --> 

and I am able to login with the credentials no. of times in https://test.pypi.org/ and it works perfectly in browser and I am not sure how to overcome this issue.

Since I am new to python , I may miss something silly or whatnot

steps followed were as provided in the official link https://packaging.python.org/tutorials/packaging-projects/  until the execution of command -python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

I have tried including the credentials in .pypirc file also and that doesn't seems to help. PFA
[twine_error.docx](https://github.com/pypa/packaging-problems/files/4462405/twine_error.docx)

NOTE: experiencing the same with API token username = __token__ and password = "generated_API_Token"

**Comment by merwok** [comment]
You’re not meant to use `example-pkg-YOUR-USERNAME-HERE` litterally as your project name, but rather `example-pkg-dhina0078`.  Can you try that?

**Comment by InsaneDhina** [comment]
Thankyou! that worked like a charm.
