### ISSUE TITLE
when i run 'python3 setup.py sdist bdist_wheel' nothing happens

### ISSUE THREAD

**Issue by PythonMods** [pypa/packaging-problems#344]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Windows 10 Pro

2. What is your Python version?
Python 3.7.3

3. What version of pip do you have?
20.0.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?
when i run 'python3 setup.py sdist bdist_wheel' nothing happens no text is displayed on-screen
and no files or folders are created

**Comment by di** [comment]
Can you share the contents of your `setup.py` file with us?

**Comment by PythonMods** [comment]
Here they are


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by PythonMods** [comment]
.py file type not supported, putting it in ZIP

[setup.zip](https://github.com/pypa/packaging-problems/files/4514606/setup.zip)

**Comment by pfmoore** [comment]
On Windows, there is no `python3` command as part of the standard python.org distribution. Can you confirm where you got your copy of Python from, as with a standard install I'd expect at least an error saying `python3` was an unrecognised command? Also, can you locate the source of that `python3` command and check if it's something odd like a batch file?

On Windows, the command should be `py setup.py sdist bdist_wheel'.

**Comment by PythonMods** [comment]
I use Windows and Linux and I did not know

**Comment by zakaria-78** [comment]
I experience the same problem and then when I want to upload I get an **_error_**

**Comment by merwok** [comment]
Can you search this bug tracker to see if there’s a ticket with your error message?
If not, please open one.  Thanks!

**Comment by Joey919** [comment]
pfmoore's answer is right.
In windows, you can try `**py setup.py sdist bdist_wheel**' instead of '**python setup.py sdist bdist_wheel**'.
use **py**     not **python**
