### ISSUE TITLE
Science Packages Often Don't Install With "Standard Tooling"

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#35]
A lot of the science packages do not install correctly with pip or easy_install, leading to fragmentation in the community.

**Comment by andreabedini** [comment]
This should just be fixed at some point. I refuse to let the community refuse to solve this :)

**Comment by pradyunsg** [comment]
pip install numpy works.
pip install scipy works.
pip install scikit-learn works.

Is this still relevant?

**Comment by ncoghlan** [comment]
Aye, the numpy folks figured out a way to manage their vectorized instruction set challenges, and manylinux made it possible to publish wheels for Linux, so a lot of packages "just work" now.
