### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by joaofaria97** [pypa/packaging-problems#351]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.8.2

3. What version of pip do you have?

pip 20.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/
from the "Generating distribution archives" downwards. The previous steps were accomplished following Chapter 2 of "Head First Python" by Paul Barry.

5. Could you describe your issue in as much detail as possible?
"python.exe" is in this directory -> C:\Users\joao-\AppData\Local\Programs\Python\Python38-32
"setup.py" is in this directory -> C:\Users\joao-\AppData\Local\Programs\Python\Python38-32\nester

I tried the following and obtained these messages:

C:\Users\joao-\AppData\Local\Programs\Python\Python38-32\nester>python.exe setup.py sdist bdist_wheel
'python.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\joao-\AppData\Local\Programs\Python\Python38-32\nester>python3 setup.py sdist bdist_wheel
'python3' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\joao-\AppData\Local\Programs\Python\Python38-32>python.exe setup.py sdist bdist_wheel
python.exe: can't open file 'setup.py': [Errno 2] No such file or directory

C:\Users\joao-\AppData\Local\Programs\Python\Python38-32\nester>setup.py sdist bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

**Comment by merwok** [comment]
You probably need to run something like `python3 -m pip install wheel`

**Comment by joaofaria97** [comment]
Thanks for the feedback. I'm trying to follow the example listed here https://packaging.python.org/tutorials/packaging-projects/ because I guess the way the book describes is kind of outdated. Ran into some trouble as well though, if you'd like to help it would be much appreciated. I described it in this thread https://github.com/pypa/packaging-problems/issues/352

**Comment by layday** [comment]
I'll close this now but feel free to comment below if you're still having trouble with this.
