### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by joaofaria97** [pypa/packaging-problems#352]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.8.2

3. What version of pip do you have?

pip version 20.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

"Generating distribution archives" section

5. Could you describe your issue in as much detail as possible?

Followed the whole tutorial until now. Got stuck with the "python3 setup.py sdist bdist_wheel" command where I get this error: 

File "C:\Users\joao-\AppData\Local\Programs\Python\Python38-32\packaging_tutorial\example_pkg\setup.py", line 3, in <module>
    with open("README.md", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

**Comment by merwok** [comment]
Is there a file named `README.md` in the same directory as setup.py?

(could help to have a screenshot or copy-paste of your files!)

**Comment by layday** [comment]
I'll close this now but feel free to comment below if you're still having trouble with this.
