### ISSUE TITLE
package folder name contains version number

### ISSUE THREAD

**Issue by mgenet** [pypa/packaging-problems#358]
Hi,

(Hoping it is the right place to ask…)

I packaged a bunch of python tools at https://pypi.org/project/myPythonLibrary. (Should be able to put directly at https://gitlab.inria.fr/mgenet/myPythonLibrary at some point, but it does not seem to work right now…)

Anyway, when I install it (within a binder instance, see https://mybinder.org/v2/git/https%3A%2F%2Fgitlab.inria.fr%2Fmgenet%2Fmec552/master), the package goes into a folder `site-packages/myPythonLibrary-2020.5.22.post0.dist-info` instead of `site-packages/myPythonLibrary`, so it cannot be imported within python. If I make a symlink `site-packages/myPythonLibrary-2020.5.22.post0.dist-info - > site-packages/myPythonLibrary` then I can import in within python.

Is that expected? Is there a way to install the package directly into `site-packages/myPythonLibrary`, or to automatically create a symlink? Any help would be appreciated. Thanks!

Martin

**Comment by uranusjr** [comment]
The `.dist-info` is a separate directory that holds project metadata for pip (and other tools) to recognise later. It is *not* the package for import.

Looking at your `setup.py`, it seems like you’re using `find_packages`, but there is no directories to be found in the project. If you want to have a `site-packages/myPythonLibrary` that holds your .py files, you need to nest the `myPythonLibrary` directory like this:

```
myPythonLibrary/   # This is to project root.
    myPythonLibrary/  # This is the directory to be installed into site-packages.
        __init__.py
        mat_vet_tools.py
        ... etc
    setup.py  # Files at this level will not be installed into site-packages.
```

**Comment by mgenet** [comment]
OMG thanks so much!

**Comment by uranusjr** [comment]
Thanks for asking! Feel free to close the ticket if the above resolves your problem 👍
