### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by AdrianaAriza** [pypa/packaging-problems#364]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

<3.6 >

3. What version of pip do you have?

<9.0.1>

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

**Comment by merwok** [comment]
Can you answer question 4?  What page or doc told you to run `python setup.py bdist_wheel` ?

**Comment by layday** [comment]
You must install wheel to be able to run `python setup.py bdist_wheel`.  Please comment below if this is still an issue for you.
