### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by XeoPlay** [pypa/packaging-problems#365]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Windows 10

2. What is your Python version?
3.7.1

3. What version of pip do you have?
20.0.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
https://www.youtube.com/watch?v=zhpI6Yhz9_4&t=34s

5. Could you describe your issue in as much detail as possible?
`python3 setup.py sdist` does nothing

**Comment by XeoPlay** [comment]
import setuptools

with open("README.txt", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="xeo_simple_calc",
    version="0.0.1",
    author="Grigoriy Agasiyants",
    author_email="xeoplay123456@gmail.com",
    description="A small basic calculator",
    long_description=long_description,
    url="",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)

**Comment by XeoPlay** [comment]
with the proper tabulation ofc

**Comment by merwok** [comment]
Do you have Python packages next to `setup.py`?  (meaning one or more directories containing `__init__.py`)

**Comment by XeoPlay** [comment]
In the folder with the library i have LICENSE.txt, MANIFEST.in, README.txt, CHANGELOG.txt, and one more directory with the ```__init__.py``` file.

**Comment by merwok** [comment]
If you do this:
```sh
python -m pip install wheel
python setup.py bdist_wheel
```
does anything happen?  (some output and a file created in `dist` directory)

**Comment by XeoPlay** [comment]
yea. there's some output and there's a file called ```xeo_simple_calc-0.0.1-py3-none-any.whl``` in the ```dist``` directory

**Comment by merwok** [comment]
But `python setup.py sdist` doesn’t create a zip file in the `dist` directory?  That’s strange.

If you know how to set an environment variable in your terminal, please set `DISTUTILS_DEBUG` to `1` and you will get more verbose output when running `setup.py` commands.

**Comment by XeoPlay** [comment]
I have no idea how or what an environment variable is. But i tried to publish my lib... AND EVERYTHING WORKED!!! I'm so happy. I'm currently working on version 0.0.3
Thanks for all your help

**Comment by merwok** [comment]
I see you uploaded the wheel, but it is strongly recommended to upload an sdist too.
