### ISSUE TITLE
Trouble installing pyinvariant

### ISSUE THREAD

**Issue by BubbleO2** [pypa/packaging-problems#366]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 20.04

2. What is your Python version?

Python 3.8.2

3. What version of pip do you have?

Pip 20.1.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://pypi.org/project/pyinvariant/

5. Could you describe your issue in as much detail as possible?

When running the command "pip3 install --user pyinvariant", i get the error :
ERROR: Could not find a version that satisfies the requirement pyinvariant (from versions: none)
ERROR: No matching distribution found for pyinvariant

**Comment by pfmoore** [comment]
If you look at https://pypi.org/project/pyinvariant/#files, the project only provides binaries, and doesn't include a binary for Python 3.8. This is something you'll need to raise with the pyinvariant project.
