### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by epimedplotly** [pypa/packaging-problems#369]
**1. What is your operating system and version?**

Windows 10 Pro 

**2. What is your Python version?**

Python 3.5.2

**3. What version of pip do you have?**

pip 20.0.2 from C:\AnacondaML\lib\site-packages\pip (python 3.5)

**4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:**

I'm follwing this links: 
https://code.tutsplus.com/pt/tutorials/how-to-write-package-and-distribute-a-library-in-python--cms-28693
https://packaging.python.org/tutorials/packaging-projects/
https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels

**5. Could you describe your issue in as much detail as possible?**

I'm trying to built a package wheel but I get a invalid sintax error: 

_python setup.py sdist
               ^
SyntaxError: invalid syntax_

There is my setup.py file:

from setuptools import setup

_setup(
    name='emspy',
    author='Lunna Borges',
    author_email='lunna.borges@...',
    packages=['emspy'],
    version='0.0.1',
    zip_safe=False,
    description = 'Epimed Solutions basic collection of python functions',
    include_package_data=True,
    install_requires=[
        "revoscalepy",
        "json",
        "babel",
        "numpy",
        "pandas",
        "abc"        
    ],
)_

**Comment by merwok** [comment]
Commands like `python setup.py sdist` are meant to be run in a terminal (also called shell, console, command line, command prompt), they are not valid Python code.

**Comment by epimedplotly** [comment]
Alright, it makes sense. 

Thanks!

**Comment by merwok** [comment]
I see that both official pages you linked are not very clear on this.
I have openeed https://github.com/pypa/packaging.python.org/issues/745 to improve this.  Thanks for your report!
