### ISSUE TITLE
Package size for h2o_pysparkling-3.0

### ISSUE THREAD

**Issue by jakubhava** [pypa/packaging-problems#370]
Hello folks and @dstufft ,
 we have released PySparkling for Spark 3.0, the same library we have for Spark 2.1 up to Spark 2.4, but we are hitting the size issue. Could I please ask to increase the size limit for the package to the same one, as for example, https://pypi.org/project/h2o-pysparkling-2.4/

Thank you!

Kuba

**Comment by layday** [comment]
Hi Kuba,

I assume this has been sorted but if it hasn't please open an issue at https://github.com/pypa/pypi-support.
