### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by kethan1** [pypa/packaging-problems#372]
OS: Windows 10

Python Version: Python 3.8.3

Pip version: pip 20.1.1

Hi, I have created a module HardwareInfo, link: https://pypi.org/project/HardwareProvider/
I can download it successfully, but when I do `import HardwareInfo`, I get an error saying `ModuleNotFoundError: No module named 'HardwareInfo'`

Github Page: https://github.com/kethan1/HardwareProvider

**Comment by merwok** [comment]
> I can download it successfully, but when I do import HardwareInfo,

The package name (what you write in `pip install something` is not directly related to the importable names (`import module`, `import package.submodule`).  Your repository has some issues: there are files that should not be there (temporary build files: `dist/`, `build/`, `*.egg-info`, these are generally in .gitignore in Python projects), but most importantly from Python‘s viewpoint there are no importable modules or packages in your repo.

A module name must be a valid identifier.  Just like it’s not possible to write `Person Age = 42` (correct: `person_age = 42`), a module name must be made of letters, undercores and numbers (but not start with a number).  Compare the two errors when I type this in the Python console:

```
>>> import Hardware Info
  File "<stdin>", line 1
    import Hardware Info
                    ^
SyntaxError: invalid syntax
>>> import hardware_info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'hardware_info'
>>> 
```

So if you rename your directory from `System Info` to `hardware_info` and the file in there from `system-info-file.py` to `system_info`, then the `find_packages` function will work and you will be able to do `pip install HardwareInfo` and then `import hardware_info` / `from hardware_info import system_info`.

**Comment by kethan1** [comment]
Hi, I can now import the module, but when I try using the methods, it gives me an error saying they do not exist. Where should I put my methods. I put in the same folder as the __init__.py. I have updated the github (had to change the links).

**Comment by merwok** [comment]
Your classes are defined in a sub-module, so you need to import it in one of these ways:

```python

import hardware_info.system_info

cpu1 = hardware_info.system_info.cpu()

from hardware_info import system_info

cpu2 = system_info.cpu()

from hardware_info.system_info import cpu

cpu3 = cpu()
```

(btw I would recommand following a style guide to name classes → `Cpu, Disk, Ram`)

You could also move code so that everything is in `hardware_info/__init__.py`, or even have a simple module `hardware_info.py`.  But that’s not a packaging problem, so now that this issue is fixed you can close it!

**Comment by kethan1** [comment]
Thanks for all the help.
