### ISSUE TITLE
Trouble following packaging libraries tutorial - no dist generated

### ISSUE THREAD

**Issue by Michael-Yongshi** [pypa/packaging-problems#373]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.6.8

3. What version of pip do you have?

pip 20.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?
Guide worked fine until actually using setuptools and wheels to generated distributable. No text was generated and no dist files were found, like it never run in the first place.

**Comment by uranusjr** [comment]
What happens if you just run `python` or `python setup.py`?

**Comment by Michael-Yongshi** [comment]
i get this

```
E:\Git\packaging_tutorial>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python setup.py
  File "<stdin>", line 1
    python setup.py
               ^
SyntaxError: invalid syntax
>>>
```

**Comment by kethan1** [comment]
run `python setup.py` in the terminal

**Comment by Michael-Yongshi** [comment]
PS E:\Git\packaging_tutorial> python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
PS E:\Git\packaging_tutorial>

**Comment by merwok** [comment]
Did that latest command not create a wheel and an sdist in a `dist` directory?

**Comment by Michael-Yongshi** [comment]
nope

**Comment by uranusjr** [comment]
What happens if you simply run `python3`? I suspect `python.exe` and `python3.exe` are pointing to different executables on your machine. Most likely, the latter is pointing to Microsoft’s Python stub, which sliently does nothing when you pass arguments to it. Simply running `python3` will open the Windows Store page of Python if my assumption is correct.

Try running `python setup.py sdist bdist_wheel` if this is the case. The `python` command seems to work fine, judging from previous information you gave.

**Comment by Michael-Yongshi** [comment]
yeah that works, so i was just using the wrong python command
