### ISSUE TITLE
Packaging with Twine: prompt for password is displayed, but cannot write

### ISSUE THREAD

**Issue by TesterSzymoon** [pypa/packaging-problems#376]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

3.8.3

3. What version of pip do you have?

20.1.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

I followed this great tutorial and wanted to upload my package to TestPyPi. I wrote my name, and then prompt for password was displayed, but I couldn't write. I just clicked enter and 403 error has occured, that's all. Here's visualistation:

```
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: __token__
Enter your password: <CANNOT WRITE HERE>
```

Do someone know how to fix that?

**Comment by merwok** [comment]
It’s possible that the input code receives your character, but doesn’t echo any `*` or other symbol, to avoid revealing the password length.  Can you try entering the username, then pasting or typing the password + `Enter`?

**Comment by bhrutledge** [comment]
@TesterSzymoon Are you sure you're using the token for TestPyPI? As noted at https://test.pypi.org/help/#invalid-auth:

>  PyPI and TestPyPI each require you to create an account, so your credentials may be different.

**Comment by bhrutledge** [comment]
@TesterSzymoon It looks like there's an issue with pasting passwords in Windows. I wrote up the details at https://github.com/pypa/twine/issues/671#issuecomment-674510081. Can you read that, and confirm that one of the workarounds works for you?

**Comment by layday** [comment]
I'll close this now but feel free to comment below if the problem persists.
