### ISSUE TITLE
Automatic updates when setup.py changes

### ISSUE THREAD

**Issue by kevinburke** [pypa/packaging-problems#38]
Not sure if this is relevant, but let's say a setup.py updates the version of a dependency or adds a new dependency, then you try rerunning the tests or server locally, and everything fails with an importerror, or "this method doesn't take that kwarg" until you remember to rerun your package dependency install, it's annoying, and can be confusing to non-Python users. 

Maybe a tool that checked your current environment for consistency with the setup.py or requirements.txt would be neat, this might not be feasible in practice.

**Comment by pradyunsg** [comment]
We can do this now with editable installs for development and `pip check`. :)
