### ISSUE TITLE
Could not find a version that satisfies the requirement os-testr===2.0.0  

### ISSUE THREAD

**Issue by yassinebenben** [pypa/packaging-problems#380]
hello, I'm trying to install openstack/devstack rocky on Ubuntu 18.04. (installed on Oracle VirtualBox) 
When using "FORCE=yes ./stack.sh" to launch openstack installation i got the following errors
Did anyone encounter this issue before? could you please suggest a solution? many thanks for your answers 
the error message is as follow --->

+inc/python:pip_install:363                sudo -H http_proxy= https_proxy= no_proxy= PIP_FIND_LINKS= SETUPTOOLS_SYS_PATH_TECHNIQUE=rewrite /usr/local/bin/pip2.7 install -c /opt/stack/requirements/upper-constraints.txt -U os-testr
Ignoring importlib-metadata: markers 'python_version == "3.6"' don't match your environment
Ignoring dataclasses: markers 'python_version == "3.6"' don't match your environment
Ignoring importlib-resources: markers 'python_version == "3.6"' don't match your environment
Collecting os-testr===2.0.0 (from -c /opt/stack/requirements/upper-constraints.txt (line 420))
  Could not find a version that satisfies the requirement os-testr===2.0.0 (from -c /opt/stack/requirements/upper-constraints.txt (line 420)) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.1.0)
No matching distribution found for os-testr===2.0.0 (from -c /opt/stack/requirements/upper-constraints.txt (line 420))
You are using pip version 9.0.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+inc/python:pip_install:1                  exit_trap
+./stack.sh:exit_trap:521                  local r=1
++./stack.sh:exit_trap:522                  jobs -p
+./stack.sh:exit_trap:522                  jobs=
+./stack.sh:exit_trap:525                  [[ -n '' ]]
+./stack.sh:exit_trap:531                  '[' -f '' ']'
+./stack.sh:exit_trap:536                  kill_spinner
+./stack.sh:kill_spinner:431               '[' '!' -z '' ']'
+./stack.sh:exit_trap:538                  [[ 1 -ne 0 ]]
+./stack.sh:exit_trap:539                  echo 'Error on exit'
Error on exit
+./stack.sh:exit_trap:541                  type -p generate-subunit
+./stack.sh:exit_trap:542                  generate-subunit 1594942161 67 fail
+./stack.sh:exit_trap:544                  [[ -z /opt/stack/logs ]]
+./stack.sh:exit_trap:547                  /home/yassine/devstack/tools/worlddump.py -d /opt/stack/logs
World dumping... see /opt/stack/logs/worlddump-2020-07-16-233029.txt for details
+./stack.sh:exit_trap:556                  exit 1
yassine@yassine-VirtualBox:~/devstack$ ^C

**Comment by merwok** [comment]
From PyPI, I see that os-testr 2.0.0 only supports Python 3.
