### ISSUE TITLE
I can not type anything in the password input for python -m twine upload --repository testpypi dist/*

### ISSUE THREAD

**Issue by ZenTheDev** [pypa/packaging-problems#384]
### 1. Operating system and version:

Windows 10

### 2. Python version:

3.8.5

### 3. Version of PIP:

20.2

### 5. Issue

I can't type anything in the password input you get by preforming the command 'python -m twine upload --repository testpypi dist/*'
It shows "Password: " However I can't type anything in it. The only thing I can do is press enter. I can't copy anything to it, I have tried reopening command prompt. Nothing works. It's just broken. I don't know what to do, **any help is appreciated.**

### 6. Screenshot:

![screenshot](https://user-images.githubusercontent.com/59929565/89138073-51f9c700-d508-11ea-8f5d-ee3c64cdd7fe.PNG)

**Comment by uranusjr** [comment]
The password prompt does not show any characters (not even `*`) when you type in it, to avoid the output being sniffed from console history. Can you try typing the password and just hit enter and see if that works?

**Comment by ZenTheDev** [comment]
> The password prompt does not show any characters (not even `*`) when you type in it, to avoid the output being sniffed from console history. Can you try typing the password and just hit enter and see if that works?

Didn't work, copied and pasted token and it still gave me an error.

**Comment by bhrutledge** [comment]
@ZenTheDev  Are you sure you're using the token for TestPyPI? As noted at https://test.pypi.org/help/#invalid-auth:

>  PyPI and TestPyPI each require you to create an account, so your credentials may be different.

**Comment by ZenTheDev** [comment]
Yes I am sure.

**Comment by bhrutledge** [comment]
@ZenTheDev It looks like there's an issue with pasting passwords in Windows. I wrote up the details at https://github.com/pypa/twine/issues/671#issuecomment-674510081. Can you read that, and confirm that one of the workarounds works for you?

**Comment by ZenTheDev** [comment]
None of them seem to work for me. I guess I am just not gonna be able to make a python package on my pc /:

**Comment by bhrutledge** [comment]
@ZenTheDev One of these options _should_ work from Command Prompt:

1. Clicking `Edit > Paste` from the `Command Prompt` menu
2. Enabling `Properties > Options > Use Ctrl+Shift+C/V as Copy/Paste` in the `Command Prompt` menu
3. Use right-click to paste

Here's an example of option 1 working for me:

![Kapture 2020-08-18 at 12 06 56](https://user-images.githubusercontent.com/1326704/90538206-3a4b5100-e14c-11ea-8f07-ee9040dc7682.gif)

In the interest of enabling you to use your token (which is better than username/password) and assisting future Windows Python developers, would you be game to give one of those options a try?

**Comment by gabybarcodes** [comment]
Hi! How did you solve this problem?
