### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by csarahc** [pypa/packaging-problems#386]
1. What is your operating system and version?

Mac OS Catalina 10.15.3

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

pip 19.0.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#pure-python-wheels

5. Could you describe your issue in as much detail as possible?

When I run "% python setup.py sdist" or "% python3 setup.py sdist bdist_wheel" I keep getting an error "error: error in 'egg_base' option: 'src' does not exist or is not a directory". I tried this locally and inside a Python virtual environment but I get the same errors in both. I can't seem to resolve this problem, I'm not sure what to exactly do? 

Entire output:
% python setup.py sdist      
running sdist
running egg_info
error: error in 'egg_base' option: 'src' does not exist or is not a directory

**Comment by merwok** [comment]
It seems like you are defining that your code modules are in an `src` directory, but it’s not the case.

Can you provide the contents of `setup.py` and `setup.cfg` (if it exists), as well as an idea of how your code files are laid out?

**Comment by csarahc** [comment]
Hello! I resolved the errors, I just had to create some directories for src and data, thank you for following up!
