### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by rlele5** [pypa/packaging-problems#390]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

macOS 10.14.5

2. What is your Python version?

3.7.6

3. What version of pip do you have?

20.2.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

5. Could you describe your issue in as much detail as possible?

Locally on my mac when I run `python3 setup.py sdist bdist_wheel` the data files are included in both my tar.gz and the wheel (I have set up a MANIFEST.in and included the files in package_data in setup.py).

However, when the Jenkins runs this command: `python3 setup.py sdist bdist_wheel`, the data files do not make it into the distribution wheel. Any tips on how to resolve this?

**Comment by merwok** [comment]
Could you show:
- your setup.py script (at least the lines with imports, package name, packages/modules, package data)
- how the files are laid out (for example, `setup.py` file, next to it `my_package` that contains `__init__.py` and other modules, and also `images` that contains `image1.png` and others — you can use `ls` or `tree` command for this and remove boring lines from the output)

**Comment by rlele5** [comment]
Hi, thanks for the quick response!

setup.py:
```import setuptools
import os

setuptools.setup(
    name="sglib",
    version="2.5.3",
    description="<redacted>",
    packages=setuptools.find_packages(),
    package_data={"sglib": ["*.json"]},
    include_package_data=True
)```

Tree structure with boring files removed
```sgllib
├── sg.py
├── __init__.py
├── args
│   ├── SArguments.py
│   ├── SArgumentsFactory.py
│   ├── SCommandLineArguments.py
│   ├── SDictArguments.py
│   ├── __init__.py
├── sol
│   ├── QueryJson.py
│   ├── QueryJsonBaseDefault.json
│   ├── SRequest.py
│   ├── SRequestRunner.py
│   ├── SOutputParser.py
│   ├── __init__.py
├── sutils
│   ├── SUtils.py
│   ├── URLParser.py
│   ├── __init__.py
│   └── sg.properties.json
```
Snipped some of the other sub modules, but this structure contains the JSON files that are skipped in the Jenkins build

**Comment by rlele5** [comment]
Hi, I found the problem. My manifest file was named `MANIFEST.IN` instead of `MANIFEST.in`. My local accepts both, but the Jenkins server requires the lowercase extension. Thank you for your time :)
