### ISSUE TITLE
after typing "python3 setup.py sdist bdist_wheel" in the promp (at the same folder where setup.py is located I get no "reaction" 

### ISSUE THREAD

**Issue by EnzoMartinelli** [pypa/packaging-problems#392]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

**Comment by merwok** [comment]
Hello, please answer the questions asked!

**Comment by Parmodsihag** [comment]
Hi there,
I also faced the same error
but now i resolved it
try to run setup.py 
it will show an error 
in my case error was in language i using in readme.md file
you may have different error
then try to resolve that error and try again
it works for me

**Comment by layday** [comment]
I'll close this now but feel free to comment below if the problem persists.
