### ISSUE TITLE
package directory 'p' does not exist

### ISSUE THREAD

**Issue by mehdizadehm** [pypa/packaging-problems#393]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

**Comment by merwok** [comment]
Hello!  You did not answer the questions in the template, but I think I know what your problem is!

Do you have code like `packages="package"` in your `setup.py` file?  If so, it should be `packages=["package"]`.

**Comment by layday** [comment]
Feel free to comment below with more details if this is still an issue for you.

**Comment by henryiii** [comment]
I've done this before. Using `find_packages` or setup.cfg's `packages = find:` is better.
