### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by adam052113** [pypa/packaging-problems#394]
1. Linux raspberry pi 

2. Python 2.7.16

3. I get an error when using that command;
Usage:   
  /usr/bin/python -m pip <command> [options]

no such option: --vesion
 

4. https://packaging.python.org/tutorials/packaging-projects/
5. when I use the command python3 setup.py sdist bdist_wheel this error happens,
python3: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by merwok** [comment]
What exact command did you type?

It seems that you typed `python -m pip --vesion`, with a bad option (vesion instead of version)
