### ISSUE TITLE
Markdown not rendering due to missing `long_description_content_type`

### ISSUE THREAD

**Issue by RealPolitiX** [pypa/packaging-problems#395]
Hi there, I have a markdown rendering issue on PyPI, but this doesn't seem to fit with any previous case.

My computer runs Windows 10.

When building and twin-checking the repo hdfio (https://github.com/RealPolitiX/hdfio), the following error appeared.
``` bash
Checking dist\hdfio-0.2.1-py2.py3-none-any.whl: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist\hdfio-0.2.1.tar.gz: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 39: Warning: Inline literal start-string without end-string.
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```
The upload to PyPI (https://pypi.org/project/hdfio/) doesn't render the text in README.md (version 0.2.0 has the same issue).

``` bash
python --version = 3.6.4
twine --version = 3.2.0
```
twine was installed using pip.

To reproduce the error message above, use the following
``` bash
python setup.py sdist bdist_wheel --universal
twine check dist/*
```

**Comment by di** [comment]
This is https://github.com/pypa/setuptools/issues/1126

**Comment by RealPolitiX** [comment]
So I remove the ``encoding=utf-8`` argument when reading the markdown file in setup.py. This made most thing work! See https://test.pypi.org/project/hdfio/

Except now that the fenced code block (with triple backticks) are not parsed correctly, how would you solve that?

**Comment by RealPolitiX** [comment]
I realized that one can use the alternative markup of a code block to let the markdown parser read it correctly, like the following,
``<pre><code class="console"> some code
</code></pre>
``
It's rendered correctly now on PyPI (https://pypi.org/project/hdfio/)
