### ISSUE TITLE
error: invalid command

### ISSUE THREAD

**Issue by honeywhisperer** [pypa/packaging-problems#399]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

**Comment by merwok** [comment]
hi, you did not answer any of the question or describe your issue at all

**Comment by honeywhisperer** [comment]
Hi, thank you for the reply and I apologize for incomplete message, it was
sent before I read everything around on the page. I am new on the portal
and I tend to do better next time.

Have a good weekend!

**Comment by merwok** [comment]
no worry but what is the problem you have?

**Comment by honeywhisperer** [comment]
Thanks!
I am.following the tutorial about uploading module. looks like the tutorial
is older one. I plan to rebuild the setup.py (following some fresher
instructions) and then try the upload again.
I'll write the results or questions in a day or two.
Thanks again.

**Comment by honeywhisperer** [comment]
Hello,

Just to inform that I have completed my exercise about publishing python
built distribution. Thank you for your support.

Have a nice day!
Nikola

**Comment by merwok** [comment]
ok, please close the ticket then! :slightly_smiling_face:
