### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by edmundsj** [pypa/packaging-problems#402]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

OS X 10.13

2. What is your Python version?

3.7.6

3. What version of pip do you have?

20.12

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

After installing twine, I attempted to run the command to upload to the pypi test repository, and got the following output:

```
(base) C02X32GFJGH5:packaging_tutorial jordan.e$ python3 -m twine upload --repository testpypi dist/*
Traceback (most recent call last):
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/jordan.e/opt/miniconda3/lib/python3.7/site-packages/twine/__init__.py", line 32, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

I installed twine and setuptools with miniconda, not pip.

**Comment by edmundsj** [comment]
This was fixed by installing twine from the conda-forge channel instead of defaults.

**Comment by merwok** [comment]
ok!  you can close the issue then :slightly_smiling_face:
