### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by arghya1979** [pypa/packaging-problems#406]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.7

3. What version of pip do you have?

pip 19.0.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

C:\Users\arghyaroytvst>pip install --user C:\Users\arghyaroytvst\dist\grse_etl_ops-1.0.tar.gz
Processing c:\users\arghyaroytvst\dist\grse_etl_ops-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\ProgramData\Anaconda3\lib\tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ARGHYA~1\\AppData\\Local\\Temp\\pip-req-build-f_mhhu7i\\setup.py'
This is the error I am getting. I have followed the instruction as given in https://packaging.python.org/tutorials/packaging-projects/

**Comment by uranusjr** [comment]
`grse_etl_ops` is packaged incorrectly. If you received it from someone, please talk to them to fix the package. If you have built the package yourself, please read the [Packaging Python Project](https://packaging.python.org/tutorials/packaging-projects/) tutorial for instructions on how to create a pip-installable package distribution.

**Comment by uranusjr** [comment]
Oh, sorry, I did not realise you have already linked to that tutorial. Did you write a setup.py file as instructed by the tutorial? Because pip is not finding that file in your tar.gz file.

**Comment by arghya1979** [comment]
@uranusjr : Yes I did. Only exception is when running `setup.py sdist bdist-wheel` I ran it from directory where `python.exe` is installed which is `c:\users\arghyaroytvst`. Original `setup.py` is in `C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops`. Is it a concern?

**Comment by arghya1979** [comment]
@uranusjr : Please see below the screenshot while building.

![package_error](https://user-images.githubusercontent.com/19373553/97809524-5793b400-1c93-11eb-8aa7-141925e54b3f.jpg)

**Comment by uranusjr** [comment]
Reading the log closely, the `sdist` command did not even write the `setup.py` file into your `.tar.gz`. Can you share the whole project structure? You can use the built-in `tree` command to display it, like this:

```
> tree C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops
```

**Comment by arghya1979** [comment]
Here it goes:

![Inkedpackage_structure_LI](https://user-images.githubusercontent.com/19373553/97810208-3ed9cd00-1c98-11eb-9957-475574eab6db.jpg)

**Comment by uranusjr** [comment]
That looks right. Can you try `cd` into the directory where `setup.py` is, and run the `sdist bdist_wheel` command there? It should create a `dist` directory at the same directory as `setup.py`. Are files in that `dist` directory installable by pip?

**Comment by arghya1979** [comment]
Also in `setup.py`, the `README.md` was read as follows:
    `with open(path/to/ README.md, 'r') as fh:
             long_description = fh.read()`

**Comment by arghya1979** [comment]
> That looks right. Can you try `cd` into the directory where `setup.py` is, and run the `sdist bdist_wheel` command there? It should create a `dist` directory at the same directory as `setup.py`. Are files in that `dist` directory installable by pip?

No. I am getting error as above. Please note I am not `uploading` this package due to confidentiality issue. So I am using `pip install /path/to/grse_etl_ops-1.0.tar.gz`

**Comment by arghya1979** [comment]
> That looks right. Can you try `cd` into the directory where `setup.py` is, and run the `sdist bdist_wheel` command there? It should create a `dist` directory at the same directory as `setup.py`. Are files in that `dist` directory installable by pip?

You meant `setup.py sdist bdist_wheel` as command? I ran this and nothing happening.

**Comment by uranusjr** [comment]
The full sequence of commands I was expecting is:

```cmd
C:\Users\arghyaroytvst> cd C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops
C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops> python setup.py sdist bdist_wheel
C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops> pip install dist\grse_etl_ops-1.0.tar.gz
```

There are a few important points:

1. You should `cd` into where `setup.py` is.
2. The resulting `dist` directory should be located in the *same directory* as `setup.py`, i.e. `C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops\dist`.
3. The directory is in your original log is at `C:\Users\arghyaroytvst\dist`, which is not expected if you follow the tutorial strictly.

My suspicion is you have multiple `grse_etl_ops` directories, and `setup.py` is confused which directory you want to package. This is why the tutorial explicitly says

> Once you create this structure, you’ll want to run all of the commands in this tutorial within the top-level folder - so be sure to `cd packaging_tutorial`.

because otherwise it’s very easy to specify the file paths incorrectly, resulting in setup.py not doing what you want.

**Comment by merwok** [comment]
> You should cd into where setup.py is.

This is important; distutils (and I think setuptools, that extends it) really expects you to run in the directory of setup.py

**Comment by arghya1979** [comment]
> The full sequence of commands I was expecting is:
> 
> ```batchfile
> C:\Users\arghyaroytvst> cd C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops
> C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops> python setup.py sdist bdist_wheel
> C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops> pip install dist\grse_etl_ops-1.0.tar.gz
> ```
> 
> There are a few important points:
> 
> 1. You should `cd` into where `setup.py` is.
> 2. The resulting `dist` directory should be located in the _same directory_ as `setup.py`, i.e. `C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops\dist`.
> 3. The directory is in your original log is at `C:\Users\arghyaroytvst\dist`, which is not expected if you follow the tutorial strictly.
> 
> My suspicion is you have multiple `grse_etl_ops` directories, and `setup.py` is confused which directory you want to package. This is why the tutorial explicitly says
> 
> > Once you create this structure, you’ll want to run all of the commands in this tutorial within the top-level folder - so be sure to `cd packaging_tutorial`.
> 
> because otherwise it’s very easy to specify the file paths incorrectly, resulting in setup.py not doing what you want.

When running `C:\Users\arghyaroytvst\Desktop\GardenReach\Data_Model\grse_etl_ops>python setup.py sdist bdist_wheel`
I get an error : `python is not a windows command` (similar like this).

**Comment by pfmoore** [comment]
Try running `py setup.py sdist bdist_wheel`. You probably didn't choose "Add Python to your PATH" when you installed Python. The `py` command will run Python for you, even though it's not on your path.

**Comment by arghya1979** [comment]
The issue is resolved now. Had added python to the SYS.PATH and at environment variable. And then run the setup.py from the same directory where the setup.py is located.
