### ISSUE TITLE
"[Errno 16] Device or resource busy: 'build/bdist.linux-x86_64/wheel/ChadBot-0.1.dist-info'")]

### ISSUE THREAD

**Issue by captanlevi** [pypa/packaging-problems#408]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

**Comment by merwok** [comment]
Hello!  What is the problem?

**Comment by captanlevi** [comment]
Hello , I was running WSL on windows and hence windows was not permitting WSL to delete the whl file.
It worked when I used it on windows powershell. Sorry for this
