### ISSUE TITLE
Installation of PIP tools on servers where internet connection is unavailable

### ISSUE THREAD

**Issue by amarpdombe** [pypa/packaging-problems#409]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
RHEL 7.7

2. What is your Python version?
2

3. What version of pip do you have?
9 ( Default as Part of OS 

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

**Comment by pradyunsg** [comment]
Hi! Please fill out the issue template.

**Comment by layday** [comment]
I'll close this now but feel free to comment below with more details.
