### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by ljy-002** [pypa/packaging-problems#411]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Windows 10

2. What is your Python version?
1.3.7(x64)

3. What version of pip do you have?
new

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
https://packaging.python.org/tutorials/packaging-projects/
![image](https://user-images.githubusercontent.com/63292034/100542149-6c0fa000-3283-11eb-8077-4126c76324bc.png)
![image](https://user-images.githubusercontent.com/63292034/100542163-847fba80-3283-11eb-9377-9efc59b82d26.png)

5. Could you describe your issue in as much detail as possible?
Cannot perform this command

**Comment by ljy-002** [comment]
There is this file in the path
![image](https://user-images.githubusercontent.com/63292034/100542332-37e8af00-3284-11eb-823a-78576e310bf0.png)

**Comment by bhrutledge** [comment]
It looks like you ran `pip setup.py sdist bdist_wheel` in the `algorithm_class` directory. The command should be `python3 setup.py sdist bdist_wheel`, and it should be run from the directory that contains `setup.py`.

**Comment by ljy-002** [comment]
`python3 setup.py sdist bdist_wheel`?
This command is invalid

**Comment by ljy-002** [comment]
Because I tried it, I used "pip"

**Comment by ljy-002** [comment]
it says:
'python3' is not an internal or external command, nor an executable program
Or batch file.
![image](https://user-images.githubusercontent.com/63292034/101238566-1708d980-371c-11eb-9e7b-ec47b0573c0b.png)

**Comment by ljy-002** [comment]
Try to run,
It went wrong at this place:
![image](https://user-images.githubusercontent.com/63292034/101238645-926a8b00-371c-11eb-8436-a3575140d18f.png)
![image](https://user-images.githubusercontent.com/63292034/101238639-88488c80-371c-11eb-8753-3079313e93f2.png)

**Comment by merwok** [comment]
What is the character encoding of the readme file?
Find that then use `open("README.md", encoding="...")`

**Comment by ljy-002** [comment]
![image](https://user-images.githubusercontent.com/63292034/101270765-3bfe5a80-37b7-11eb-8f7d-09d36ac9e323.png)
![image](https://user-images.githubusercontent.com/63292034/101270768-428cd200-37b7-11eb-870a-79323b3f7d14.png)

**Comment by merwok** [comment]
Is seems like you ran `setup.py` without adding a command (like `sdist` or `bdist_wheel`)

**Comment by ljy-002** [comment]
Whether to run the command first or run Python first

**Comment by merwok** [comment]
You are not giving enough information to describe what you are doing, and not saying if you are following the help given here.

Run `pip install wheel` then `python setup.py bdist_wheel sdist`.

**Comment by ljy-002** [comment]
Hmm... I seem to succeed

**Comment by ljy-002** [comment]
Is `python setup.py sdist bdist_wheel` and `python setup.py bdist_wheel sdist` the same meaning

**Comment by ljy-002** [comment]
I have written Python3.9.1 in the environment variable
Why is it like this:
![image](https://user-images.githubusercontent.com/63292034/106601011-1cf12e80-6596-11eb-9bd1-26ac3c9544e4.png)

**Comment by ljy-002** [comment]
problem solved

**Comment by merwok** [comment]
What environment variable are you talking about?
What was the problem and solution?

**Comment by ljy-002** [comment]
Windows environment variables
This problem has been resolved:
![image](https://user-images.githubusercontent.com/63292034/106825363-b0724e80-66bf-11eb-9320-4fe6250eff2a.png)

**Comment by merwok** [comment]
This ticket is not closed, please use the Close button.

**Comment by ljy-002** [comment]
Ok
