### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Ayaan-Imran** [pypa/packaging-problems#415]
This is the error I faced:

bash: /c/Users/ayaan/AppData/Local/Microsoft/WindowsApps/python3: Permission denied

**Comment by merwok** [comment]
How did you install that Python?

**Comment by Ayaan-Imran** [comment]
What do you mean

**Comment by merwok** [comment]
It’s hard to help without any information about your environment!
Could you tell us:
- OS version
- Python version
- how you installed Python
- what tutorial or guide are you following, if any
- what command you are trying to run

**Comment by Ayaan-Imran** [comment]
- Windows 10
- 3.8.2
- Just like everyone else. I set python to path and then just clicked on install
- I was following [python's tutorial](https://packaging.python.org/tutorials/installing-packages/)
- python3 setup.py sdist bdist_wheel

I hope this have helped you

**Comment by merwok** [comment]
Sorry, I don’t know what WindowsApps are; your command line looks like a unix emulation layer inside windows?  Try running: `ls -hla /c/Users/ayaan/AppData/Local/Microsoft/WindowsApps/python3` to see what the file permissions are.  They should be something like `-rwxr-xr-x`, where `r` means the file can be read and `x` that it can be executed.

(I also don’t know what «I set python to path and then just clicked on install» means; for example, my system comes with Python 3.8, and I run `aptitude install python3.9` in a terminal to add a new version, like many many people (but not everyone!) do :slightly_smiling_face:).

**Comment by pfmoore** [comment]
This looks like you installed Windows Python from the Microsoft store, and are now trying to run it from WSL (the Windows Subsystem for Linux).

I'm not sure if that's supported, but even if it is, it's not the best way for a relative newcomer to use Python in WSL. I'd strongly recommend treating WSL as a completely separate (Linux) system, and following tutorials for running Python on Linux. However, I don't know what the best practices are for running Python on Linux, so I can't advise you on those.

**Comment by Ayaan-Imran** [comment]
Okay. I didn't install it from the Microsoft store. I installed it from python.org. I set python to path and installed it with default setting **(This all happened in the setup wizard)**. 

When I ran `ls -hla /c/Users/ayaan/AppData/Local/Microsoft/WindowsApps/python3`, This is what got spilled out:
```console
-rwxr-xr-x 1 ayaan 197610 0 Nov 20 18:36 /c/Users/ayaan/AppData/Local/Microsoft/WindowsApps/python3*
```

And by the way I am using windows not liniux

Thankyou for your efforts. If you can't resolve the problem, I will try to find another way

**Comment by merwok** [comment]
Yes, Paul said you are using linux inside windows (WSL), which is shown by the fact you are using the bash shell and the path looks like `/c/Users/etc` and not `C:\Users\etc`.

Again, I don’t know what `set python to path` means, but it seems that you downloaded and installed a windows build of Python, but now you are running commands in a linux shell and that’s incompatible.  Either use a windows shell (powershell) or look at a WSL guide for how to install Python for WSL.

**Comment by Ayaan-Imran** [comment]
Oh okay thx
