### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Yoplayer-1** [pypa/packaging-problems#416]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
>>> Windows 10.

2. What is your Python version?
>>> Python 3.8.6

3. What version of pip do you have?
>>> pip 20.3.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
>>> https://tinyurl.com/Python-Packaging-Projects 

5. Could you describe your issue in as much detail as possible?

>>>  I ran the command - " python3 setup.py sdist bdist_wheel " but no output came.

 But when I ran - " python setup.py sdist bdist_wheel " but it opened my shell.  I think this is happening because of  I have a .bat (batch) file  that contains the path to python so if you want I can delete it.
[Speak-main.zip](https://github.com/pypa/packaging-problems/files/5650154/Speak-main.zip)

Then I ran this command -  " setup.py sdist bdist_wheel " it gave me this output - 
" usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel' "

**Comment by merwok** [comment]
This last error message means that you need to install the `wheel` package.

**Comment by layday** [comment]
I assume installing wheel fixed that for you.  Feel free to comment below if it hasn't.
