### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by masterleming** [pypa/packaging-problems#418]
1. What is your operating system and version?
Current Archlinux with LTS kernel.

2. What is your Python version?
3.9.0

3. What version of pip do you have?
20.3.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
I am not exactly following this tutorial but I use it for reference as I have learnt from it: https://packaging.python.org/tutorials/packaging-projects/
Unfortunately I cannot find the article or post I got the idea wi th `setup.cfg` file.

5. Could you describe your issue in as much detail as possible?
I don't like the default behaviour of `setuptools` (not only probably, but I do not know exactly) of creating build directories in the project root (e.g. `dist`) so I use specific config in `setup.cfg`:
```
[egg_info]
egg_base = ./build

[sdist]
dist_dir = ./build/dist

[bdist_wheel]
bdist_dir = ./build/_wheel
dist_dir = ./build/dist
```
But with that I am unable to use `python setyp.py develop` or `pip install --editable .` -- for both cases I am getting "Can't get a consistent path to setup script from installation directory" error. Without this build directory configuration both methods work.

**Comment by pfmoore** [comment]
That's something very specific to setuptools, and probably counts as "advanced" usage, so I'd suggest you ask on the setuptools tracker whether your usage is intended to work.

**Comment by masterleming** [comment]
Thanks.
