### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by hostingthepage** [pypa/packaging-problems#422]
Hello Team .
C:\Users\Jainam Oswal>pip3 install helome 
ERROR: Could not find a version that satisfies the requirement upgrade
ERROR: No matching distribution found for upgrade

[And My full source code is here on github ](https://github.com/hostingthepage/Help-Me)

Why this error ?
I've build my own packge.

![image](https://user-images.githubusercontent.com/73230800/103367987-745e3380-4aec-11eb-9bd9-dedac6bade59.png)
![image](https://user-images.githubusercontent.com/73230800/103368022-863fd680-4aec-11eb-8350-887ce54ddb69.png)
![image](https://user-images.githubusercontent.com/73230800/103368032-8dff7b00-4aec-11eb-95f8-36f2f2f24595.png)

**Comment by hostingthepage** [comment]
I've build this package as a test package.
I have a original code but before publishing that, I've published this for test purposes.

But I have many folders Like here there are name1 and name2.
How to use files which are in that folder ?
Can you help me ?

**Comment by merwok** [comment]
Are you sure you’re pasting the error output corresponding to the command you gave?

> ERROR: Could not find a version that satisfies the requirement upgrade

This seems like the kind of error you would get for a command like `pip install upgrade helome` (forgot the dashes in `--upgrade`), or if your `helome` package had `install_requires=["upgrade"]`.

**Comment by hostingthepage** [comment]
dir :- 

      - setup.py
      - LICENSE
      - README.txt
      - helome :- 
                        - folder 1 
                                  - file1.py
                                  - file 2.py

                        - folder 2 
                                - file 1.py
                                - file 2.py


I want to add multiple folders in the module, So that in the script, User can use it like :- 
`from <helome> import <1stfolder>`
`from <helome> import <2ndfolder>`
`helome.1stfolder.file1,cool()
helome.1stfolder.file2.send("Dummy data")
helome.2ndfolder.file1.retrivedata("All_Data")
helome.2ndfolder.file2.deletedata("Last date of year")`

**Comment by hostingthepage** [comment]
Assume the latest as the Problem.
I want the library work like the above, What should I name everything ?
To use it like I said before ?
@merwok @alex @pjenvey @berkerpeksag

**Comment by merwok** [comment]
So if you want a package `helome` with sub-packages `helome.thing1` and `helome.thing2`, make sure to create empty files named `__init__.py` in `helome` and the sub-directories.  Do not have spaces in the package names (the directories) or the module names (the python files).

**Comment by hostingthepage** [comment]
Thanks for your reply @merwok, 
I'll check and post you.
I'm closing this issue now.
