### ISSUE TITLE
Failed to install the pytest-capturelog with pip install with "No matching distribution found for"

### ISSUE THREAD

**Issue by mpapply11** [pypa/packaging-problems#423]
1. What is your operating system and version?
MacOS Darwin xxxxxxxxx 18.7.0 Darwin Kernel Version 18.7.0
also tried inside the docker builder as image of below.
the docker builder with the python2.7 as base image (FROM python:2.7)

2. What is your Python version?
tried on both python 2.7 as well as python3.8

3. What version of pip do you have?
> # pip -V                                                                                                                                                                                                 
pip 20.3.3 from /Library/Python/2.7/site-packages/pip (python 2.7)

 > #  pip3.8 -V            
pip 20.3.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
None

5. Could you describe your issue in as much detail as possible?
I am trying to install the pytest-capturelog as one of my dependency, and it failed as the details of "No matching distribution found for",
I had run the pip3.8 install --upgrade -v pip already and still the same error.
**it seems the index url doesn't list/indexed the package pytest-capturelog ?**
Found index url https://pypi.org/simple

> # pip3.8 install pytest-capturelog -vvv                                                                                                                                                                  
WARNING: The directory '/Users/pmao/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Using pip 20.3.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-1m_fnsgd
Created temporary directory: /private/tmp/pip-req-tracker-7vwuaoc9
Initialized build tracking at /private/tmp/pip-req-tracker-7vwuaoc9
Created build tracker: /private/tmp/pip-req-tracker-7vwuaoc9
Entered build tracker: /private/tmp/pip-req-tracker-7vwuaoc9
Created temporary directory: /private/tmp/pip-install-tmu22w6j
1 location(s) to search for versions of pytest-capturelog:
* https://pypi.org/simple/pytest-capturelog/
Fetching project page and analyzing links: https://pypi.org/simple/pytest-capturelog/
Getting page https://pypi.org/simple/pytest-capturelog/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pytest-capturelog/ HTTP/1.1" 404 13
Could not fetch URL https://pypi.org/simple/pytest-capturelog/: 404 Client Error: Not Found for url: https://pypi.org/simple/pytest-capturelog/ - skipping
Given no hashes to check 0 links for project 'pytest-capturelog': discarding no candidates
ERROR: Could not find a version that satisfies the requirement pytest-capturelog
ERROR: No matching distribution found for pytest-capturelog
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'pytest-capturelog'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('pytest-capturelog')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 312, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('pytest-capturelog'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pytest-capturelog
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Fetching project page and analyzing links: https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 15396

**Comment by merwok** [comment]
I can’t find a project page for pytest-capturelog.  Some PyPI pages are in web search results but then give 404.  Maybe the project is inactive and the distributions have been deleted.  Can you share any link about pytest-capturelog?

**Comment by mpapply11** [comment]
Thank you @merwok  for reply. 
I see the pytest-catchlog declare itself as "This is a fork of pytest-capturelog."
so seems the name changed or original one was removed, I will use this one as replacement.
https://pypi.org/project/pytest-catchlog/
