### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by gbland0725** [pypa/packaging-problems#431]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

python version 3.8

3. What version of pip do you have?

pip version 21.0

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

API token is not working

5. Could you describe your issue in as much detail as possible?

All following steps worked until I get to upload the archives to dist. I get the following message:

**twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: __token__
Enter your password:
Uploading sphandles-0.1.0-py2.py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████| 9.18k/9.18k [00:00<00:00, 36.0kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.**

I made sure to paste in the username and password correctly, but still would not allow me to upload my token.

**Comment by bhrutledge** [comment]
@gbland0725 Please don't share your token. For security sake, consider regenerating it.

Did you read through the tips at https://test.pypi.org/help/#invalid-auth?

You might also try `twine upload --verbose` (as of Twine 3.3.0) to get more information about your credentials.

**Comment by gbland0725** [comment]
Thank you! I deleted that token and started a new one. 

Yes, I went through the tips and made sure. My password is not being displayed when I type it in, but I assume it's registering since I typed it out or pasted just fine on a blank command prompt or notepad .

Here's the response from --verbose

twine upload --verbose
usage: twine upload [-h] [-r REPOSITORY] [--repository-url REPOSITORY_URL] [-s] [--sign-with SIGN_WITH] [-i IDENTITY]
                    [-u USERNAME] [-p PASSWORD] [--non-interactive] [-c COMMENT] [--config-file CONFIG_FILE]
                    [--skip-existing] [--cert path] [--client-cert path] [--verbose] [--disable-progress-bar]
                    dist [dist ...]
twine upload: error: the following arguments are required: dist

**Comment by bhrutledge** [comment]
@gbland0725, sorry, that should be:

```
twine upload --verbose --repository testpypi dist/
```

**Comment by bhrutledge** [comment]
Again, assuming `twine --version` is 3.3.0.

**Comment by gbland0725** [comment]
Here is the following response from that command

**Using configuration from C:\Users\[redacted]/.pypirc
Uploading distributions to https://test.pypi.org/legacy/
InvalidDistribution: Unknown distribution format: ''**

**Comment by merwok** [comment]
`twine upload` needs one or more distribution files as parameter.

**Comment by gbland0725** [comment]
Here is the response for one of the distribution files for twine upload --verbose --repository testpypi.

C:\Users\[redacted]\sphandles>twine upload --verbose --repository testpypi dist/sphandles-0.1.0-py2.py3-none-any.whl
Using configuration from C:\Users\[redacted]/.pypirc
Uploading distributions to https://test.pypi.org/legacy/
  dist/sphandles-0.1.0-py2.py3-none-any.whl (3.9 KB)
Enter your username: __token__
Enter your password:
username: __token__
password: <hidden>
Uploading sphandles-0.1.0-py2.py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████| 9.18k/9.18k [00:00<00:00, 27.8kB/s]
Content received from server:
<html>
 <head>
  <title>403 Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.</title>
 </head>
 <body>
  <h1>403 Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.</h1>
  Access was denied to this resource.<br/><br/>
Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.


 </body>
</html>
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.

**Comment by bhrutledge** [comment]
@gbland0725 Are you absolutely sure that you're using your token for `test.pypi.org`, and not `pypi.org`?

Also, are you including the `pypi-` prefix when you paste it?

**Comment by gbland0725** [comment]
Thanks! I was using pypi.org previously. I created another account for test.pypi.org and generated another api token. Unfortunately, I still get the same issue. Because password is hidden, I can't see what I'm pasting but I am pasting that I normally would on the command prompt which includes the pypi- prefix. I've tried this on Anaconda Prompt and Pycharm Terminal.

**Comment by bhrutledge** [comment]
@gbland0725 I'm stumped. Can you find someone (a friend, colleague, local Meetup, etc.) to share your screen with? I'm optimistic that another pair of eyes would help spot your issue, even if they're not familiar with Python packaging.

**Comment by gbland0725** [comment]
Yes, I will do that. I'll let you know once I fix the problem. If not, I'll close the issue. 
Thank you for your time!

**Comment by gbland0725** [comment]
Looks like control + shift + v did the trick when pasting the password. Thought I tried this but I guess not. Closing issue.
