### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by dsbowen** [pypa/packaging-problems#436]
After running `python3 -m build`, the distribution files didn't include the package. I fixed this by including `packages = find:` under `[options]` in `setup.cfg`. Please consider updating the example `setup.cfg` file in your tutorial if this is a common problem.

Windows 10
python 3.6.8
pip 21.0.1

**Comment by di** [comment]
(cc @henryiii)

**Comment by henryiii** [comment]
This is correct (and present in the setup.py version); I clearly remember writing this, it seems to have been missed, maybe when I split the changes off. I'll add it. Thanks!
