### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by aaronplowther** [pypa/packaging-problems#440]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04

2. What is your Python version?

Python 3.8.5

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

I have been following the instructions on the tutorial given above. I have run into problems when running 
python3 -m build
I am now following the instructions as I am receiving an error. Attached is the output after the build 
[build_error.txt](https://github.com/pypa/packaging-problems/files/5943005/build_error.txt)

command. Thank you in advance for any pointers.

**Comment by henryiii** [comment]
I think this is https://github.com/pypa/packaging-problems/issues/436 which would be fixed by https://github.com/pypa/packaging.python.org/pull/823

**Comment by henryiii** [comment]
Fixed in build 0.3.0! Please reopen if there are still issues.
