### ISSUE TITLE
I have two files I've created, a python library, and an example application that uses that library. I've been all through the instructions, and they do not tell me what to do with my files. In other words, I'm going to be uploading a package that no one will be able to use, because there is no source code. Where do I put my files?

### ISSUE THREAD

**Issue by vegebond** [pypa/packaging-problems#442]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

2. What is your Python version?

3. What version of pip do you have?

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

**Comment by merwok** [comment]
Hello!  Would you mind moving your text from issue title to the message, and answer the questions including showing us the layout of your files and your packaging code?

**Comment by henryiii** [comment]
I think this is the record for the longest title I've seen. 😆 

Assuming your package is called `coolpackage`, you put your library code in `/coolpackage` or `/src/coolpackage`. If you want to make an app that is available when you install your package, then the app code goes there too, and you add an entry-point (a setup.cfg/setup.py option that creates the command line or gui app given a function in your library). If you want your app to only be available directly from the repo, you can put your app in `/app` or `/bin`, maybe `/scripts`.

**Comment by layday** [comment]
I'll close this now but feel free to comment below if the problem persists.
