### ISSUE TITLE
Semver version matchers

### ISSUE THREAD

**Issue by daenney** [pypa/packaging-problems#45]
Rubygems has had this possibility to indicate a required version like so: `~> 1.3.0` which means it will install the latest 1.3.X release but not jump to 1.4.

I was curious if we had something like that or could get that.

**Comment by brainwane** [comment]
Now that PEP 440 has been accepted, is there anything more that needs to happen so we can resolve this?

**Comment by merwok** [comment]
This can be marked as solved!  I use `~=` constraints in my dependencies, then use pip-tools to freeze exact versions.  It works great.

**Comment by brainwane** [comment]
Awesome, thanks!

And just as a plug so y'all see it: [we're currently seeking feedback from package maintainers, including via several IRC livechats/office hours this week](https://wiki.python.org/psf/WarehousePackageMaintainerTesting), about what does or doesn't work for you in the new pypi.org interface, and in the next few weeks we'll be doing so with the wider Python developer community.
