### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by electronhead** [pypa/packaging-problems#451]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

MacOS 11.2.1

2. What is your Python version?

3.9.0

3. What version of pip do you have?

20.2.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

I managed to upload the distribution files, but when I install using pip, the required libraries specified in setup.py are not installed.  On the other hand, when I use the wheel file on another computer, the required libraries are included and the library operates as expected.

Here is a terminal listing...

(venv) [~/dev/testpypi]$ pip install -i https://test.pypi.org/simple/ whendo==0.0.1
Looking in indexes: https://test.pypi.org/simple/
Collecting whendo==0.0.1
  Downloading https://test-files.pythonhosted.org/packages/1d/62/4a390db07025e15d4073f22f86dd4c6fa5e36272c8bb7cb7ec5d49127032/whendo-0.0.1-py3-none-any.whl (29 kB)
Collecting requests
  Downloading https://test-files.pythonhosted.org/packages/6d/00/8ed1b6ea43b10bfe28d08e6af29fd6aa5d8dab5e45ead9394a6268a2d2ec/requests-2.5.4.1-py2.py3-none-any.whl (468 kB)
     |████████████████████████████████| 468 kB 2.9 MB/s 
ERROR: Could not find a version that satisfies the requirement fastapi (from whendo==0.0.1) (from versions: none)
ERROR: No matching distribution found for fastapi (from whendo==0.0.1)

When I first ran twine, I didn't give the __token__ / pypi-..... credentials. I gave my user name and password. So maybe I started off wrong which bolluxed it up. But as you can see, the installation link at https://test.pypi.org/project/whendo/0.0.1/ did download something -- just not all that I expected.

What can I do to successfully upload the distribution files so that when I 'pip install' them, the libraries like fastapi and uvicorn are also included?

Any help would be greatly appreciated.

Thanks.

-- Gary

[setup.pdf](https://github.com/pypa/packaging-problems/files/5993429/setup.pdf)

**Comment by henryiii** [comment]
It's trying to get the install_requires from TestPyPI, and some of them are missing from there.

I would use setup.cfg for most of the contents of your setup.py; it will be a lot cleaner and avoid boilerplate that's easy to get wrong. I'd also drop the test_requires and such, that's been deprecated for years. Also, use find_packages with include= (or better yet, the cfg version) instead of rolling your own function. See https://scikit-hep.org/developer/packaging for an extended example.

**Comment by electronhead** [comment]
Very helpful. I’ll give your suggestions a try.

My setup.py was cobbled together from tutorials and other pip libraries that I use. First real Python project. Both probably obvious to you. Onward!

-- Gary

**Comment by layday** [comment]
I'll close this now but feel free to open a new ticket or comment below if you encounter any more issues.
