### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by yaturner** [pypa/packaging-problems#453]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Raspberry Pi OS (debian) buster
[build_error.txt](https://github.com/pypa/packaging-problems/files/6022722/build_error.txt)

2. What is your Python version?

python 3.7

3. What version of pip do you have?

18.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

created the example shown in tutorial and got the errors shown in attached file, as instructed __init__.py was empty

**Comment by layday** [comment]
Please see https://github.com/pypa/packaging-problems/issues/454#issuecomment-783789920.

**Comment by yaturner** [comment]
thank you for your help, that worked

**Comment by layday** [comment]
The tutorial has been updated to draw attention to `setup.py`.
