### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by SAX10093** [pypa/packaging-problems#458]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

From the tutorial its not clear that only one file, setup.py or setup.cfg, should be created. Both are listed in the tree in the beginning, thats confusing. On top of that, there are syntax errors in the example setup.py, e.g. missing quote in Bug tracker line, missing commas.

**Comment by layday** [comment]
Thank you for the report, see https://github.com/pypa/packaging.python.org/issues/838.

**Comment by layday** [comment]
I think both of these issues were addressed. Thanks again for reporting.
