### ISSUE TITLE
PyPI should render readmes written in Markdown

### ISSUE THREAD

**Issue by hickford** [pypa/packaging-problems#46]
Reproduced from https://bitbucket.org/pypa/pypi/issue/148/support-markdown-for-readmes

---

If you write your readme in Restructured Text, PyPI will render it on your project's page (eg. https://pypi.python.org/pypi/requests ). It should be possible to write your readme in Markdown too. Markdown is a pervasive format used on GitHub and StackOverflow. It shouldn't be necessary to learn a new markup language or rewrite your project's documentation to publish a Python package.

This is common frustration, and the Python community suffers because it's a barrier to publishing packages and writing documentation . Please consider it!
- http://stackoverflow.com/questions/10718767/have-the-same-readme-both-in-markdown-and-restructuredtext
- http://i.imgur.com/7NYlimN.png
- https://coderwall.com/p/qawuyq
  If you write your readme in Restructured Text, PyPI will render it on your project's page (eg. https://pypi.python.org/pypi/requests ). It should be possible to write your readme in Markdown too. Markdown is a pervasive format used on GitHub and StackOverflow. It shouldn't be necessary to learn a new markup language or rewrite your project's documentation to publish a Python package.

This is common frustration, and the Python community suffers because it's a barrier to publishing packages and writing documentation . Please consider it!
- http://stackoverflow.com/questions/10718767/have-the-same-readme-both-in-markdown-and-restructuredtext
- http://i.imgur.com/7NYlimN.png
- https://coderwall.com/p/qawuyq

**Comment by bukzor** [comment]
As of 2014-12-08, pypi seems to have some markdown support: bitbucket.org/pypa/pypi/pull-request/33

**Comment by karolyi** [comment]
+1

**Comment by xapple** [comment]
+1

**Comment by geezhawk** [comment]
+1 man writing rst is annoying

**Comment by pylover** [comment]
+1

**Comment by ekohl** [comment]
It would appear https://github.com/pypa/readme_renderer/pull/3 is the latest effort.

**Comment by pylover** [comment]
Interesting

**Comment by msabramo** [comment]
I think the next step is to get https://github.com/pypa/python-packaging-user-guide/pull/258 reviewed.

**Comment by AnaPana** [comment]
+1

**Comment by glenjamin** [comment]
Is this feature now fully merged? I tried to piece together how to make it work today, but my README ends up as plain text still.

**Comment by brainwane** [comment]
@glenjamin Sorry, no, not yet! @di is working on the checklist in https://github.com/pypa/warehouse/issues/869#issuecomment-340928703 . Specifically, at the moment, he's working to update `pkginfo`. Then the next thing to fix will be `twine` and then Warehouse.

**Comment by sayanarijit** [comment]
Hi All

Why don't we just use client side JavaScript to automatically detect the format and render it?

There are plenty of detectors or render tools like [markup](https://github.com/github/markup), [gfm](https://github.github.com/gfm) than are capable enough to handle it all at client side.

This way I believe there is no need to change any algorithm at the back-end.

**Comment by merwok** [comment]
I would be great if the new PyPI ket being functional without requiring javascript.

**Comment by ewdurbin** [comment]
Accepted [PEP 566 Description-Content-Type](https://www.python.org/dev/peps/pep-0566/#description-content-type-optional) removes the need for trying to detect the format.

Once implemented, The renderer for PyPI (https://github.com/pypa/readme_renderer) will be able to add explicit renders for various markup syntaxes. This is the correct solution and doesn't require JavaScript or other fragile hacks.

Right now most of the maintainers/contributors are working on completing the final/production rollout and switchover to https://github.com/pypa/warehouse, but I believe some progress is being made towards implementation of PEP 566 overall.

**Comment by brainwane** [comment]
Yeah, @di has been making great progress on implementing PEP 566 in relevant tools -- https://github.com/pypa/warehouse/issues/869#issuecomment-340928703 is a good checklist to follow and he's updating it as maintainers merge and release his improvements.

There's now [a release candidate for the next version of Twine available](https://pypi.org/project/twine/1.11.0rc1/) and it includes PEP 566 compliance. (Witness [my test project](https://test.pypi.org/project/Forms990-analysis/1.0.5.dev1/)!) Feel free to use it as you test other Markdown-related packaging ecosystem stuff.

**Comment by ncoghlan** [comment]
Given https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi, I'm going to go ahead and close this. Even though it will take a while for all the related updates to ripple out through the ecosystem, it now works with latest PyPI, setuptools, and twine combo :)

**Comment by hickford** [comment]
Great news, thank for sharing! To clarify, Markdown readme detection isn't automatic: you need to follow the instructions for and reupload your project.

Thanks to all involved.

**Comment by msabramo** [comment]
I was very happy to see that this happened! Fantastic! Thank you everyone who worked on this and the new PyPI!
