### ISSUE TITLE
Trouble following packaging libraries tutorial - project files omitted while running `python -m build`

### ISSUE THREAD

**Issue by vardecab** [pypa/packaging-problems#461]
**Hello! It's my first time distributing a Python module (or at least trying to do that...) and I'd appreciate any help in troubleshooting the mistake.**

1. What is your operating system and version?

Windows 10 20H2

2. What is your Python version?

Python 3.7.4

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

[Packaging Python Projects](https://packaging.python.org/tutorials/packaging-projects/#packaging-your-project)

5. Could you describe your issue in as much detail as possible?

### Problem 
**I was following [the guide](https://packaging.python.org/tutorials/packaging-projects/#packaging-python-projects) on how to distribute a Python module and looks like I made a mistake while building the project because my project files are not being added to the package/archive.**

### What I did
I _didn't_ create `setup.py` file because the guide says:
>This file used to be required, but can be omitted in modern setuptools.

I set up `setup.cfg` file: 
```[metadata]
name = win10toast-click
version = 0.1.2
author = vardecab
author_email = 
description = An easy-to-use Python library for displaying Windows 10 Toast Notifications. Improved version of win10toast and win10toast-persist to include callback_on_click to run a function on notification click, for example to open a URL.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/vardecab/win10toast-click
project_urls =
    Bug Tracker = https://github.com/vardecab/win10toast-click/issues
classifiers =
    Development Status :: 5 - Production/Stable
    Topic :: Utilities
    Programming Language :: Python :: 3
    Operating System :: Microsoft
    Environment :: Win32 (MS Windows)
    Operating System :: Microsoft :: Windows :: Windows 10
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)

[options]
python_requires = >=3.7
[bdist_wheel]
universal=1
```

Then `requirements.txt`:
```
pypiwin32
setuptools
```

Then copy-pasted `pyproject.toml` from the guide: 
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

I have a file structure recommended in the guide, ie.: 
![Code_O0WRmcDPYa](https://user-images.githubusercontent.com/6877391/109398645-6d15a380-793e-11eb-9044-785ea653ac7a.png)
but when I run `python -m build` it looks like only those config files are being added and project folder `win10toast-click` is being omitted. 
![explorer_KSrq0tTdYB](https://user-images.githubusercontent.com/6877391/109398705-a2ba8c80-793e-11eb-9d82-33e49853ede1.png)

### Question
**How to add project files**
![Code_mWcsMG33Nx](https://user-images.githubusercontent.com/6877391/109398747-00e76f80-793f-11eb-916a-323ca6d4452b.png)
**to the package?**

**Comment by layday** [comment]
You are missing `packages = find:` under `[options]` in your `setup.cfg`.  Python module and package names must also not contain dashes; `win10toast-click` should be `win10toast_click`.

**Comment by henryiii** [comment]
(Capitalization and dashes vs. spaces are ignored on PyPI, so you’ll still be able to install it using the dashed name if you want to)

**Comment by vardecab** [comment]
Thank you both! 

Changing `-` to `_` helped. I was able to build, upload to TestPyPI and then install from TestPyPI but my `data` folder with `python.ico` is being omitted. 
![Code_m5FNjvLbn7](https://user-images.githubusercontent.com/6877391/109420360-43a65780-79d2-11eb-8621-4af1d6b98d6b.png)
Any ideas why? Should I add something to the `setup.cfg` file?

**Comment by layday** [comment]
Yes, please see: https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html#including-data-files.

**Comment by vardecab** [comment]
That's a good lead, thank you, however adding `include_package_data = True` didn't help and neither did creating a more complicated project structure with `src` folder etc. that I found [here](https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html).

`icon/python.ico` (or `data/python.ico` as it was called before) is not being included. I tried to put `python.ico` directly in one folder with `__init__.py` but that didn't work either.

I didn't change anything in neither `pyproject.toml` nor `requirements.txt` (comparing to my first post at the top) and my `setup.cfg` file looks like this now: 
```
[metadata]
name = win10toast-click
version = 1.0.2
author = vardecab
author_email = 
description = An easy-to-use Python library for displaying Windows 10 Toast Notifications. Improved version of win10toast and win10toast-persist to include callback_on_click to run a function on notification click, for example to open a URL.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/vardecab/win10toast-click
project_urls =
    Bug Tracker = https://github.com/vardecab/win10toast-click/issues
classifiers =
    Development Status :: 5 - Production/Stable
    Topic :: Utilities
    Programming Language :: Python :: 3
    Operating System :: Microsoft
    Environment :: Win32 (MS Windows)
    Operating System :: Microsoft :: Windows :: Windows 10
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
[options]
python_requires = >=3.7
packages = find:
include_package_data = True
[bdist_wheel]
universal=1
```
And that's the project structure: 
![Code_sAsAvbW5Qd](https://user-images.githubusercontent.com/6877391/109425892-e10d8580-79ea-11eb-8057-ed35b10e7e96.png)

Is there anything else I should modify?

**Comment by layday** [comment]
Yes, create a `MANIFEST.in` in the same folder as `setup.cfg`, containing:
```

**Comment by vardecab** [comment]
Fixed! Many hours later [it's now available on PyPI](https://pypi.org/project/win10toast-click/). Thank you @layday for all your support!
