### ISSUE TITLE
Trouble with package version

### ISSUE THREAD

**Issue by temuller** [pypa/packaging-problems#466]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

`Ubuntu 18.04.` 

2. What is your Python version?

`3.6`

3. What version of pip do you have?

`20.2.2`

5. Could you describe your issue in as much detail as possible?

I am trying to build my own package, but whenever I do it, it seems to build a developer version `[package]-0.1.dev278+gd9260df`, so when I try to upload the package to testpypi it gives me this error: `HTTPError: 400 Bad Request from https://test.pypi.org/legacy/ '0.1.dev278+gd9260df' is an invalid value for Version.`

I have been working on this package for a while so I initially installed it with `python setup.py develop`

Thanks!

**Comment by henryiii** [comment]
You are using setuptools-scm. It picks up git tags. You should tag in git with `v0.2.0` (or whatever you want to call it), and then release. Make sure the working fir is clean. Or set SETUPTOOLS_SCM_PRETEND_VERSION, if I remember correctly. But in that case you aren't really taking advantage of setuptools-scm.

**Comment by temuller** [comment]
Thanks! That was precisely the issue :)
