### ISSUE TITLE
ERROR Backend while build

### ISSUE THREAD

**Issue by ipungg-junior** [pypa/packaging-problems#469]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.
1. What is your operating system and version?

_Ubuntu 18.04_

2. What is your Python version?

_Python 3.8.5_

3. What version of pip do you have?

_pip 20.0.2_

5. Could you describe your issue in as much detail as possible?

```
Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
Collecting selenium
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting urllib3
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Installing collected packages: urllib3, selenium
Successfully installed selenium-3.141.0 urllib3-1.26.4
ERROR Backend 'setuptools.build_meta:__legacy__' is not available.
```

**Comment by layday** [comment]
It looks like you've put your runtime depedencies where your build dependencies ought to be.  If you're following the packaging tutorial, ensure that your `pyproject.toml` containts exactly:

```toml
[build-system]
requires = [
    "setuptools >=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

You can declare runtime dependencies in `setup.cfg`.  Underneath the `[options]' section, add:

```
install_requires =
    selenium
```

**Comment by layday** [comment]
I'll close this now but feel free to comment below if the problem persists.
