### ISSUE TITLE
PyPI package pages should have clear "pip install" instructions near top of page

### ISSUE THREAD

**Issue by hickford** [pypa/packaging-problems#47]
Reproduced from https://bitbucket.org/pypa/pypi/issue/149/package-pages-should-have-clear-pip 

---

Take a look at any package page on the Ruby gems website (eg.  https://rubygems.org/gems/rails ).  At the top of the page, it has the installation instructions in large friendly letters (eg. `gem install rails`). Similarly, on any Nodejs package page (eg. https://www.npmjs.org/package/express ) the installation instructions are near the top and very clear (eg. `npm install express`)

However, browse to a package page on Python's package index PyPI (eg. https://pypi.python.org/pypi/lxml/3.3.5 ) and there's no installation instructions at all! There should be clear instructions at the top of the page (eg. `pip install lxml`. Pip is the Python package manager and the easiest way to install packages.). 

Don't underestimate the importance of clear instructions. They would be extremely helpful, particularly to new users. There's a huge amount of confusion about how to install Python packages, as evidenced by popular search queries and StackOverflow questions. This is the long shadow of Python's history of shipping without a package manager.

Now Python (from version 3.4) ships with the package manager Pip, packages can be installed easily, but **users need to be educated how**. 

If you doubt the problem, observe that a number of high-ranking web pages encourage the use of the obsolete and lacking `easy_install` script. And that the deprecated packaging library `distribute` still receives upwards of a million downloads per month. The confusion around packages is a real barrier to new users learning Python.

---

I'd argue that the current content of PyPI package pages is actually counter-helpful. See, for example https://pypi.python.org/pypi/Jinja2 . There's no instruction to `pip install` the package (agreed to be best way to install packages). There's no instructions at all. The user's eyes light instead on the download link at the bottom page. This saves a `.tar.gz` file. For many Windows users, extracting this archive is challenge enough (remember, we recommend Python to people who've never programmed before). After that, it's still not obvious. The most reasonable action is to double-click  `setup.py` but that just opens a command line window that dissappears again. What to do? The persevering user might go search the web and deduce to run `python setup.py install`, but some will give up before that. Perhaps they'll write their software in javascript. 

The easiest way to install the package would have been `pip install`, but the PyPI page never mentioned it, and instead pointed the user download another more difficult path.

**Comment by hickford** [comment]
http://stackoverflow.com/q/21222114/284795

> I downloaded it from: https://pypi.python.org/pypi/requests and now I have a .whl file. I've got Python 2.7 and 3.3 on Windows, so how do I install it so all the other Python scripts I run can use it?

**Comment by hickford** [comment]
> To speak to the confusion, I didn't realize until today that pip could download from pypi - I always used it from the install directory of a tarball.

https://bitbucket.org/pypa/pypi/issues/149/package-pages-should-have-clear-pip#comment-21878779

**Comment by daenney** [comment]
I'm not entirely sure how people miss that pip can install directly from pypi. Most projects have a `pip install $projectname` as part of their instructions which should at least hint at the fact that it fetches that project from somewhere itself.

**Comment by brainwane** [comment]
Thanks to everyone suggesting and discussing this!

The new PyPI does indeed include a prominent `pip install` direction at the top of a project page -- [example](https://pypi.org/project/arrow/). (One user has pointed out in pypa/warehouse#3006 that we need to be wary of situations where `pip install` will not Just Work. But that's another issue.)

Warehouse, the codebase behind the new PyPI, is available as a pre-production site at https://pypi.org, [we're making steady progress on the developer roadmap](https://wiki.python.org/psf/WarehouseRoadmap) thanks to [funding from Mozilla's Open Source Support Program](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and it's on its way to replacing the legacy PyPI site this year. [We're currently seeking feedback from package maintainers, including via several IRC livechats/office hours this week](https://wiki.python.org/psf/WarehousePackageMaintainerTesting), about what does or doesn't work for you in the new interface, and in the next few weeks we'll be doing so with the wider Python developer community.

I'm going to leave this issue open till we actually flip the switch and start redirecting people from pypi.python.org to pypi.org.

**Comment by hickford** [comment]
@brainwane Thanks for the links. The example looks good. One idea for improvement: [Npm package pages](https://www.npmjs.com/package/express) have a "how? learn more" link by the installation command.  I think PyPI pages would be even clearer with a similar link, perhaps to https://packaging.python.org/tutorials/installing-packages/#installing-from-pypi

**Comment by brainwane** [comment]
I'm now going to close this issue since each package as displayed in Warehouse does include a `pip install` instruction at the top of the page. If people would like to add further suggestions for improving that aspect of the in-page instructions, I think https://github.com/pypa/warehouse/issues/3006 and https://github.com/pypa/warehouse/issues/1563 would be good places to add those suggestions. Thanks!
