### ISSUE TITLE
Uploading to pip .cfg file only uploads metadata

### ISSUE THREAD

**Issue by adamoppenheimer** [pypa/packaging-problems#479]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

MacOS 10.15.7

2. What is your Python version?

Python 3.7.9

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

I am working on a Python package for handling data for two way fixed effect labor models. The repository is at https://github.com/tlamadon/bipartitepandas. I was previously working on another package, pytwoway (https://github.com/tlamadon/pytwoway) and used setup.py. However, the page for uploading to pip has updated to recommend using setup.cfg instead. I wrote the exact same file as I had for pytwoway except this time in bipartitepandas using the .cfg format and added a pyproject.toml file. Except when I used the .cfg format, only the metadata for bipartitepandas was uploading to pip so when I would install it and use it in ipython, it would say the package couldn't be found. Eventually I just converted back to the .py format and it worked for the new package (I was going to change pytwoway to use .cfg as well but just left it the same since it seems that .cfg doesn't work). Obviously I found a workaround but I thought it would help you to know about this potential bug. Please let me know if you can use any more information. The files are included below.

Here are the files:
setup.cfg:
```
[metadata]
name = bipartitepandas
version = 0.0.4
author = Thibaut Lamadon
author_email = thibaut.lamadon@gmail.com
description = Python tools for bipartite labor data
long_description = file: README.rst
long_description_content_type = text/x-rst
url = https://github.com/tlamadon/bipartitepandas
project_urls =
    Documentation = https://tlamadon.github.io/bipartitepandas/
    GitHub = https://github.com/tlamadon/bipartitepandas
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = bipartitepandas
packages = find:
python_requires = >=3.6
install_requires =
    numpy
    numpy_groupies
    pandas
    scipy
    scikit-learn
    networkx
    tqdm

[options.packages.find]
where = bipartitepandas
```

setup.py:
```
import setuptools

with open('README.rst', 'r', encoding='utf-8') as fh:
    long_description = fh.read()

setuptools.setup(
    name='bipartitepandas',
    version='0.0.5',
    author='Thibaut Lamadon',
    author_email='thibaut.lamadon@gmail.com',
    description='Python tools for bipartite labor data',
    long_description=long_description,
    long_description_content_type='text/x-rst',
    url='https://github.com/tlamadon/bipartitepandas',
    packages=setuptools.find_packages(),
    install_requires=[
        'numpy',
        'numpy_groupies',
        'pandas',
        'scipy',
        'scikit-learn',
        'networkx',
        'tqdm'
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)
```

pyproject.toml:
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

**Comment by layday** [comment]
The issue is that you have:

```cfg
[options]
package_dir =
    = bipartitepandas

[...]

[options.packages.find]
where = bipartitepandas
```

Both of these options are telling setuptools to look for packages _inside_ the `bipartitepandas` folder.  If you're not using a `src`-based layout, you can omit them.  This stuff is really opaque - can't fault anyone for getting it wrong.

**Comment by KOLANICH** [comment]
BTW, there exist semi-automatic convertors from setup.py to setup.cfg

**Comment by adamoppenheimer** [comment]
Thank you, I removed those lines and it works now.
