### ISSUE TITLE
Proposal: separate support requests into a separate bug tracker

### ISSUE THREAD

**Issue by KOLANICH** [pypa/packaging-problems#480]
I have subscribed to this repo in order not to miss an important discussion about python packaging ecosystem. But instead I get lot of support requests from people who haven't read the manual carefully enough. Should these support requests be separated into a dedicated bug tracker?

**Comment by merwok** [comment]
This is the project for packaging problems, it’s not meant or used for packaging specs discussion at all.

**Comment by KOLANICH** [comment]
Though there were some, so I subscribed here. And yes, if one has to design a new spec, that means that there exist a problem it is meant to solve.

**Comment by pradyunsg** [comment]
discuss.python.org is where discussions regarding new specifications would take place. There's no plans to have discussions here about them anymore.
