### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by csmolen6136** [pypa/packaging-problems#482]
1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.7.6

3. What version of pip do you have?
pip 20.0.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

Running python -m build resulted in the following error:
```
Uninstalling setuptools-41.2.0:
  Successfully uninstalled setuptools-41.2.0
←[91mERROR←[0m Backend 'setuptools.build_meta' is not available.
```

**Comment by henryiii** [comment]
The minimum I would put would be:

```yaml
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
```

Setuptools before 42 doesn't work properly with this system, and you usually need wheel.
