### ISSUE TITLE
Local module works, but packaged version doesn't. Why?

### ISSUE THREAD

**Issue by viktak** [pypa/packaging-problems#483]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Linux havm 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux in an Oracle VM VirtualBox on a Windows 10 Pro 64 host

2. What is your Python version?
Python 3.7.3

3. What version of pip do you have?
pip 21.0.1 from /home/dev/.local/lib/python3.7/site-packages/pip (python 3.7)

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
[https://packaging.python.org/tutorials/packaging-projects](https://packaging.python.org/tutorials/packaging-projects)

5. Could you describe your issue in as much detail as possible?
I am a python beginner. I developed a basic module, [ows2json](https://test.pypi.org/project/owm2json/).
I also wrote a small client that tests its functionality, it's very basic like this:
```
import json
import requests

import owm2json

apinames = ["air_pollution", "onecall", "roadrisk"]
lat = 37
lon = 23
appid = "secret"

myOWM = owm2json.owmRequestor(apinames, lat, lon, appid)

print(myOWM.GetData())
```

The client works fine when the module (`owm2json.py`) is in the same directory.

I created and uploaded a package to [https://test.pypi.org/](https://test.pypi.org/) (going through all the steps on [this page](https://packaging.python.org/tutorials/packaging-projects))

I installed the package with this command:
```
pip install -i https://test.pypi.org/simple/ owm2json
```
Finally I removed the local module from the working directory (so that my client wouldn't use that).

So far without an error anywhere, I can even see the correct version installed using `pip list`.

However, when I run `python client.py` it doesn't seem to find the module, I get this error message instead:
```
dev@havm:~$ python ./python/client.py
Traceback (most recent call last):
  File "./python/client.py", line 11, in <module>
    myOWM = owm2json.owmRequestor(apinames, lat, lon, appid)
AttributeError: module 'owm2json' has no attribute 'owmRequestor'
```

Investigating it further, I found that at the python prompt (after importing the module, which seems to happen without a problem), when I issue `dir (owm2json)`, I get the following result:
```
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```
I think this explains why I don't get to the function I want. I just don't know why...

Any idea what I overlooked?

Thanks in advance for any pointers!!

**Comment by merwok** [comment]
Hello!

How is your code laid out?
Is `owm2json` a package with `ownRequestor` a sub-module or sub-package?

**Comment by viktak** [comment]
Hi there!

It's a simple class in a single file. The class is called `owmRequestor`. It has only 2 functions: `__init__` and `GetData`.
I'm not sure what you mean by sub-module/sub-package... I'm a beginner @ Python...

**Comment by layday** [comment]
The packaging tutorial assumes that your project is laid out as a package; however `src/owm2json/__init__.py` is empty.  If the code is located in a `owm2json.py`, you need to move it into `src/owm2json/__init__.py`.

**Comment by layday** [comment]
Keep in mind that you can inspect the built distributions by unzipping them. Wheel files are simple zip files with a `.whl` extension. With your setup, whe wheel file is what pip will download and install from PyPI.

**Comment by merwok** [comment]
Module is something you can import.  It can be one file (`import thing` → `thing.py`) or multiple files (`import package.module` → `package/__init__.py` and `package/module.py`).

I looked at own2json on TestPyPI.  You wrote it as a package, without any code in the `__init__` submodule (that’s the module that’s imported when the package is imported), so that’s why `ownRequestor` is not found.  The easiest thing is to have a single module when you start, or if you know you’re going to want multiple modules, then you can have a package.

I wonder if maybe you have expectations from other languages.  In Python, you don’t have to use one module per class; modules in a package are not automatically imported; you don’t even have to have classes!  So when you said that you have a class named `ownRequestor`, do you mean that you have a module `own2json.ownRequestor` that contains that class?

Can you also share your packaging config (setup.py and/or setup.cfg and/or pyproject.toml)?

**Comment by viktak** [comment]
@merwok @layday 
Wow guys, you are incredible - a lot of good info, thank you so much!!!

First of all, this is my `setup.cfg`:
```
[metadata]
name = owm2json
version = 0.1.5
author = @viktak
author_email = owm2json@viktak.com
description = Python module for getting several of OpenWeatherMap API at once
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/viktak/owm2json
project_urls =
    Bug Tracker = https://github.com/viktak/owm2json/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.7

[options.packages.find]
where = src
```
I have no `setup.py`.

This is my `pyproject.toml`:
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```
The contents I got from the tutorial.

And, for completeness, this is my (I think) module:
```
import json
import requests


class owmRequestor:

    def __init__(self, apinames, lat, lon, appid):
        #   Init variables
        self.apinames = apinames
        self.lat = lat
        self.lon = lon
        self.appid = appid
        self.data = "{"



    def GetData(self):
        #   Call each OpenWeatherMap API in the list
        #   and build a JSON object containing all the results 
        for apiname in self.apinames:
            self.data += "\"" + apiname + "\":"
            self.data += requests.get(f"https://api.openweathermap.org/data/2.5/{apiname}?lat={self.lat}&lon={self.lon}&appid={self.appid}").text
            self.data += ","
        
        #   Remove the last comma ","
        self.data = self.data[:-1]  

        #   Finish JSON object
        self.data += "}"

        #   Return JSON object containing all the result
        return (json.loads(self.data))
```

**Comment by viktak** [comment]
@merwok:
> do you mean that you have a module own2json.ownRequestor that contains that class?

At this stage (of my Python journey) I'm not clear on the difference between packages/modules... However, I do think `owmRequestor` is a class, because of the word `class` in front of it. :) Or I totally misunderstand things.
To summarize my understanding: `owm2json` is a module and `owmRequestor` is a class in it. Is this not correct? If not, I'll go back to basics :) feel free to suggest resource to look at - I really want to understand this once and for all.

>  The easiest thing is to have a single module when you start

Couldn't agree more! I was going for that - just lost my way...

@layday 
> however src/owm2json/__init__.py is empty

What would I need to put in this file? I did notice that it was empty, but I could find any info on it..

**Comment by viktak** [comment]
> 
> 
> The packaging tutorial assumes that your project is laid out as a package; however `src/owm2json/__init__.py` is empty. If the code is located in a `owm2json.py`, you need to move it into `src/owm2json/__init__.py`.

I just tried moving my code from `owm2json.py` to `__init__.py` as you suggested, built, uploaded (v0.1.6), installed, and now it is working as expected.

Thank you @merwok , @layday !!! 

ps: Still, if you could point me to the right resources as I asked above, it would be great. :)

**Comment by layday** [comment]
1. Simply create a module `src/owm2json/foo.py` containing a symbol, e.g. a class, `bar` which
  you can import in `__init__.py` with `from .foo import bar`; or to import the entire module
  wholesale: `from . import foo`.
2. Create a virtual environment for development (see https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments)
  and perform an editable install of your package with pip: `pip intall -e .`.  This will expose your package
  to your client script while keeping changes in sync.

**Comment by viktak** [comment]
@layday Awesome, thank you!!
