### ISSUE TITLE
Trouble following packaging libraries tutorial: build fails inside virtualenv, missing License and Requires info for pip

### ISSUE THREAD

**Issue by sebkraemer** [pypa/packaging-problems#488]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

MacOS Catalina 10.15.7

2. What is your Python version?

Python 3.8.2

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

There are two issues.

The first problem: I was applying the packaging tutorial at https://packaging.python.org/tutorials/packaging-projects/ for my existing python project at https://github.com/sebkraemer/FinTsUml/

```
(fints_uml) sebi@macbook2019-ske FinTsUml % python3 -m build
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sebi/.virtualenvs/fints_uml/lib/python3.8/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/Users/sebi/.virtualenvs/fints_uml/lib/python3.8/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/Users/sebi/.virtualenvs/fints_uml/lib/python3.8/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/Users/sebi/.virtualenvs/fints_uml/lib/python3.8/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/Users/sebi/.virtualenvs/fints_uml/lib/python3.8/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/Users/sebi/.virtualenvs/fints_uml/lib/python3.8/site-packages/build/env.py", line 199, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True).create(path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 289, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/var/folders/r_/tn7hk_md1vj851lfjr5mfczc0000gq/T/build-env-li8kr87s/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

The problem arose when running the build step. Note that I'm running it from within a virtualenv. python binary lookup resolves as follows:

```
(fints_uml) sebi@macbook2019-ske FinTsUml % ls -l `which python3`
lrwxr-xr-x  1 sebi  staff  6 22 Mar 21:52 /Users/sebi/.virtualenvs/fints_uml/bin/python3 -> python
(fints_uml) sebi@macbook2019-ske FinTsUml % which python
python: aliased to /usr/local/bin/python3
```

The problem disappears when I run the build step from outside the virtualenv!

The second problem is that:
- the package shows as having UKNOWN license when pip is asked
- pip also does not show the `requests` dependency (and it is not pulled when installing into a fresh virtualenv).

```
% pip show fints_uml
Name: fints-uml
Version: 0.1
Summary: A FinTS log file UML visualizer
Home-page: https://github.com/sebkraemer/FinTsUml
Author: Sebastian Krämer
Author-email: sebkraemer@posteo.org
License: UNKNOWN
Location: /Users/sebi/.virtualenvs/fts2/lib/python3.8/site-packages
Requires: 
Required-by: 
```

As far as I understood from the tutorial, the dependency should have been found automatically by examining the import inside the project code.

Any help or pointers are appreciated!

**Comment by henryiii** [comment]
For problem 2: You do need to list `install_requires`, you can't tell exactly what is needed by looking at the code. Imports and names may not match, min versions matter, etc.

**Comment by merwok** [comment]
The `License` field is a free-form text file meant to be used when there is no suitable existing `Classifier` for your license.  Your config is fine!

> the dependency should have been found automatically by examining the import inside the project code

Some tools try that, but it’s hard and fragile.  I don’t think setuptools does that!
I find a note about `dependencies` in the page you linked, and none about `install_requires`.
Can you link to the exact section that mislead you to believe this?

**Comment by sebkraemer** [comment]
> The `License` field is a free-form text file meant to be used when there is no suitable existing `Classifier` for your license. Your config is fine!

OK thanks.

> > the dependency should have been found automatically by examining the import inside the project code
> 
> Some tools try that, but it’s hard and fragile. I don’t think setuptools does that!
> I find a note about `dependencies` in the page you linked, and none about `install_requires`.
> Can you link to the exact section that mislead you to believe this?

I believe this one:

> packages is a list of all Python import packages that should be included in the Distribution Package. Instead of listing each package manually, we can use the find: directive to automatically discover all packages and subpackages and options.packages.find to specify the package_dir to use.

I'm not so familiar with python nomenclature yet, so I probably thought "list of all Python import packages"  and "find:" would find the packages that my package does import. Now I see it will figure out my "fints_uml" module name. Since it's such a simple project, I'll just list the dependencies myself then.

As for the tutorial, I believe the aspect of how to specify these or use `install_requires` would be helpful, since even simple modules will import something more than python-shipped modules.

Regarding the build error, I guess it's something I have to bring to the virtualenv project, right?

**Comment by layday** [comment]
> Regarding the build error, I guess it's something I have to bring to the virtualenv project, right?

Please see https://github.com/pypa/packaging-problems/issues/493#issuecomment-818325582.

**Comment by sebkraemer** [comment]
@layday , thanks for the notification! I replied in the linked issue, the provided solution works for me.

Closing this issue, thanks to everybody! 👏
