### ISSUE TITLE
Running various setup.py's is awkward compared to using one familiar and trusty package manager

### ISSUE THREAD

**Issue by hickford** [pypa/packaging-problems#49]
Reproduced from http://stackoverflow.com/a/23998536/284795

To install a Python package you've downloaded, you extract the archive and run the setup.py script inside:

```
python setup.py install
```

To me, this has always felt odd. It would be more natural to point a package manager at the download, as one would do in Ruby and Nodejs, eg. `gem install rails-4.1.1.gem`

A package manager is more comfortable too, because it's familiar and reliable. On the other hand, each `setup.py` is novel, because it's specific to the package. It demands faith in convention "I trust this setup.py takes the same commands as others I have used in the past". That's a regrettable tax on mental willpower. 

I'm not saying the setup.py workflow is less secure than a package manager (I understand Pip just runs the setup.py inside), but certainly I feel it's awkard and jarring. There's a harmony to commands all being to the same package manager application. You might even grow fond it.

**Comment by embray** [comment]
I think there should be a documentation change here if ever it's feasible to do so.  I was just explaining this to some coworkers.  For over a decade we've been telling everyone `python setup.py install` is the correct way to install a Python package.  Now we really want to be telling people `pip install distname/source-dist/wheel/cwd/etc.` for all Python package installation (unless you are a system packager or developer or the like--just as those are the only people who should generally ever be running `make install`).

But I agree that without ensurepip on 2.7 we're still stuck with it...

**Comment by dstufft** [comment]
Good news, 2.7.9 includes ensurepip :)

**Comment by daenney** [comment]
:dancers:

**Comment by embray** [comment]
Nice!  I've been out of the loop so I missed that.  Now all the more reason to remind my coworkers to not run `setup.py install`...  (.egg installations tend to only cause confusion anyways)

**Comment by brainwane** [comment]
@hickford thanks for filing this issue! Now that [the official packaging documentation tells people to use `pip`](https://packaging.python.org/tutorials/installing-packages/#use-pip-for-installing), shall we close it, or is there another aspect to this that I haven't considered?

**Comment by ncoghlan** [comment]
Nope, just a lack of issue backlog grooming as things have changed over the past few years.

@brainwane, thanks for reviewing all these and prompting me/us to clear them up where appropriate :)

**Comment by hickford** [comment]
> Now that the official packaging documentation tells people to use pip 

Brilliant! The documentation consistently advises `pip install` for local and remote sources, that's what I wanted. Thanks.
