### ISSUE TITLE
Feature Request: There should be an ability to distribute a pip library to a certain platform rather than all the platforms?

### ISSUE THREAD

**Issue by jazilzaim** [pypa/packaging-problems#495]
**What's the problem this feature will solve?**

Not sure if this exists yet, but I am trying to build a way to enable select platforms to install pip libraries. NPM and Swift Package Manager (SPM) already enables this. I am not sure if this is possible.

**Describe the solution you'd like**

There should be a way to build a pip package for a certain amount of platforms. Let's say if I wanted to distribute my pip package only to Linux, there should be a way just like you can with NPM and other package managers.

It could enable developers to write platform-specific dependencies. It would enable a solid integration for the developer. This would give more options to a Python developer as well.

**Alternative Solutions**

Not exactly.

**Additional context**

**Comment by jazilzaim** [comment]
oh. So if I was to use wheels and let's say if I target Mac, Windows and Linux users won't be able to download my pip package?

**Comment by matthewfeickert** [comment]
@jazilzaim (I'm just a person on the internet, not part of the PyPA so take this endorsement with this in mind) I think you might want to check out the awesome [`cibuildwheel` project](https://cibuildwheel.readthedocs.io/en/stable/) &mdash; it makes is amazingly easy to build wheels for many platforms (c.f. [examples of projects using it now](https://cibuildwheel.readthedocs.io/en/stable/working-examples/)).

**Comment by uranusjr** [comment]
> say if I target Mac, Windows and Linux users won't be able to download my pip package?

Pretty much. As long as you build your wheel with a platform-specific tag (something like `py3-none-macosx_10_9_x86_64`), pip will not try to install it on Windows or Linux.

**Comment by jazilzaim** [comment]
Oh I see. Thank you for all the help!
