### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Satstef** [pypa/packaging-problems#497]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

`MacOS Big Sur (11.2.3)`

2. What is your Python version?

`Python 3.8.2`

3. What version of pip do you have?

`pip3 version 19.2.3`

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

5. Could you describe your issue in as much detail as possible?

This is first time I'm using build. 
First I installed it in my virtualenv (using pip3).
I was in the same directory with pyproject.toml, and run 
`python3 -m build`(keeping my virtualenv activated)

The following Traceback I got:

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/satya/Desktop/INFORMATICA/applicazioni/app_SingSong/venv/lib/python3.8/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/Users/satya/Desktop/INFORMATICA/applicazioni/app_SingSong/venv/lib/python3.8/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/Users/satya/Desktop/INFORMATICA/applicazioni/app_SingSong/venv/lib/python3.8/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/Users/satya/Desktop/INFORMATICA/applicazioni/app_SingSong/venv/lib/python3.8/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/Users/satya/Desktop/INFORMATICA/applicazioni/app_SingSong/venv/lib/python3.8/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/Users/satya/Desktop/INFORMATICA/applicazioni/app_SingSong/venv/lib/python3.8/site-packages/build/env.py", line 199, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True).create(path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 289, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/var/folders/cy/lyx9fn2d5ms1k1vkmggxltf40000gn/T/build-env-qlnrlemd/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

This is my pyproject.toml file:
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

**Comment by Satstef** [comment]
My packaging files are: 

- pyproject.toml which already I put up;
- setupp.cfg
```
[metadata]
name = SingSong
version = 0.0.1
author = Satstef
author_email = singsong@gmail.com
description = A way to store and listen to your music
long_description = file: README.md
long_description_content_type = markdown
url =
project_urls =

classifiers =
    Programming Language :: Python :: 3.8
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Framework :: Flask

[options]
package_dir =
    = app_SingSong
packages = find:
python_requires = >=3.6

[options.packages.find]
where = app_SingSong
```

- README.md
- MANIFEST.in
```
include SingSong/Database/schema.sql
graft SingSong/static
graft SingSong/templates
global-exclude *.pyc
```

- LICENSE (MIT)

**App structure**
app_SingSong folder is the root and contains:

- packaging files;
- virtualenv folder
- config.py
- application folder named `SingSong` (this folder contains `__init__.py`)

**Comment by layday** [comment]
This is a known issue with the Python version from the macOS command line tools. Please install build with the virtualenv extra (`build[virtualenv]`) and try again.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by henryiii** [comment]
The latest master should also work, `pip install "build @ git+https://github.com/pypa/build.git"` - if you could test that _before_ installing virtualenv (or uninstall virtualenv), that would reassure us that it's working before release. :)

**Comment by mlastIDBS** [comment]
I had the same issue and `python3 -m build -n` worked, although I had to then upgrade setuptools and install wheel.

**Comment by Satstef** [comment]
Hello everyone and thanks for sharing and helping.

**The @henryiii solution:**
I installed it with activated virtualenv and is working. It create the expected files and directories.
I installed it with deactivated virtualenv (hoping that's what you were asking to test) and installation works. 

**The @layday solution:**
I'm sorry, I was not able to try that because I cannot use virtualenv extra. I went trough this to better understand:
https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#installing-extras
but I could not do that. I also found:
https://virtualenv.pypa.io/en/legacy/userguide.html#the-extra-search-dir-option
Please could you explain me what is virtualenv extra?

Still there is some issue because not all **myapp** directories have been included in the **build** directory: for example the static and templates directories and config.py

**Comment by merwok** [comment]
Extras are like flags that enable optional functionality in a package, and have more dependencies.

The advice you were given was to replace `pip install build` (confusingly, `build` is a package name here) with `pip install build[virtualenv]`.  It’s the `virtualenv` string inside the brackets that’s the extra, and it makes `build` install more things in order to do what it needs.

**Comment by Satstef** [comment]
OK thanks.

@mlastIDBS I didn't try your solution, but the one @henryiii suggested is working. 
The only problem now, as I said before, is that **build** doesn't include all applications folder.
