### ISSUE TITLE
ERROR Backend '<backend>' is not available

### ISSUE THREAD

**Issue by tpowell11** [pypa/packaging-problems#506]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Windows 10 Pro 1909, build 18363.1500 

2. What is your Python version?
Python 3.9.0

3. What version of pip do you have?
pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
[Official packaging guide](https://packaging.python.org/tutorials/packaging-projects/)

5. Could you describe your issue in as much detail as possible?
When running 
```sh
python -m build
```
I get the output
```sh
OpenCMBL> python -m build
Collecting lxml>=4.6.2
Installing collected packages: lxml
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
ERROR Backend 'setuptools.build_meta' is not available.
```
I have tried omitting this line, making `build` use the default value, however this still gives:
```sh
ERROR Backend 'setuptools.build_meta:__legacy__' is not available.
```
This prompted me to see if `setuptools` was installed, which it was, and subsequently discovered that I had double-installed python, but `setuptools` was available to both. I also checked that `pip` was installing to the correct directory for python 3.9, and it was. \ 
I've attached the `pyproject.toml`, and `setup.cfg` as .txt files, due to a limitation in GitHub issues.
[pyproject.txt](https://github.com/pypa/packaging-problems/files/6424491/pyproject.txt)
[setup.txt](https://github.com/pypa/packaging-problems/files/6424493/setup.txt)

**Comment by layday** [comment]
Your `build-system.requires` do not list setuptools.  These are meant to be your build dependencies; lxml is a runtime dependency.  Use:

```toml
[build-system]
requires = [
    "setuptools >=42"
]
build-backend = "setuptools.build_meta"
```

**Comment by tpowell11** [comment]
This worked and the package is now building, thanks for the help. Definitely making a template repo for this!
