### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by JAVAHTML1** [pypa/packaging-problems#517]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

raspban

2. What is your Python version?

python 2.7.16

3. What version of pip do you have?

18.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist

**Comment by henryiii** [comment]
> Could you describe your issue in as much detail as possible?

More error please? You should include why the `get_requires_for_build_sdist` invocation failed.

**Comment by layday** [comment]
I'll close this now - feel free to comment below if you're still facing issues.
