### ISSUE TITLE
Got "Backend subproccess exited..." when trying to build packages

### ISSUE THREAD

**Issue by ByeMC** [pypa/packaging-problems#522]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.9.2

3. What version of pip do you have?

pip 21.1.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

["Packaging Python Projects" # Generating distribution archives - packaging.python.org](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives)

5. Could you describe your issue in as much detail as possible?

I tried to use `py -m build`, but I got a `Backend subproccess exited when trying to invoke get_requires_for_build_sdist` error.

```
Windows CMD>py -m build                                                                                             
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
  Successfully uninstalled setuptools-49.2.1
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-57.0.0-py3-none-any.whl (821 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-57.0.0 wheel-0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.1.2 is available.
You should consider upgrading via the 'C:\Users\qwerty\AppData\Local\Temp\build-env-8zxgosz2\Scripts\python.exe -m pip install --upgrade pip' command.
running egg_info
error: error in 'egg_base' option: 'src' does not exist or is not a directory

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist

Windows CMD>
```

**Comment by ByeMC** [comment]
Source Code: https://github.com/ByeStore/ByeStoreLibs

just in case I did stuff wrong

**Comment by ByeMC** [comment]
my project's tree
```
Z:.
│   LICENSE
│   pyproject.toml
│   README.md
│   setup.py
│
└───scr
    └───byestorelibs
            main.py
            __init__.py
```

**Comment by layday** [comment]
You have a typo, "scr" should be "src".

**Comment by ByeMC** [comment]
> You have a typo, "scr" should be "src".

why do i always make that mistake

**Comment by ByeMC** [comment]
It worked, thanks!
