### ISSUE TITLE
Broken setup file. (unable to save classifier)

### ISSUE THREAD

**Issue by BenitzCoding** [pypa/packaging-problems#524]
So, I wrote the wrong classifier, and I uploaded it, I got:

```diff
Uploading distributions to https://upload.pypi.org/legacy/
Uploading cubacrypt-0.0.1.tar.gz
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.17k/4.17k [00:01<00:00, 2.80kB/s]
NOTE: Try --verbose to see response content.
-HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
-Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: GNU General Public License v3.0' is not a valid classifier.
```

So, I edited the classifier to the right classifier in Visual Studio Code, saved it and ran it again, but I got the same error as if I didn't save it, even though I did.

I'm currently in Python 3.9 on a Windows 10 Laptop, with pip version 20.2.3.
I used twine to upload it and I did it using the person who answered in [stackoverflow](https://stackoverflow.com/questions/45207128/failed-to-upload-packages-to-pypi-410-gone/45209514#45209514).

**Comment by layday** [comment]
Have you rebuilt the sdist?  You saved the file and ran what again?

**Comment by layday** [comment]
I'll close this now, but please comment below if you're still having trouble.
