### ISSUE TITLE
HELP FILTERING MOST RECENT REVIEWS

### ISSUE THREAD

**Issue by Arpan-Mistry** [pypa/packaging-problems#525]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

 Windows 10 

2. What is your Python version?

Python 3.7.2

3. What version of pip do you have?

19.2.

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

using for scraping reviews but not been able to sort Sort.MOST_RECENT plz help me for that

5. Could you describe your issue in as much detail as possible?

from google_play_scraper import Sort, reviews
pkg_name='com.facebook.katana'
result = reviews(
    pkg_name,
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort= Sort.MOST_RECENT , # defaults to Sort.MOST_RELEVANT     ----------HELP HERE FOR RECENT------------
    count=1000, # defaults to 100
    filter_score_with=None # defaults to None(means all score)
)
print(result)

**Comment by layday** [comment]
This tracker is for help with Python packaging.  Please see [google-play-scraper](https://github.com/JoMingyu/google-play-scraper); the enum member you're looking for is `Sort.NEWEST`.

**Comment by Arpan-Mistry** [comment]
Realy glad to see such a supportive nature I love you guys the way you are
maintaining a connection between Developers
