### ISSUE TITLE
Why is easy_install deprecated and what should I do instead?

### ISSUE THREAD

**Issue by wvxvw** [pypa/packaging-problems#530]
### setuptools version

44.0.0

### Python version

Does not matter

### OS

Does not matter

### Description

So, I received this warning:

```
WARNING: The easy_install command is deprecated and will be removed in a future version.
```

without any explanation of what I should do instead... And, how am I supposed to install Eggs now? I mean, not right now, but in this grim future, where there seems to be no way to install Eggs.

I mean, Wheel format is garbage and the tools around it are garbage too. In order to avoid dealing with `pip`, and to avoid dealing with idiotic `install` command, my normal workflow was to override `install` to do the equivalent of:

``` sh
python setup.py bdist_egg
python -m easy_install ./dist/*.egg
```

This avoids inconsistencies caused by calling the default `install` command, which are particularly apparent when packaging "data" files, native libraries, scripts etc. I mean, if anything needs deprecation and removal, that's the `install` command. There should only be one way to install a package, which is to build the distributable package first, and then to install it. The bullshit that default `install` does is just harmful.

Now, if you remove `easy_install`, then there's no way to have an actually functional installation process. This is because `pip` cannot install Eggs, and if I tried to replace them with wheels, then in order to make wheels, `pip` will, again, call `setup.py install`... which is idiotic and kinda hilarious, but it's a different battle... `pip` is beyond repair, and needs a complete ground-up remake at this point.

So, you are kinda removing the only functioning tool that can install packages without any alternative? Why?

### Expected behavior

`easy_install` stays as long as there isn't a working alternative to install packages.

### How to Reproduce

Irrelevant

### Output

Irrelevant

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Can you provide more detail about why the workflow is unmet by pip? Please do consider seeking out other resources where others may have worked through the same issues as you.
