### ISSUE TITLE
Trouble with packaging tutorial

### ISSUE THREAD

**Issue by vmgustavo** [pypa/packaging-problems#531]
1. What is your operating system and version?

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

2. What is your Python version?

Python 3.8.10

3. What version of pip do you have?

pip 21.1.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

When using `pip install .` the package is correctly installed with all requirements as expected, however when using `python -m build` to create a `whl` file and installing the package from this `whl` file the required modules are ignored.

While trying to debug this I found that the reason was my `setup.py` file is dynamically reading the `requirements.txt` file in the root directory of the project, hence it works when installing with `pip install .`, but when packaging into a `whl` file the `requirements.txt` file is not correctly copied into a `/tmp` directory used to build the package.

The `setup.py` is executed 4 times when executing the `python -m build` command, on the first 2 executions it works as expected (it is able to find the `requirements.txt` from the project root directory), but on the final 2 executions it can't find the `requirements.txt`.

This is the code to collect the `install_requires` data:
```python
import os

reqs_path = 'requirements.txt'
if os.path.isfile(reqs_path):
    with open(reqs_path) as f:
        install_requires = f.read().splitlines()
```

How should the specification of the `install_requires` be done to guarantee that the `requirements.txt` file is correctly read?

**Comment by henryiii** [comment]
Are you sure the requirements file is in the SDist? Is it in your MANIFEST.in?

**Comment by vmgustavo** [comment]
Could you please elaborate a bit more or point me in the direction of resources about SDist and MANIFEST? I haven't used those and it might be helpful.

**Comment by merwok** [comment]
See https://packaging.python.org/tutorials/packaging-projects/#including-other-files

**Comment by henryiii** [comment]
If you read in a requirements.txt into your setup.py (which I personally don't like, it's a bit of a mis-usage of the file), then you need to make sure it gets packaged into your SDist. So you need to add a rule to MANIFEST.in to get the file included (normally, you don't want to include requirements files, as they are not intended for package requirements, so it's not default, and the setup.cfg mode doesn't allow using them for requirements).

Something like this:

```
include requirements.txt
```

See https://github.com/scikit-hep/awkward-1.0/blob/ce393b48abb2eda0a60d003867eeb3ffcb22f91c/MANIFEST.in for an example of a package that I have not managed to talk into just including the requirements in the setup.cfg/py yet. ;)

**Comment by merwok** [comment]
More info on why parsing requirements.txt in setup.py is an anti-pattern: https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by vmgustavo** [comment]
Thanks. What would be the ideal setup to specify the required modules and still use the requirements file?

**Comment by layday** [comment]
To be clear, what is considered an anti-pattern is specifying concrete dependencies in packages that you distribute, i.e. if your `requirements.txt` were to function as a lock file.  Whether those concrete dependencies come from a `requirements.txt` is irrelevant.

**Comment by henryiii** [comment]
Well, it's discouraged enough to keep setuptools from adding a `file:` option for install and extra requirements.
