### ISSUE TITLE
i can't be able to upload package into  https://test.pypi.org 

### ISSUE THREAD

**Issue by mounika-gorintla** [pypa/packaging-problems#534]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Windows 10 

2. What is your Python version?
 Python 3.9.6

3. What version of pip do you have?
 pip 21.1.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#uploading-your-project-to-pypi

5. Could you describe your issue in as much detail as possible?

I am not able to upload package into the above mentioned URL. And getting access issue while uploading files. Please find the below screenshot for your reference. 

![image](https://user-images.githubusercontent.com/87873140/126821479-ab663968-75f7-4458-9e6d-7d294f0f24e3.png)

**Comment by merwok** [comment]
The project already exists and you’re not a maintainer: https://test.pypi.org/project/aws-access/

**Comment by mounika-gorintla** [comment]
Hi Team,

As I can see Rajib deb is the maintainer of the aws-access package, but he left our organization so, can you make me as a maintainer of this packages.
Or let us know how we can get the maintainer access.

Regards
G. Mounika

**Comment by merwok** [comment]
OK, you hadn’t said that you were in the same organization who published the package before.
This is the process to claim a project name: https://pypi.org/help/#project-name-claim

**Comment by mounika-gorintla** [comment]
Hi Éric Araujo,

 

The original (& sole) maintainer, Rajib Deb ***@***.***), is no longer with Cisco. And his Cisco email is no longer valid.

However, aws-access has been in a Cisco project & still is. Now it needs code update in order to fix issue.

 

Can you add us as new maintainers?

 

Thanks,

Allen

 

 

 

From: "Mounika Gorintla -X (mgorintl - INFOSYS LIMITED at Cisco)" ***@***.***>
Date: Wednesday, July 28, 2021 at 4:50 AM
To: pypa/packaging-problems ***@***.***>, pypa/packaging-problems ***@***.***>
Cc: Author ***@***.***>, "Suhas Talathi -X (stalathi - INFOSYS LIMITED at Cisco)" ***@***.***>, "Allen Liu (allliu)" ***@***.***>, "Tony Lin (dtlin)" ***@***.***>
Subject: RE: [pypa/packaging-problems] i can't be able to upload package into https://test.pypi.org (#534)

 

Hi Team,

 

As I can see Rajib deb is the maintainer of the aws-access package, but he left our organization so, can you make me as a maintainer of this packages.

Or let us know how we can get the maintainer access.

 

Regards 

G. Mounika

**Comment by henryiii** [comment]
This is for test.pypi.org, not pypi.org, right? I think the name claim form is for pypi.org?

**Comment by mounika-gorintla** [comment]
Hi Henry Schreiner,

we need to claim on both https://pypi.org/ and https://test.pypi.org/ sites. Could you guide me on this

**Comment by merwok** [comment]
Please follow the guide on the link I gave.

**Comment by mounika-gorintla** [comment]
Hi Éric Araujo and Team,

We have opened new support case for Transferring ownership of the project four days ago.  Could you please tell me how long it takes?
Kindly check the link for more details on support case : https://github.com/pypa/pypi-support/issues/1242

Regards
G. Mounika

**Comment by merwok** [comment]
Could you please close this ticket and only communicate on the other one?  That is the proper channel, not here.

**Comment by layday** [comment]
None of us here can give you an estimate, sorry.
