### ISSUE TITLE
Trouble with importing

### ISSUE THREAD

**Issue by tinyCodersDen** [pypa/packaging-problems#535]
OS: Windows 10
Python Version : 3.7.1
Pip version: 21.1.1

Hello, I created a module in PyPI over [here.](https://pypi.org/project/py-data-structure/)
The installation works all fine, but when I do `import py-data-structure`, I get an error like this: `import py-data-structure
             ^
SyntaxError: invalid syntax`

This is ok, it might be an invalid syntax error, but I want to keep my package name the same, but at the same time, I want the import statement to work different. For example, you say `pip install opencv-python` but then you say `import cv2`, so I want it to be like this: `pip install py-data-structure`, but I want it like `import py_data_structure`. Notice that I changed the dashes to underscores.

Github repo [here](https://github.com/tinyCodersDen/py-data-structure)

**Comment by merwok** [comment]
> when I do import py-data-structure, I get an error

Correct, you can’t have hyphens in python identifiers (module names, function names, etc).

> I want it like `import py_data_structure`

Good!  Then why did you try `import py-data-structure` instead of the correct form?


The packaging and import systems are mostly decoupled in Python.
In the opencv example, they probably have `name='opencv-python'` in their setup script, but `cv2/__init__.py` for the modules.

**Comment by tinyCodersDen** [comment]
Sure, I tried it out, but I got an error like this: `error: package directory 'py-data-structure' does not exist`
I kept it as `name='py-data-structure'`, and I changed my setup script to be `py_data_structure/__init__.py`

Notice the dashes changed to underscores, I also updated my github to have the setup and init files, so for a better view of my program, you can go [here](https://github.com/tinyCodersDen/py-data-structure)

I kept it in the correct form to show what I want my desired import statement to look like.

**Comment by merwok** [comment]
name is fine, but you didn’t adapt the list of packages:
```python
  packages = ['py_data_structure'],
```

**Comment by tinyCodersDen** [comment]
Oh Ok I see, I made a new version and now it works. Thanks for your help and support!
