### ISSUE TITLE
Trouble with the packaging tutorial - Something wrong with TOP_DIR, can't find

### ISSUE THREAD

**Issue by Kornax** [pypa/packaging-problems#540]
### OS version

WSL Ubuntu 20.04

### Python version

Python 3.8.5

### Pip version

pip 20.0.2

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

Following the tutorial up to the "Generating distribution archives" section.

Directory Structure
```
package_name/
├── CHANGES.txt
├── README.md
├── pyproject.toml
├── setup.cfg
└── src
    └── package_name
        ├── __init__.py
        ├── module1.py
        ├── module2.py
        ├── module3.py
        ├── module4.py
        └── module5.py
```

setup.cfg
```cfg
[metadata]
name = ***
version = 0.1.0
author = ***
author_email = ***
description = ***
long_description = file: README.md
long_description_content_type = text/markdown
url = ***
project_urls =
    Bug Tracker = ***
classifiers =
    Programming Language :: Python :: 3
    Development Status :: 4 - Beta
    Natural Language :: Spanish
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6

[options.packages.find]
where = src
```

pyproject.toml
```
[build-system]
requires = [
    "requests",
]
build-backend = "setuptools.build_meta"
```

Error while running `python3 -m build`

### Error message

```text
Something wrong with TOP_DIR, can't find:  ${TOP_DIR}/include
```

**Comment by henryiii** [comment]
You need to include setuptools>=42 and wheel in your requires list in pyproject.toml.

**Comment by Kornax** [comment]
Thanks @henryiii , I misinterpreted the purpose of `build-system.requires`.

Tho I'm still having the same outcome:

pyproject.toml
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

python3 -m build
```
Something wrong with TOP_DIR, can't find:  ${TOP_DIR}/include
```

Tried with and without a virtualenv to see if there was a issue with that (installing the same packages on both scenarios), but same outcome as well.

**Comment by henryiii** [comment]
Is there a TOP_DIR mention somewhere in your code? Not sure what's producing that. Do you have a link to a repo?

**Comment by jaboucher** [comment]
I am getting the same thing. The code is really trivial so I know there is no use of TOP_DIR. This post was marked as resolved but I see no mention of the solution. Does anyone remember the fix? I see this on both linux and mac.

**Comment by merwok** [comment]
github issues is a poor system, there is no resolved status but only closed.  This ticket was probably caused by lack of response from the OP.

Can you investigate your issue a little?  If your code does not contain `TOP_DIR`, then maybe it comes from `build` or another build tool, so you could grep in your site-packages or build environment.

**Comment by layday** [comment]
Can you paste the complete output? Is that all there is, just a message, no stack trace?

**Comment by jaboucher** [comment]
>> setup.py's, though. Did you add any dependencies?
I use os and logging so I added these to the pyproject.toml. This didn't change anything:[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "os",
    "logging"
]
build-backend = "setuptools.build_meta"

**Comment by jaboucher** [comment]
Here is my setup.cfg[metadata]
name = robot_bpa_gppe_sdk
version = 0.0.1
author = Me
author_email = Me@gmail.com
description = GPPD SDK
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/pypa/gppd_sdk
project_urls =
    Bug Tracker = https://github.com/pypa/sampleproject/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6

[options.packages.find]
where = src

**Comment by henryiii** [comment]
`os` and `logging` are standard library modules. You can't install them from PyPI. Basically anything in here: https://docs.python.org/3/library/ (though a few newer ones do have back ports on PyPI).

If that's the problem, this is a horrible error message for that problem!

**Comment by jaboucher** [comment]
That does not seem to be it.
% cat pyproject.toml 
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

jabouche@JABOUCHE-M-D339 packages % python3 -m build  
Something wrong with TOP_DIR, can't find:  ${TOP_DIR}/include

**Comment by henryiii** [comment]
There's a really old "backport" (initial implementation, more likely) at https://pypi.org/project/logging/, but it doesn't seem to have this problem.

Does "python3 -m site" work?

**Comment by jaboucher** [comment]
This is what I get. 
% python3 -m site
sys.path = [
    '/Users/jabouche/workspace/<cut>/packages',
    '/Users/jabouche/Development/nso-5.2.3.3/src/ncs/pyapi',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python38.zip',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/lib-dynload',
    '/Users/jabouche/Library/Python/3.8/lib/python/site-packages',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages',
    '/Library/Python/3.8/site-packages',
]
USER_BASE: '/Users/jabouche/Library/Python/3.8' (exists)
USER_SITE: '/Users/jabouche/Library/Python/3.8/lib/python/site-packages' (exists)
ENABLE_USER_SITE: True

**Comment by jaboucher** [comment]
I get an error upgrading logging% pip3 install logging
Defaulting to user installation because normal site-packages is not writeable
Collecting logging
  Downloading logging-0.4.9.6.tar.gz (96 kB)
     |████████████████████████████████| 96 kB 664 kB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bt/p3bn4br57rx9fqrc5fc01kdw0000gn/T/pip-install-hc_9xky_/logging_5376ebaff1344100a0a80bff17dcde61/setup.py'"'"'; __file__='"'"'/private/var/folders/bt/p3bn4br57rx9fqrc5fc01kdw0000gn/T/pip-install-hc_9xky_/logging_5376ebaff1344100a0a80bff17dcde61/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/bt/p3bn4br57rx9fqrc5fc01kdw0000gn/T/pip-pip-egg-info-6avbbbnq

**Comment by layday** [comment]
Do you have another package on path called "build"? What's the output of `python3 -m inspect -d build`?

**Comment by jaboucher** [comment]
% python3 -m inspect -d build
Something wrong with TOP_DIR, can't find:  ${TOP_DIR}/include

**Comment by jaboucher** [comment]
% unset PYTHONPATH% python3 -m inspect -d build
Target: build
Origin: /Users/jabouche/Library/Python/3.8/lib/python/site-packages/build/__init__.py
Cached: /Users/jabouche/Library/Caches/com.apple.python/Users/jabouche/Library/Python/3.8/lib/python/site-packages/build/__init__.cpython-38.pyc
Loader: <_frozen_importlib_external.SourceFileLoader object at 0x10a05a130>
Submodule search path: ['/Users/jabouche/Library/Python/3.8/lib/python/site-packages/build']

**Comment by layday** [comment]
Do you have a "build" script which isn't build's? `command -v build`

**Comment by jaboucher** [comment]
That was it! I had to unset my PYTHONPATH which had a "." in it which must have confused things.  Thanks Everyone!

**Comment by layday** [comment]
Out of curiosity, do you know which package/distribution it was that caused it?

**Comment by jaboucher** [comment]
Sorry, The error message was pretty bare.

**Comment by henryiii** [comment]
If removing the "." fixed it, it was probably a local file? `build.py` or `build/__init__.py` in your package?

What is the output of `pip list`?

Also, you should not be installing `logging`, it's been builtin to Python since Python 2.3, 20 years ago.

**Comment by jaboucher** [comment]
Actually I had the NSO PYTHONPATH set. Perhaps one of the NSO packages was the problem.

**Comment by henryiii** [comment]
Okay, I bet they added a `build` module which conflicts with the pypa one. I'd request that they rename their module if possible. ;)

**Comment by layday** [comment]
We could've just called "build" something else... *grumble grumble*
