### ISSUE TITLE
'pip install tensorflow' does not work on FreeBSD

### ISSUE THREAD

**Issue by probonopd** [pypa/packaging-problems#547]
### Problem description

Not sure whether this is the right bugtracker to get this resolved; please point me to the correct one in case it isn't.

`pip install tensorflow` does not work on FreeBSD. Apparently there is no precompiled package for FreeBSD. Why?

```
FreeBSD% ./spleeter/bin/pip install tensorflow     
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Comment by probonopd** [comment]
Use case: Running [Spleeter](https://github.com/deezer/spleeter) on FreeBSD.

```
python3 -m venv spleeter
./spleeter/bin/pip install spleeter
```

**Comment by matthewfeickert** [comment]
I think the answer to your problem is that TensorFlow doesn't distribute any source distributions on PyPI and only distributes wheels (e.g. https://pypi.org/project/tensorflow/2.6.0/#files) and there isn't a compatible wheel with your operating system.

I think that you should ask this question on the [TensorFlow GitHub Issues](https://github.com/tensorflow/tensorflow/issues) as this is a TensorFlow decision and not a `pip` issue, but just a quick search on 'FreeBSD' there makes it look like you're going to need to build TensorFlow from source.

**Comment by layday** [comment]
Closing this one, please continue discussion on the tensorflow tracker.

**Comment by probonopd** [comment]
Information from the tensorflow tracker:

The Google TensorFlow team won't do binary builds due to lack of resources. They would possibly be willing to provide source distributions on PyPI but there is a concern:

> There might be an issue here in that TF builds with Bazel (no cmake support) and pypa might not be able to run these.

Can someone knowledgable comment on this please?
I am just a user trying to install TensorFlow through pip on FreeBSD and I don't even know what Bazel is (and have no desire to, honestly).

**Comment by matthewfeickert** [comment]
> I am just a user trying to install TensorFlow through pip on FreeBSD

If you want TensorFlow on FreeBSD then you're going to need to build TensorFlow from source (as in clone it from GitHub and then make sure that you have all of its build dependencies setup and then build it with Bazel).

> and don't even know what Bazel is (and have no desire to, honestly).

[Bazel is Google's build system](https://bazel.build/).

My recommendation is that if you want things to work sooner than later that you learn how to build TensorFlow from source in a Debian Docker image and then once you've figured out how to at least get things building then work on getting things to work in FreeBSD.

For a longer term solution I would continue to follow the discussion on https://github.com/tensorflow/tensorflow/issues/52125 (which you already are as you opened the Issue :+1:) and then see where that eventually leads.
