### ISSUE TITLE
Package platform version for Mac OS X different from actual platform version

### ISSUE THREAD

**Issue by sbrodehl** [pypa/packaging-problems#554]
### Problem description

Hi there,

I am building a package with Github Actions on `macOS-10.15` for python 3.6, 3.7, 3.8 and 3.9 with the following system information

| Command | Output | 
| --- | --- |
|  `uname -a` | Darwin Mac-1636462704207.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64 x86_64 |
|  `sw_vers` |  ProductName: Mac OS X, ProductVersion: 10.15.7, BuildVersion: 19H1419 |
|  `python3 -m platform` | Darwin-19.6.0-x86_64-i386-64bit |
|  `python3 -c 'import platform; print(platform.mac_ver())'` | ('10.15.7', ('', '', ''), 'x86_64') |
| `pip --version` | pip 21.3.1 | 

The resulting package is named `...-macosx_10_14_x86_64.whl`, so the package platform version is 10.14, which is neither the darwin kernel version, nor the Mac OS X version.
The same happens on `macOS-11`

What am I missing?
Thanks!

**Comment by henryiii** [comment]
It should pick up whatever the `MACOSX_DEPLOYMENT_TARGET` was when that version of Python was compiled. You can manually control it with `MACOSX_DEPLOYMENT_TARGET`, but you shouldn't set it lower than the original Python compile. I'm guessing the python-versions Python's are compiled with the lowest supported GHA macOS version, which is 10.14.

If you are building wheels, I'd use https://cibuildwheel.readthedocs.io/en/stable/ - that uses the official Python downloads on macOS, so you can target `MACOSX_DEPLOYMENT_TARGET=10.9` or later, whatever you want. "Nice" distributions generally pick something around 10.9-10.12, with 10.13 or 10.14 for C++17 support.

This is a macOS thing - you can normally target any older version with MACOSX_DEPLOYMENT_TARGET, every new runtime feature is gated, so there's never a reason to use old macOS versions even if you are targeting compatibility with old macOS versions.

**Comment by sbrodehl** [comment]
Thank you very much for the quick reply! :)
