### ISSUE TITLE
installing package if needed

### ISSUE THREAD

**Issue by FateScript** [pypa/packaging-problems#555]
### OS version

Ubuntu 18.04

### Python version

3.6.9

### Pip version

pip3 install -v -e .

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

Hello, pypa community.
My setup.py requires installing torch (you might refer to [this](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/setup.py#L8-L9)). If I write a pyproject.toml like :
```
[build-system]
requires = [
    "setuptools>=42",
    "torch>=1.7",
    "wheel",
]
build-backend = "setuptools.build_meta"
```

Then I run the following cmd: `pip install -v -e .` and I found that `torch` will be collected even if it's installed on my machine. I know that it's a isolated build, I just wonder what could I do to make the installation behaves like pip:
(1)If I have alread installed torch that >= 1.7, then use it to build
(2)If I don't install statisfied version torch, install it.

Thanks.

**Comment by matthewfeickert** [comment]
If you don't want build isolation then you should just be able to turn it off with the `--no-build-isolation` flag for `pip install`. c.f. [Disabling build isolation](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#disabling-build-isolation) in the `pip` docs.

Does this address your issue?

**Comment by henryiii** [comment]
Last I checked, that is exactly what it does for isolated builds, except it is checking your *pip cache* for wheels that match, rather than installed packages (you can't install a package from an installed package, only from your cache). I've had it bite me when I mistakenly put too low a minimum on setuptools, in fact.

**Comment by FateScript** [comment]
> Disabling build isolation

`--no-build-isolation` worked in the first case. However, if I didn't installed torch, it fails.

**Comment by FateScript** [comment]
> Last I checked, that is exactly what it does for isolated builds, except it is checking your _pip cache_ for wheels that match, rather than installed packages (you can't install a package from an installed package, only from your cache). I've had it bite me when I mistakenly put too low a minimum on setuptools, in fact.

So is there anyway to check torch installation like pip before setup.py runs?

**Comment by merwok** [comment]
Can you explain how the behaviour is a problem, or what would be gained by changing it?

**Comment by henryiii** [comment]
As I've said, _the installed torch cannot be used inside the new virtual environment_. Only a cached wheel can be reused, and if you have one, it will be reused. If you run `pip cache purge` (or if you install it with conda or another package manager), it can't be reused.

**Comment by henryiii** [comment]
Do you really need torch at _build time_, by the way? Just curious, there aren't many reasons (but there are some) to use packages at build time.

**Comment by henryiii** [comment]
PS: Also, what you've noticed is that `--no-build-isolation` does two things. It disables the creation of the virtual environment that the wheel was built in, and it also ignores the requests in `build-system.requires`. If you are working on package managers (like conda recipes), this is exactly what you want - you already control the build environment, and you need to reimplement the packages required anyway (conda packages or other system packages may have different names, you can't use pip, etc).

**Comment by FateScript** [comment]
> OP: Can you explain how the behaviour is a problem, or what would be gained by changing it?

I'm not saying that it's a problem. I just wonder is there a method for me to auto-detect torch(just like `install_requires` argument of  `setup` function) before `setup.py` runs.

**Comment by henryiii** [comment]
`install_requires` is for the _current_ environment. The build environment is a brand new environment, so there's no way to "auto-detect" something in it, it doesn't even exist before pip runs.

It is possible to grab a cached version of the wheel to install, and pip already does do that to the best of my knowledge.

**Comment by FateScript** [comment]
> Do you really need torch at _build time_, by the way? 

Yes, I need  to compile my own cuda/cpp file provided by torch.

> It is possible to grab a cached version of the wheel to install, and pip already does do that to the best of my knowledge.

Now I  know what should I do to solve my issue. Thanks for help of everyone : )
