### ISSUE TITLE
After downloading the package I just uploaded, I can't import

### ISSUE THREAD

**Issue by lianxmfor** [pypa/packaging-problems#557]
### OS version

macos

### Python version

Python 3.8.5

### Pip version

pip 21.3.1 

### Guide link

https://github.com/oom-ai/oomstore/tree/e527df579e0381b4852a136a96e3a1516cfddf45/sdk/python

### Problem description

I want to package [my python code][1] and upload it to PyPI so that people can use it easily. I followed the [documentation][2] for packaging python projects and eventually uploaded it to the [PyPI test website][3]. I ran pip install to try and install it.

Strangely enough, after installing it, I couldn't find the package:

```code
(base) ➜  ~ python3 -m pip install --index-url https://test.pypi.org/simple/  oomstore==0.0.4
Looking in indexes: https://test.pypi.org/simple/
Collecting oomstore==0.0.4
  Downloading https://test-files.pythonhosted.org/packages/4f/a5/4e7089a1ecb36a59f7f0852a5f96a6054daf886d97132060a7efcda5f04f/oomstore-0.0.4-py3-none-any.whl (12 kB)
Installing collected packages: oomstore
Successfully installed oomstore-0.0.4
(base) ➜  ~ python3
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import oomstore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'oomstore'
>>>
```

I went to the installation path of the package and found no python files in it: 

```code
(base) ➜  ~ cd ~/miniconda3/lib/python3.8/site-packages/oomstore-0.0.4.dist-info
(base) ➜  oomstore-0.0.4.dist-info ls
INSTALLER     LICENSE       METADATA      RECORD        REQUESTED     WHEEL         top_level.txt
(base) ➜  oomstore-0.0.4.dist-info

```

Did I do something wrong? Is there something wrong with my setup.cfg file? Forgive me for asking such an ignorant question, I'm new to python...

  [1]: https://github.com/oom-ai/oomstore/tree/e527df579e0381b4852a136a96e3a1516cfddf45/sdk/python
  [2]: https://packaging.python.org/tutorials/packaging-projects/#
  [3]: https://test.pypi.org/project/oomstore/

I also asked a question on StackOverflow： https://stackoverflow.com/questions/70113511/packaging-python-projects-failed?noredirect=1#comment123941853_70113511

**Comment by merwok** [comment]
The wheel file does not contain an `oomstore` package, but only the sub-package `codegen`.
I think this is caused by the erroneous `package_dir` option in your setup.cfg; try removing it and building the distributions, which you can then inspect before uploading (wheel is a zip file).

**Comment by lianxmfor** [comment]
> The wheel file does not contain an `oomstore` package, but only the sub-package `codegen`. I think this is caused by the erroneous `package_dir` option in your setup.cfg; try removing it and building the distributions, which you can then inspect before uploading (wheel is a zip file).

thanks, merwok!
