### ISSUE TITLE
https://github.com/pypa/packaging-problems

### ISSUE THREAD

**Issue by Claudio060320** [pypa/packaging-problems#559]
https://github.com/pypa/packaging-problems

**Comment by Claudio060320** [comment]
https://github.com/pypa/packaging-problems

**Comment by merwok** [comment]
Hello!  You have posted the link to this repo in the title and two messages.
What is the problem that brings you here?  (please edit the ticket title and message)

**Comment by merwok** [comment]
Judging by public contributions from that username, might be an automated agent or a person quite confused about github.
Suggest that a triager closes this.
