### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by Claudio060320** [pypa/packaging-problems#560]
### OS version

python --version

### Python version

python --version

### Pip version

python -m pip --version

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

Include all the commands that you ran, any offline guides you followed, etc.

### Error message

```text
Remember, contributions to this repository should follow its
```

**Comment by merwok** [comment]
Triagers, please close this.
