### ISSUE TITLE
Backend subproccess exited when trying to invoke build_sdist

### ISSUE THREAD

**Issue by carl-frederick-github** [pypa/packaging-problems#561]
### Problem description

This build was previously working fine and I haven't seen this error before.  I haven't run it in a while and have made no changes to the build directory I don't think.  I'm using a virtual env and have activated it.  Python3.7 and you can see the packages I'm using when I ask to upgrade them.  Here's what happens:

**Comment by carl-frederick-github** [comment]
Continuing with the output...

(sgjbr_plugin_api) PS D:\gst\Tools\main\coretech\shotgun\sgjbr_plugin_api> py -m pip install --upgrade build
Requirement already up-to-date: build in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (0.7.0)
Requirement already satisfied, skipping upgrade: packaging>=19.0 in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (21.2)
Requirement already satisfied, skipping upgrade: tomli>=1.0.0 in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (1.2.2)
Requirement already satisfied, skipping upgrade: pep517>=0.9.1 in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (0.12.0)
Requirement already satisfied, skipping upgrade: importlib-metadata>=0.22; python_version < "3.8" in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (4.8.2)
Requirement already satisfied, skipping upgrade: colorama; os_name == "nt" in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (0.4.4)
Requirement already satisfied, skipping upgrade: pyparsing<3,>=2.0.2 in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from packaging>=19.0->build) (2.4.7)
Requirement already satisfied, skipping upgrade: zipp; python_version < "3.8" in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from pep517>=0.9.1->build) (3.6.0)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.4; python_version < "3.8" in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from importlib-metadata>=0.22; python_version < "3.8"->build) (4.0.0)
(sgjbr_plugin_api) PS D:\gst\Tools\main\coretech\shotgun\sgjbr_plugin_api> py -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 42, wheel)
* Getting dependencies for sdist...
C:\Users\CARL~1.FRE\AppData\Local\Temp\build-env-v0e2ws67\lib\site-packages\setuptools\dist.py:743: UserWarning: Usage of uppercase key 'Topic' in 'metadata' will be deprecated in future versions. Please use lowercase 'topic' instead
  % (opt, section, lowercase_opt)
running egg_info
writing src\sgjbr_plugin_api.egg-info\PKG-INFO
writing dependency_links to src\sgjbr_plugin_api.egg-info\dependency_links.txt
writing top-level names to src\sgjbr_plugin_api.egg-info\top_level.txt
reading manifest file 'src\sgjbr_plugin_api.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'src\sgjbr_plugin_api.egg-info\SOURCES.txt'
* Building sdist...
C:\Users\CARL~1.FRE\AppData\Local\Temp\build-env-v0e2ws67\lib\site-packages\setuptools\dist.py:743: UserWarning: Usage of uppercase key 'Topic' in 'metadata' will be deprecated in future versions. Please use lowercase 'topic' instead
  % (opt, section, lowercase_opt)
running sdist
running egg_info
writing src\sgjbr_plugin_api.egg-info\PKG-INFO
writing dependency_links to src\sgjbr_plugin_api.egg-info\dependency_links.txt
writing top-level names to src\sgjbr_plugin_api.egg-info\top_level.txt
reading manifest file 'src\sgjbr_plugin_api.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'src\sgjbr_plugin_api.egg-info\SOURCES.txt'
running check
warning: check: missing required meta-data: url

copying files to sgjbr_plugin_api-0.0.0...
copying src\sgjbr_plugin_api.egg-info\PKG-INFO -> sgjbr_plugin_api-0.0.0\src\sgjbr_plugin_api.egg-info
copying src\sgjbr_plugin_api.egg-info\SOURCES.txt -> sgjbr_plugin_api-0.0.0\src\sgjbr_plugin_api.egg-info
copying src\sgjbr_plugin_api.egg-info\dependency_links.txt -> sgjbr_plugin_api-0.0.0\src\sgjbr_plugin_api.egg-info
copying src\sgjbr_plugin_api.egg-info\top_level.txt -> sgjbr_plugin_api-0.0.0\src\sgjbr_plugin_api.egg-info
Writing sgjbr_plugin_api-0.0.0\setup.cfg
error: [Errno 13] Permission denied: 'sgjbr_plugin_api-0.0.0\\setup.cfg'

ERROR Backend subproccess exited when trying to invoke build_sdist

**Comment by carl-frederick-github** [comment]
I think I mistakenly closed my earlier issue...here it is again:

**Comment by carl-frederick-github** [comment]
This build was previously working fine and I haven't seen this error before. I haven't run it in a while and have made no changes to the build directory I don't think. I'm using a virtual env and have activated it. Python3.7 and you can see the packages I'm using when I ask to upgrade them. Here's what happens:

(sgjbr_plugin_api) PS D:\gst\Tools\main\coretech\shotgun\sgjbr_plugin_api> py -m pip install --upgrade build
Requirement already up-to-date: build in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (0.7.0)
Requirement already satisfied, skipping upgrade: packaging>=19.0 in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (21.2)
Requirement already satisfied, skipping upgrade: tomli>=1.0.0 in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (1.2.2)
Requirement already satisfied, skipping upgrade: pep517>=0.9.1 in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (0.12.0)
Requirement already satisfied, skipping upgrade: importlib-metadata>=0.22; python_version < "3.8" in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (4.8.2)
Requirement already satisfied, skipping upgrade: colorama; os_name == "nt" in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from build) (0.4.4)
Requirement already satisfied, skipping upgrade: pyparsing<3,>=2.0.2 in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from packaging>=19.0->build) (2.4.7)
Requirement already satisfied, skipping upgrade: zipp; python_version < "3.8" in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from pep517>=0.9.1->build) (3.6.0)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.4; python_version < "3.8" in d:\gst\tools\main\coretech\shotgun\sgjbr_plugin_api\lib\site-packages (from importlib-metadata>=0.22; python_version < "3.8"->build) (4.0.0)
(sgjbr_plugin_api) PS D:\gst\Tools\main\coretech\shotgun\sgjbr_plugin_api> py -m build

Creating venv isolated environment...
Installing packages in isolated environment... (setuptools >= 42, wheel)
Getting dependencies for sdist...
C:\Users\CARL~1.FRE\AppData\Local\Temp\build-env-v0e2ws67\lib\site-packages\setuptools\dist.py:743: UserWarning: Usage of uppercase key 'Topic' in 'metadata' will be deprecated in future versions. Please use lowercase 'topic' instead
% (opt, section, lowercase_opt)
running egg_info
writing src\sgjbr_plugin_api.egg-info\PKG-INFO
writing dependency_links to src\sgjbr_plugin_api.egg-info\dependency_links.txt
writing top-level names to src\sgjbr_plugin_api.egg-info\top_level.txt
reading manifest file 'src\sgjbr_plugin_api.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'src\sgjbr_plugin_api.egg-info\SOURCES.txt'
Building sdist...
C:\Users\CARL~1.FRE\AppData\Local\Temp\build-env-v0e2ws67\lib\site-packages\setuptools\dist.py:743: UserWarning: Usage of uppercase key 'Topic' in 'metadata' will be deprecated in future versions. Please use lowercase 'topic' instead
% (opt, section, lowercase_opt)
running sdist
running egg_info
writing src\sgjbr_plugin_api.egg-info\PKG-INFO
writing dependency_links to src\sgjbr_plugin_api.egg-info\dependency_links.txt
writing top-level names to src\sgjbr_plugin_api.egg-info\top_level.txt
reading manifest file 'src\sgjbr_plugin_api.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'src\sgjbr_plugin_api.egg-info\SOURCES.txt'
running check
warning: check: missing required meta-data: url
copying files to sgjbr_plugin_api-0.0.0...
copying src\sgjbr_plugin_api.egg-info\PKG-INFO -> sgjbr_plugin_api-0.0.0\src\sgjbr_plugin_api.egg-info
copying src\sgjbr_plugin_api.egg-info\SOURCES.txt -> sgjbr_plugin_api-0.0.0\src\sgjbr_plugin_api.egg-info
copying src\sgjbr_plugin_api.egg-info\dependency_links.txt -> sgjbr_plugin_api-0.0.0\src\sgjbr_plugin_api.egg-info
copying src\sgjbr_plugin_api.egg-info\top_level.txt -> sgjbr_plugin_api-0.0.0\src\sgjbr_plugin_api.egg-info
Writing sgjbr_plugin_api-0.0.0\setup.cfg
error: [Errno 13] Permission denied: 'sgjbr_plugin_api-0.0.0\setup.cfg'

ERROR Backend subproccess exited when trying to invoke build_sdist

**Comment by Chirag1994** [comment]
I'm getting the following error. How can I resolve it?

* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=65.6.0, wheel)
* Getting build dependencies for sdist...
Traceback (most recent call last):
  File "C:\Users\Chirag Sharma\AppData\Local\Programs\Python\Python311\Lib\site-packages\pep517\in_process\_in_process.py", line 351, in <module>
    main()
  File "C:\Users\Chirag Sharma\AppData\Local\Programs\Python\Python311\Lib\site-packages\pep517\in_process\_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chirag Sharma\AppData\Local\Programs\Python\Python311\Lib\site-packages\pep517\in_process\_in_process.py", line 285, in get_requires_for_build_sdist
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chirag Sharma\AppData\Local\Temp\build-env-pf2y0ur3\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chirag Sharma\AppData\Local\Temp\build-env-pf2y0ur3\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "C:\Users\Chirag Sharma\AppData\Local\Temp\build-env-pf2y0ur3\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 67
SyntaxError: keyword argument repeated: packages

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist

**Comment by j4r0slv** [comment]
I had similar problem when executing:

`python3 -m build`

in my tutorial project from [this tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/)

So this was my code which I rewrite manually:
```
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example_package_jarrros"
version = "0.0.1"
authors = [
    {name="example author", email="author@example.com" },
]
description = "a small example package" 
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating system :: OS Independent",
    ]

    [project.urls]
    "homepage" = "https://github.com/pypa/sampleproject"
    "Bug Tracker" = "https://github.com/pypa/sampleprojects/issues"
```
And this one I just copied to check if it solves the issue. And it worked
```
[project]
name = "example_package_YOUR_USERNAME_HERE"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
```

Conclusion. The syntax is very sensitive, especially when you begin to learn.
I've missed some spaces here, added extra spaces there...

And again this is what pop up in the beggining:
```
jarojaro@MacBook-Air-Jarosaw PACKAGING _ % python3 -m build                                      
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 304, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/wj/50fr0qq93vxb1hp4s8bzlp300000gn/T/build-env-4xevw0kz/lib/python3.11/site-packages/hatchling/build.py", line 34, in build_sdist
    return os.path.basename(next(builder.build(sdist_directory, ['standard'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/wj/50fr0qq93vxb1hp4s8bzlp300000gn/T/build-env-4xevw0kz/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 93, in build
    self.metadata.validate_fields()
  File "/private/var/folders/wj/50fr0qq93vxb1hp4s8bzlp300000gn/T/build-env-4xevw0kz/lib/python3.11/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
    self.core.validate_fields()
  File "/private/var/folders/wj/50fr0qq93vxb1hp4s8bzlp300000gn/T/build-env-4xevw0kz/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1327, in validate_fields
    getattr(self, attribute)
  File "/private/var/folders/wj/50fr0qq93vxb1hp4s8bzlp300000gn/T/build-env-4xevw0kz/lib/python3.11/site-packages/hatchling/metadata/core.py", line 979, in classifiers
    raise ValueError(message)
ValueError: Unknown classifier in field `project.classifiers`: Operating system :: OS Independent

ERROR Backend subprocess exited when trying to invoke build_sdist
```

**Comment by layday** [comment]
You have a typo, `Operating system :: OS Independent` should be `Operating System :: OS Independent` (note the capital S).
