### ISSUE TITLE
Allowed values for license

### ISSUE THREAD

**Issue by erzoe** [pypa/packaging-problems#563]
### OS version
Debian 11

### Python version
Python 3.9.2

### Pip version
pip 21.3.1

### Guide link
https://packaging.python.org/en/latest/tutorials/packaging-projects/

### Problem description
Trying to upload a package licensed under [WTFPL](http://www.wtfpl.net/) to pypi with `python3 -m twine upload dist/*` I am getting the error message

> Invalid value for classifiers. Error: Classifier 'License :: WTFPL' is not a valid classifier.

I have specified the license in setup.cfg as:
```
classifiers =
    Programming Language :: Python :: 3
    License :: WTFPL
    Operating System :: OS Independent
```

I have not seen any limitation for the allowed licenses on [Packaging Python Projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/) and the [setuptools help for the license field](https://setuptools.pypa.io/en/latest/references/keywords.html).
It does, of course, make a lot of sense to not allow any string to avoid different names for the same license but I am missing the information which values I can use.

I have somehow found [this link](https://pypi.org/pypi?%3Aaction=list_classifiers) which seems to provide the list I am searching for but it does not list the WTFPL. Is it a deliberate decision that some licenses are not allowed or has this license just never been considered? How should users deal with that if the license they want to use is not allowed?

### Error message

```
Content received from server:
<html>
 <head>
  <title>400 Invalid value for classifiers. Error: Classifier 'License :: WTFPL' is not a valid classifier.</title>
 </head>
 <body>
  <h1>400 Invalid value for classifiers. Error: Classifier 'License :: WTFPL' is not a valid classifier.</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
Invalid value for classifiers. Error: Classifier &#x27;License :: WTFPL&#x27; is not a valid classifier.


 </body>
</html>
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for classifiers. Error: Classifier 'License :: WTFPL' is not a valid classifier.
```

**Comment by merwok** [comment]
The doc here: https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-classifier
leads to the list of valid classifiers: https://pypi.org/classifiers/
which surprisingly does not include WTFPLv2

**Comment by erzoe** [comment]
thank you very much, that link is very useful. Not only for licenses, I have also found a matching topic and environment there. I didn't even know such classifiers existed.

I have decided to go with [0BSD](https://choosealicense.com/licenses/0bsd/) instead and declare it as `License :: OSI Approved :: BSD License`. That may be somewhat ambiguous but better than nothing I suppose.

**Comment by KOLANICH** [comment]
>which surprisingly does not include WTFPLv2

WTFPL v2 is not OSI approved, so not under `License :: OSI Approved ::` . But since proprietary ones live under just `License ::` and since WTFPL is a public domain-like, I guess it should be `License :: Public Domain :: WTFPLv2`.

**Comment by layday** [comment]
"Public Domain" is not a category and no other licenses should inhabit it.  It is specifically for releasing something in the public domain.

Please open an issue or a PR at https://github.com/pypa/trove-classifiers if you'd like to add a WTFPL classifier, but note that at least one other PR for a license classifier is [blocked](https://github.com/pypa/trove-classifiers/pull/35#issuecomment-647047311) pending resolution of [PEP 639](https://www.python.org/dev/peps/pep-0639/), which is also blocked for lack of a PEP delegate.

**Comment by layday** [comment]
> How should users deal with that if the license they want to use is not allowed?

Classifiers are not exhaustive. If your license is not listed that doesn't mean that it's not allowed. There exists a free-form ["license" field](https://packaging.python.org/en/latest/specifications/core-metadata/#license).

**Comment by layday** [comment]
I'll close this now but feel free to open an issue if you face any other problems :)
