### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by Shahaf-Yagoda** [pypa/packaging-problems#569]
### Problem description

I've got python install already, and while I'm trying to install 'pip' in the command prompt this is the massage return 
"Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases."
I'll be happy to get some help please.
thank you.

**Comment by merwok** [comment]
Does it work if you run the `py` launcher (not `python`)?

If positive, then try `py -m pip`

**Comment by Shahaf-Yagoda** [comment]
First, thank you for your comment. 
It worked when I ran py, but when I ran py -m pip it shows this massage  "File "<stdin>", line 1
    py -m pip
          ^
SyntaxError: invalid syntax"

**Comment by merwok** [comment]
It seems that you run the second py command inside the python interpreter — you have to exit, it is a system command!
