### ISSUE TITLE
ModuleNotFoundError after packaging and installation

### ISSUE THREAD

**Issue by pfeiffer-dev** [pypa/packaging-problems#575]
### Problem

Hey, I've been trying to get my python program to run as a package for two days, but it keeps showing the same error.
I am creating a pypi package for the first time and have followed the ["Packaging Python Projects" ](https://packaging.python.org/en/latest/tutorials/packaging-projects/).
Everything has worked well so far, except for this error when testing the package.

### Error
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.9/site-packages/stock-report/__main__.py", line 9, in <module>
    import data
ModuleNotFoundError: No module named 'data'
```
### Setup.py
```python
from setuptools import setup, find_packages
import pathlib

here = pathlib.Path(__file__).parent.resolve()

long_description = (here / 'README.md').read_text(encoding='utf-8')

setup(
    name='stock-report',
    version='0.0.13',
    description='StockReport is a Phyton program that allows you to simply create an automated PDF report about a stock.',
    long_description=long_description,
    long_description_content_type='text/markdown',
    url='https://github.com/pfeiffer-dev/stock-report',
    author='Kevin Pfeiffer',
    author_email='pfeiffer.kevin@gmx.de',
    classifiers=[ 
        'Development Status :: 5 - Production/Stable',
        'Topic :: Office/Business :: Financial :: Investment',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
        'Natural Language :: English',
    ],
    keywords='stock-market, pandas, pdf, report, fpdf, alpha-vantage, plotly-express',
    packages=find_packages(),
    py_modules=['data', 'analysis', 'pdf'],
    python_requires='>=3.6',
    install_requires=[
        'alpha-vantage',
        'pandas',
        'fpdf',
        'plotly'
    ],
    include_package_data=True,
    package_data={ 
        'resources': [
            'resources/bb.png',
            'resources/dpc.png',
            'resources/footer.png',
            'resources/header.png',
            'resources/logo.png',
            'resources/macd.png',
            'resources/md.png',
            'resources/rsi.png',
            'resources/sma.png',
            ],
    },
    project_urls={ 
        'Bug Reports': 'https://github.com/pfeiffer-dev/stock-report/issues',
        'Source': 'https://github.com/pfeiffer-dev/stock-report',
    },
)
```

### Code

You can see my full code on GitHub or install it with pip install stock-report. You can find the links below.
**PyPI:** [pypi.org/project/stock-report/ ](https://pypi.org/project/stock-report/)
**GitHub:** [github.com/pfeiffer-dev/stock-report ](https://github.com/pfeiffer-dev/stock-report)

**Thanks for helping...**

**Comment by merwok** [comment]
You should not add package sub-modules in `py_modules`, that list is for standalone (top-level) modules.

**Comment by pfeiffer-dev** [comment]
> You should not add package sub-modules in `py_modules`, that list is for standalone (top-level) modules.

Thanks @mework, I also tested it without "sub-modules" and the same error occurred.

**Comment by abravalheri** [comment]
Hi @pfeiffer-dev,

There is a couple of things that deviate a bit from a standard packaging that might be causing the problem.

1. As @merwok mentioned, all the modules in your package should (ideally) be scoped to a single top-level. So I would simply remove `py_modules` and trust that `packages=find_packages(exclude=["examples.*"])` will do the right job.
2. Although `stock-report` is a fine name for PyPI, your folder would be better if named as `stock_report`. This is a Python limitation, for using it in `import` statements you need all the modules and packages to be valid Python identifiers (i.e. anything that you can use as a variable name).
3. It is necessary to re-write your import statements, considering all the modules belong to a single top-level package, you need to use:

```python
from stock_report import data  # explicit
# OR
from . import data  # relative
```

**Comment by pfeiffer-dev** [comment]
> Hi @pfeiffer-dev,
> 
> There is a couple of things that deviate a bit from a standard packaging that might be causing the problem.
> 
> 1. As @merwok mentioned, all the modules in your package should (ideally) be scoped to a single top-level. So I would simply remove `py_modules` and trust that `packages=find_packages(exclude=["examples.*"])` will do the right job.
> 2. Although `stock-report` is a fine name for PyPI, your [local folder](https://github.com/pfeiffer-dev/stock-report/tree/main/stock-report) would be better if renamed as `stock_report`. This is a Python limitation, for using it in `import` statements you need all the modules and packages to be valid Python identifiers (i.e. anything that you can use as a variable name).
> 3. It is necessary to re-write your import statements, considering all the modules belong to a single top-level package. You need to use:
> 
> ```python
> from stock_report import data  # explicit
> # OR
> from . import data  # relative
> ```

Thank you very much @abravalheri. It works now.

**Comment by abravalheri** [comment]
I will close this issue then! Nice to know that things are working 😄
