### ISSUE TITLE
Successfully installed mypackage | python3 -c 'import mypackage' ModuleNotFoundError: No module named 'mypackage'

### ISSUE THREAD

**Issue by mikelkou** [pypa/packaging-problems#579]
### Problem description

I have published a package in PyPi and I can install it successfully but when I try to import it in a script it gives me the error of:
ModuleNotFoundError: No module named 'mypackage'

which mypackage
/usr/local/bin/mypackage

I have checked package-sites, python versions, if it runs locally but it has no problem.
I cannot find any reason not to be able to import it.

**Comment by merwok** [comment]
A Python package can contain 0 or more scripts, 0 or more modules, 0 or more packages (module with sub-modules), 0 or more data files.

What kind of files do you have in your project?
How do you make the package for PyPI?
What is the PyPI project name?

**Comment by mikelkou** [comment]
Hi, Thaks for your reply.

I followed the tutorial here: https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-setup-py to build teh package.

So, I have everything described there. It has only one module basically.

I found out with the command:
ls -ltrh /usr/local/lib/python3.9/site-packages  
that I don't have a folder with the package. Only mypackage-0.2.0.dist-info.

Do you know why, if that is the problem and how can I fix it? (for all the users)
PyPI project name: favapy

**Comment by abravalheri** [comment]
Hi @mikelkou, the tutorial uses the configuration:

```ini
[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src
``` 
This requires all your package files that you need to distribute to be placed at a `src` folder in the root of your repository. Can you confirm that is the case?

Alternatively if your project has just a `favapy.py` file inside of the project root, you can also specify:

```ini
[options]
packages = favapy
# No need of package_dir if your module lives in the root of the repo.
```

**Comment by mikelkou** [comment]
Do you think something is wrong here:

package_dir =
    = favapy
packages = find:
python_requires = >=3.7

[options.entry_points]
console_scripts =
    favapy = favapy.fava:main

[options.packages.find]
where = favapy

**Comment by abravalheri** [comment]
I would say that is very likely (but without having a look on the source code I cannot be sure).

For example

```ini
package_dir =
= favapy

[options.packages.find]
where = favapy
```

Look very unconventional to me.

The usual approach is either one of the 2 options:

a) a `flat-layout` with the toplevel folder of your package (e.g. `favapy`) directly under the project root.
   In this case you don't need a `package_dir`, and for `[options.packages.find]` I would probably use `include = favapy*` instead of `where`.

b) a `src-layout`, i.e.:
   ```
   src/
      favapy/
          otherfiles...
   ```
   In this case, you can use the exact same configuration presented in the tutorial.

**Comment by mikelkou** [comment]
Indeed it was my layout. I fixed it as src-layout and now it works. :D 

Thank you. I was really stack.
