### ISSUE TITLE
getting error: command errored out with exit status 1: when installing rioxarray

### ISSUE THREAD

**Issue by MMon27** [pypa/packaging-problems#590]
### Problem description

I am trying to install rioxarray in anaconda prompt but I got an error as in below picture, it showed "getting requirements to build wheel..error" and "no module named wrapt". I made sure to check "wrapt" is installed and it is satisfied.
Could anyone please help me solve this? Thank you.

![error installing rioxarray](https://user-images.githubusercontent.com/104421747/166408154-318c4b07-1b41-425e-b91d-1935753aa425.png)

**Comment by henryiii** [comment]
They don’t provide wheels and conda doesn’t really support building binaries via pip very well. They need to either provide a conda package or they need to provide wheels (such as with cibuildwheel).

You can try using `--no-build-isolation` which will avoid the separate build environment and will see your version of wrapt.

**Comment by MMon27** [comment]
@henryiii Thank you Mr. Schreiner. I found the conda installation command "conda install -c conda-forge rioxarray", but when I run the script, it still gives "ModuleNotFoundError: No module named 'rioxarray".

**Comment by MMon27** [comment]
@henryiii I run the conda package in a new environment, it works now after choosing the interpreter the new environment. Thanks.
