### ISSUE TITLE
no access to main email anymore

### ISSUE THREAD

**Issue by julianascencio** [pypa/packaging-problems#591]
### Problem description

Hi team,

Unfortunately, I don't have access to my former institutional email: julian.ascencio@fe.uni-lj.si, and this repository has been created with it: https://pypi.org/project/pvweathermaps/

Could you please re assign it to this email: julian.ascencio.vasquez@gmail.com	

Thank you in advance,
Julian

**Comment by merwok** [comment]
PyPI support requests use this tracker: https://github.com/pypa/pypi-support/issues/new?labels=account-recovery&template=account-recovery.yml&title=Account+recovery+request
