### ISSUE TITLE
Clipping a netcdf file with Shapefile in Anaconda produces NaN values

### ISSUE THREAD

**Issue by MMon27** [pypa/packaging-problems#592]
### Problem description

I want to clip my netcdf file with the shapefile, the script I run is as below.  But my clipped data when I check with Panoply gives the dtr values all NaN. I attached the screenshot here.

Please enlighten me on how I can solve this one. Thanks much.

==================================================================================
import xarray
import rioxarray
import geopandas
from shapely.geometry import mapping

xds = xarray.open_dataset("dtr_MON_climpact.sample_historical_NA_1970-1989.nc", drop_variables='time_bnds')
xds.rio.write_crs("EPSG:4326", inplace=True)
geodf = geopandas.read_file("Chauk_BD.shx")

clipped = xds.rio.clip(geodf.geometry.apply(mapping), geodf.crs,drop=False)
clipped.to_netcdf('my clipped data 1.nc')
![NaN values](https://user-images.githubusercontent.com/104421747/166650695-db4e1179-1def-439b-83d2-6c69ecdf194c.png)

**Comment by merwok** [comment]
This is not a packaging problem, you should find a support forum for xarray and ask there.

**Comment by layday** [comment]
Closing as per above :)
