### ISSUE TITLE
Trouble with a packaging tutorial

### ISSUE THREAD

**Issue by Whoeza** [pypa/packaging-problems#595]
### OS version

Windows 10

### Python version

Python 3.10.1

### Pip version

pip 22.1.2

### Guide link

https://packaging.python.org/en/latest/tutorials/packaging-projects/

### Problem description

From the package page on PyPI, clicking on Download Files and trying to download any of them yields an error `SignatureDoesNotMatch` with message `The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.`
(From the terminal, `py -m pip install package_name` returns a couple errors,  but they might be connected to the above.)

### Error message

```text
After clicking on Download Files from the package page on PyPI:

<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
</Message>
<StringToSign>
GET Thu, 02 Jun 2022 21:50:17 GMT /pypi-files/packages/b2/ba/37f32331b479e4dbbfd5420a2f409625e417a54128947126a7b02c057417/html-and-py-1.0.3.tar.gz
</StringToSign>
</Error>


From terminal, after `py -m pip install package_name`,

ERROR: HTTP error 403 while getting https://files.pythonhosted.org/packages/7b/45/b877b0f82958f8bec0021d4c564853697a300270c07ff45285c4f33c278f/html_and_py-1.0.3-py3-none-any.whl#sha256=d45c27458d698c968b26b077dbffa9acc26286de5719a3d9ded104b9c2aa90da (from https://pypi.org/simple/html-and-py/) (requires-python:>=3.6)
ERROR: Could not install requirement html-and-py from https://files.pythonhosted.org/packages/7b/45/b877b0f82958f8bec0021d4c564853697a300270c07ff45285c4f33c278f/html_and_py-1.0.3-py3-none-any.whl#sha256=d45c27458d698c968b26b077dbffa9acc26286de5719a3d9ded104b9c2aa90da because of HTTP error 403 Client Error: Forbidden for url: https://files.pythonhosted.org/packages/7b/45/b877b0f82958f8bec0021d4c564853697a300270c07ff45285c4f33c278f/html_and_py-1.0.3-py3-none-any.whl for URL https://files.pythonhosted.org/packages/7b/45/b877b0f82958f8bec0021d4c564853697a300270c07ff45285c4f33c278f/html_and_py-1.0.3-py3-none-any.whl#sha256=d45c27458d698c968b26b077dbffa9acc26286de5719a3d9ded104b9c2aa90da (from https://pypi.org/simple/html-and-py/) (requires-python:>=3.6)
```

**Comment by Whoeza** [comment]
> @Whoeza How did you create and upload the sdists and wheels? As you mentioned, the files on PyPI are invalid(?) in some way
> 
> ```
> (venv) root@e122a3de6a52:/# python -m pip install html-and-py
> Collecting html-and-py
>   ERROR: HTTP error 403 while getting https://files.pythonhosted.org/packages/7b/45/b877b0f82958f8bec0021d4c564853697a300270c07ff45285c4f33c278f/html_and_py-1.0.3-py3-none-any.whl#sha256=d45c27458d698c968b26b077dbffa9acc26286de5719a3d9ded104b9c2aa90da (from https://pypi.org/simple/html-and-py/) (requires-python:>=3.6)
> ERROR: Could not install requirement html-and-py from https://files.pythonhosted.org/packages/7b/45/b877b0f82958f8bec0021d4c564853697a300270c07ff45285c4f33c278f/html_and_py-1.0.3-py3-none-any.whl#sha256=d45c27458d698c968b26b077dbffa9acc26286de5719a3d9ded104b9c2aa90da because of HTTP error 403 Client Error: Forbidden for url: https://files.pythonhosted.org/packages/7b/45/b877b0f82958f8bec0021d4c564853697a300270c07ff45285c4f33c278f/html_and_py-1.0.3-py3-none-any.whl for URL https://files.pythonhosted.org/packages/7b/45/b877b0f82958f8bec0021d4c564853697a300270c07ff45285c4f33c278f/html_and_py-1.0.3-py3-none-any.whl#sha256=d45c27458d698c968b26b077dbffa9acc26286de5719a3d9ded104b9c2aa90da (from https://pypi.org/simple/html-and-py/) (requires-python:>=3.6)
> ```
> 
> though if we clone your repo, `twine` validates the sdist and wheel that `build` makes
> 
> ```
> $ docker run --rm -ti python:3.10 /bin/bash
> root@b54975d0751d:/# python -m venv venv && . venv/bin/activate
> (venv) root@b54975d0751d:/# python -m pip --quiet install --upgrade pip setuptools wheel
> (venv) root@b54975d0751d:/# python -m pip --quiet install --upgrade build twine
> (venv) root@b54975d0751d:/# git clone https://github.com/Whoeza/html-and-py.git
> (venv) root@b54975d0751d:/# cd html-and-py/
> (venv) root@b54975d0751d:/html-and-py# git rev-parse HEAD
> 2251cc4054903dffe20e0fc5b5454bc2afd084d3
> (venv) root@b54975d0751d:/html-and-py# python -m build .
> (venv) root@b54975d0751d:/html-and-py# python -m twine check dist/*
> Checking dist/html_and_py-1.0.2-py3-none-any.whl: PASSED
> Checking dist/html-and-py-1.0.2.tar.gz: PASSED
> (venv) root@b54975d0751d:/html-and-py# python -m pip install ./dist/html_and_py-*.whl 
> Processing ./dist/html_and_py-1.0.2-py3-none-any.whl
> Installing collected packages: html-and-py
> Successfully installed html-and-py-1.0.2
> (venv) root@b54975d0751d:/html-and-py#
> ```
> 
> How did you make the files that are at https://pypi.org/project/html-and-py/1.0.2/ ?

Hi @matthewfeickert and thanks for the quick reply.

To create the build files, I simply typed in the package root folder, the command:

`py -m build`

This will generate the files in the dist/ folder inside the package root.

With those files, I launched the Twine command:

`py -m twine upload dist\*1.0.2*`

And received a green success message.

**Comment by dstufft** [comment]
https://status.python.org/incidents/bt0tzq7x2fk2

**Comment by matthewfeickert** [comment]
@Whoeza I think you should follow https://github.com/pypa/warehouse/issues/11500 as it seems that they're taking care of it there.

**Comment by Whoeza** [comment]
Thank you guys!

**Comment by Whoeza** [comment]
Fixed: https://github.com/pypa/warehouse/issues/11500#issuecomment-1145415572

It is resolved for me now.

**Comment by lgedgar** [comment]
Works for me too - thanks very much!

**Comment by holdenweb** [comment]
Shouldn't this issue be closed, given that the situation has been diagnosed in a post mortem and rectified?
