### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by suyunovfarrux4544** [pypa/packaging-problems#600]
### OS version

Ubuntu 20.04

### Python version

python 3.8.10

### Pip version

 pip-22.1.2

### Problem description

 HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                                                                                                
         User 'suyunovfarrux4544' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.

### Error message

what can i do in that case

**Comment by merwok** [comment]
The error message is telling you: add an email address to your account and verify it.

**Comment by suyunovfarrux4544** [comment]
> Does it work now?

Yes

**Comment by henryiii** [comment]
Great!

**Comment by suyunovfarrux4544** [comment]
Thanks to everyone I found a solution, I need to confirm the email address
