### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by BlackEvildoer** [pypa/packaging-problems#603]
### OS version

Windows 10

### Python version

python --3.10.5

### Pip version

python -m pip --version

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

By BlackEvildoerXD

### Error message

```text
Eror.pip not installed
```

**Comment by merwok** [comment]
Can you run `python -m ensurepip` then retry?
