### ISSUE TITLE
Intents and Entities are not returned

### ISSUE THREAD

**Issue by LavanyaGeetha** [pypa/packaging-problems#608]
### Problem description

Hi Team,

I have developed a lu model using the Azure Cognitive Services and have installed pyluis on my local Jupyter notebook and tried to call the model by providing model url and query text as needed but I am unable to see any intents or entities in the result. I am also not getting errors except blank intents and entities as a result.

Ex - print (r.intents)
[ ]
print (r.entities)
[ ]

I need your help in fixing this issue and getting the intents and entities in the result.

Thanks,
Lavanya.

**Comment by merwok** [comment]
Hello,

This github group and this repository in particular is about python packaging tools.
For support about the pyluis library, you should ask on a support forum of the pyluis team.

Good luck!
