### ISSUE TITLE
package resources with hatch/hatchling

### ISSUE THREAD

**Issue by greyltc** [pypa/packaging-problems#618]
### Problem description

I'm trying to migrate my project to hatch/hatchling which I guess is the new de facto standard, (right?) but I can't figure out how to package [resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources). I'd like to be able to load a resource at runtime using [`importlib.resources.read_text()`](https://docs.python.org/3/library/importlib.html#importlib.resources.read_text)

**Comment by merwok** [comment]
There are proper standards are documented at https://packaging.python.org/en/latest/ — thanks to this long work there isn’t a de facto standard build tool anymore, you are free to use hatch or flit or setuptools or another one.

Flit is very nice for simple projects, Hatch is recommended in tutorial, etc.

How have you tried to package resource files?
I have searched the docs and not found the info.  I might expect hatch to just include data files present in the python packages.  Does that work?

@ofek this is a bug report for hatchling docs more than packaging-problems I think

**Comment by henryiii** [comment]
FYI, I would not recommend Flit for simple projects, Flit is quite difficult to use correctly. If you use standards based tooling like `pipx run build`, you'll not get the right files in the SDist or the wheel. You have to provide explicit include/exclude lists, and Flit still hasn't released support for recursive expressions like `**.pyc` or `"**/__pycache__"`, and does not exclude things like that by default! Also the author explicitly doesn't want it recommended.

If you use the `flit` tool itself, then it uses `git` to compute these things, but not if you follow standards.

Hatchling is no harder to use, and uses your `.gitignore` to exclude files, so tends to do the right thing out of the box. And it doesn't change behavior to try to force you to use its own tooling (hatch).

**Comment by henryiii** [comment]
Oh, and I believe the answer to this is hatchling includes resources by default. It includes everything that is not ignored by your git ignore by default in `src/<package_name>` or `<package_name>`. But @ofek can confirm.

**Comment by merwok** [comment]
I did mean to recommend flit (in a personal capacity), not flit-core used via pypa-build.

**Comment by henryiii** [comment]
Okay, but then that means that you are making a package that has invalid configuration for standard tooling, that _only_ uses `flit` and can't use `pypa-build`. Or `pip install <repo>`, `pip wheel <repo>`, or things like https://github.com/hynek/build-and-inspect-python-package correctly.

**Comment by ofek** [comment]
Yes as mentioned this works OOTB.

**Comment by layday** [comment]
I think this is resolved.
