### ISSUE TITLE
CNVpytor

### ISSUE THREAD

**Issue by Anitha1993-hash** [pypa/packaging-problems#621]
### Problem description

Hello everyone,

Can we use CNVpytor for the detection of CNVs in Plasmodium falciparum genome? or it is Human specific tool? If yes Please suggest me other tools for the CNV detection for Plasmodium.

Thanks,
Anitha

**Comment by merwok** [comment]
I think you’re asking in the wrong place — this is a repo to note problems with software packaging tools in Python, not a forum for genetics question.  Good luck finding one!
