### ISSUE TITLE
invalid wheel name: 'apache_beam2.42.0rc00-cp37-cp37m-macosx_10_9_x86_64.whl'

### ISSUE THREAD

**Issue by zoranveljkovic** [pypa/packaging-problems#623]
### OS version

Ubuntu 18.04

### Python version

Python 3.7.14

### Pip version

pip 21.1.3

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

After command:
!python setup.py build
!python setup.py install
I receive error

### Error message

```text
File "/usr/local/lib/python3.7/dist-packages/setuptools/wheel.py", line 57, in __init__
    raise ValueError('invalid wheel name: %r' % filename)
ValueError: invalid wheel name: 'apache_beam2.42.0rc00-cp37-cp37m-macosx_10_9_x86_64.whl'
```

**Comment by pfmoore** [comment]
The project name and version should be separated with a `-`. Whatever tool you used to create the wheel is creating incorrectly named wheels, you need to report that to them.

**Comment by RobMcKiernan** [comment]
I'm experiencing this too, here's the issue on apache beam's github https://github.com/apache/beam/issues/23433

**Comment by layday** [comment]
Please follow the linked issue.
