### ISSUE TITLE
Specifying optional dependencies based on Python version

### ISSUE THREAD

**Issue by daenney** [pypa/packaging-problems#63]
Fairly often you need some dependency on older Python versions but not on newer. For example, scandir for Python pre 3.5, or asyncio if you're on Python 3.3 instead of 3.4.

It's currently possible to do so in `setup.py` but requires a bit of trickery with matching against `sys.version` and I have no idea how this affects wheels.

It would be nice to have a single directive, perhaps a second option that can be passed along with the version that allows you to restrict dependency installation based on `> >= < <= ==` a Python version. Preferably that will take a string and correctly match against `sys.version` or something better.

**Comment by ncoghlan** [comment]
PEP 508 formally defined Environment Markers to cover this: https://www.python.org/dev/peps/pep-0508/#environment-markers

**Comment by pganssle** [comment]
@ncoghlan Can we close this then?

**Comment by ncoghlan** [comment]
Indeed! I think I originally didn't close it because tool support for the PEP 508 syntax was still a bit sketchy last year, whereas it's pretty solid now.
