### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by waxcruzcoder** [pypa/packaging-problems#639]
### OS version

macOS Ventura Version 13.0.1

### Python version

Python 3.9.5

### Pip version

pip 22.3.1

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

python3

from example_package_waxcruz import example
example.add_one(2)

### Error message

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'example_package_waxcruz.example' has no attribute 'add_one'
```

**Comment by merwok** [comment]
Can you share the code for this example package?

**Comment by waxcruzcoder** [comment]
Here's code. Thank you for helping me.

[PackMyRV.zip](https://github.com/pypa/packaging-problems/files/10375186/PackMyRV.zip)

**Comment by merwok** [comment]
OK!  To get help with a problem, you need to show the source code (code block in a message if small, or a github repo for many files), explain what you do and show the error message.

Here we’re still missing step 2: what did you do to see the AttributeError?  Your code does have a function `add_one` in the `example` sub-module, and the packaging info looks correct to include your source files and install them.  Did you install the sdist or wheel into a new virtualenv then try to import?

**Comment by waxcruzcoder** [comment]
I didn't use a new virtualenv. Is this a requirement?

**Comment by merwok** [comment]
It’s just the easiest way to test your package in isolation.  Could also be tox!

**Comment by waxcruzcoder** [comment]
User error on my part.
