### ISSUE TITLE
The Packaging Python Projects doesn't work

### ISSUE THREAD

**Issue by mohsenSy** [pypa/packaging-problems#640]
### OS version

Ubunt 20.04

### Python version

3.8.10

### Pip version

22.3.1

### Guide link

https://packaging.python.org/en/latest/tutorials/packaging-projects/

### Problem description

I followed all the instructions on the web page to create a new package but couldn't import the code after installing the package.

### Error message

```text
>>> from example_package_mouhsen import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'example_package_mouhsen'
```

**Comment by merwok** [comment]
Please give more info about your files and the commands you run.

Did you create a `example_package_mouhsen` package?
Did you refer to it in setup.py?
Did you install it into a clean location?

**Comment by mohsenSy** [comment]
I just followed the instructions using a docker image for python 3.11 and it worked this time, I'm not sure what was wrong with my previous setup on my laptop directly, sorry I'll close this and add comments later if I find the previous bug in my code.

My current code is here now https://gitlab.com/hash-platform/core

**Comment by merwok** [comment]
That code is not for `example_package_mouhsen`, so we can’t find what the problem was.  (BTW your packages are missing `__init__.py`) 

If you have more issues, please give: project layout, setup (and/or pyproject) file, commands run, error message.  Thanks!
