### ISSUE TITLE
SomePackage==1.2.3

### ISSUE THREAD

**Issue by doomroep5** [pypa/packaging-problems#647]
### OS version

windows1064bits

### Python version

python -m pip install --upgrade pip

### Pip version

python -m pip install --upgrade pip SomePackage==1.2.3

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

python -m pip install --upgrade pip SomePackage==1.2.3

### Error message

```text
python  -m pip install --upgrade pip SomePackage==1.2.3
```

**Comment by merwok** [comment]
Hello, you haven’t answered most of the questions!

What versions are you using, what is it you’re trying to do, what is the error?
