### ISSUE TITLE
Not able to install hnswlib

### ISSUE THREAD

**Issue by Sunil-1234** [pypa/packaging-problems#648]
### Problem description

When i try to install hnswlib for chromadb i got error , then i install microsoft builder again, getting same errror while all module is updated 
Building wheels for collected packages: hnswlib
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build hnswlib
ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based projects

**Comment by matthewfeickert** [comment]
@Sunil-1234 I would suggest that you open up this issue with the project itself on https://github.com/nmslib/hnswlib. The `pypa/packaging-problems` issue tracker isn't designed to help fix other projects packaging. 

Admins, please close this Issue.

**Comment by gilbertfullah** [comment]
I'm also having this same problem when trying to install chromadb. I have search all over internet for a solution, but I still can't find one.

**Comment by henryiii** [comment]
Looks like you need to install MSVC. You can’t build code on Windows without a compiler like MSVC.

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Sunil-1234** [comment]
yes, i installed latest version of Microsoft Visual C++ , and then chromadb installed successfully

**Comment by Taznain06** [comment]
@Sunil-1234   Could you please provide a detailed explanation of the steps you took to install Chromadb? I'm encountering a similar issue and would appreciate your guidance.

**Comment by Sunil-1234** [comment]
> @Sunil-1234 Could you please provide a detailed explanation of the steps you took to install Chromadb? I'm encountering a similar issue and would appreciate your guidance.

i just installed microsoft visual c++ latest version and then issue resolved.

**Comment by hskhawaja** [comment]
> > @Sunil-1234 Could you please provide a detailed explanation of the steps you took to install Chromadb? I'm encountering a similar issue and would appreciate your guidance.
> 
> i just installed microsoft visual c++ latest version and then issue resolved.

How did you install? I'm installing it via vs_BuildTools but no luck.

**Comment by nickjuntilla** [comment]
Yeah it doesn't install on a mac either

**Comment by prabhudevguntur** [comment]
Installing through conda worked for me

conda install -c conda-forge hnswlib

**Work around Docker file ...**

FROM ubuntu:latest

## Update the package lists
RUN apt-get update

## Install the necessary dependencies
RUN apt-get install -y curl build-essential cmake libboost-all-dev git python3.9

## Install Conda
RUN curl -sSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh && bash /tmp/miniconda.sh -bfp /usr/local && rm -rf /tmp/miniconda.sh
ENV PATH="/usr/local/bin:${PATH}"
RUN conda update conda

## Copy requirements.txt to the container
COPY requirements.txt .

## Set environment variables
ENV HNSWLIB_NO_NATIVE=1

## Install Python packages
RUN conda install -c conda-forge hnswlib

## Install Homebrew
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

## Add Homebrew to PATH
ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"

## Install libmagic from Homebrew
RUN brew install libmagic

**Comment by anastasiaxuejing** [comment]
try  'conda install -c conda-forge hnswlib ' if you use conda environment!
BTW， running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by sunilkumardash9** [comment]
How to do it on Linux? Any idea

**Comment by TtTTTtTeee** [comment]
I am with conda environment, so run 'conda install -c conda-forge hnswlib', and it worked and added hnswlib on conda list.
But when I run 'pip install chromadb', it still got an error: ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based project

I created another clone that uses python 3.10, then 'pip install chromadb' worked straight away - Not sure if this info helps but this is what happened in my case.

**Comment by sms03** [comment]
> yes, i installed latest version of Microsoft Visual C++ , and then chromadb installed successfully

what version u install can u tell me??

**Comment by queerputin** [comment]
If you have older versions of visual studio tools, it might work if you uninstall them and then install the newest. That seemed to work for me.

**Comment by ja-818** [comment]
For everyone who doesn't know how to make it work with pip, those are the steps I followed to do it.
I'm putting this in really easy clear steps as I know many people are just starting coding to try out chromadb with LangChain, so sorry if it seems too obvious:
1. Go to this page: https://visualstudio.microsoft.com/visual-cpp-build-tools/
2. Click on "Download Build Tools" and run what you downloaded
3. Click on "Install" (a window with different options to click should show up)
4. Click only on "Desktop Development with C++" and click on install (image for reference)
5. Reboot your system
6. try "pip install chromadb" again, it should work
![i1](https://github.com/pypa/packaging-problems/assets/95070226/b1ea217e-3e91-4b2d-b707-0683f0933ed5)

**Comment by AhmadBakdash** [comment]
How to solve the problem and download it on Mac?

**Comment by AhmadBakdash** [comment]
> How to solve the problem and download it on Mac?

Try setting an environment variable:
`export HNSWLIB_NO_NATIVE=1 `
And then retry...

...this helped me

**Comment by manuelrech** [comment]
Any suggestion for ubuntu 20.04?

**Comment by bryceschultz** [comment]
> For everyone who doesn't know how to make it work with pip, those are the steps I followed to do it. I'm putting this in really easy clear steps as I know many people are just starting coding to try out chromadb with LangChain, so sorry if it seems too obvious:
> 
> 1. Go to this page: https://visualstudio.microsoft.com/visual-cpp-build-tools/
> 2. Click on "Download Build Tools" and run what you downloaded
> 3. Click on "Install" (a window with different options to click should show up)
> 4. Click only on "Desktop Development with C++" and click on install (image for reference)
> 5. Reboot your system
> 6. try "pip install chromadb" again, it should work
>    ![i1](https://user-images.githubusercontent.com/95070226/238103017-b1ea217e-3e91-4b2d-b707-0683f0933ed5.png)

I'm running on windows 11 and originally python 3.10 and tried the above steps but chromadb install was still failing. In addition to the above steps I had to install python 3.9.12 and point my path to python 3.9.12 and the chromadb install then worked. Python installation files can be found here: https://www.python.org/downloads/windows/

**Comment by Sreekiranar** [comment]
I was getting the same issue in MacOS. My issue was resolved when I upgraded the Python version from 3.8 to 3.11.

**Comment by Sreekiranar** [comment]
> I was getting the same issue in MacOS. My issue was resolved when I upgraded the Python version from 3.8 to 3.11.



> How to solve the problem and download it on Mac?

I was getting the same issue in MacOS. My issue was resolved when I upgraded the Python version from 3.8 to 3.11.

**Comment by Aditya1399** [comment]
It is not running even after installing visual studio c++ on windows

**Comment by Aditya1399** [comment]
I HV tried the above mentioned export command also

**Comment by jweinstock-git** [comment]
To install hnswlib, the only solution that woked for me (on Docker) is to use conda: 

conda install -c conda-forge hnswlib

To install chromadb (or any other package with dependency on hnswlib) install it without dependency:
1. install all the other dependencies except hnswlib manually 
2. pip install chromadb --no-deps

**Comment by mananmani1** [comment]
Solution at my end:
I installed MSVS installer in my machine after installation a new window has shown by MSVS installer to select the visual studio build tools then after selecting this ,so in the this way installation and downloading of packages will took place side by side.

link for MSVS installer:         https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by tkni2005** [comment]
Solved like this https://github.com/imartinez/privateGPT/issues/445#issuecomment-1685057620

**Comment by Shubhamtomar123** [comment]
> @Sunil-1234 I would suggest that you open up this installation issue with the project itself on https://github.com/nmslib/hnswlib. The `pypa/packaging-problems` issue tracker isn't designed to help fix other project's packaging unless they come with questions on how their procedure is going wrong.
> 
> Admins, please close this Issue.

simple download another python entrepreneur and issue will be resolved

**Comment by TheArtifulProgrammer** [comment]
I downgraded my Python version from 3.12 to 3.11. and it solved the issue for me.  Downloading MSVS  build tools didn't work

**Comment by semiautomatix** [comment]
> For Ubuntu try following commands: `sudo apt install python3-dev` `sudo apt-get install build-essential -y`

Just a note here, ensure you match your python version if using deadsnakes PPA, for example:

 `sudo apt install python3.12-dev` `sudo apt-get install build-essential -y`

**Comment by esakkiappan444** [comment]
> > yes, i installed latest version of Microsoft Visual C++ , and then chromadb installed successfully
> 
> what version u install can u tell me??

**Python Version 3.12 Not Working** 
some days before i'm facing same issue that time i have python version 3.9 after i will install Microsoft Visual studio and that Development C++ and working fine

- [ ] Now I have Python version 3.12 Not working  , Now i have installed Microsoft Visual code and  Development C++ 
- [ ] Not working!

So use python v3.9,v3.10 or v3.11
Python v3.12 Not workng

**Comment by tunacinsoy** [comment]
For those who are using ubuntu 24.04+, following command solved the problem for me:
```bash
sudo apt-get install libomp-dev 
````
