### ISSUE TITLE
Words package not installing

### ISSUE THREAD

**Issue by shawnmcpeek** [pypa/packaging-problems#649]
### Problem description

I am trying to install the 'words' package and I get the following error.
I type: pip install words
It says:
Collecting words
  Using cached words-0.0.1.tar.gz (2.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in words setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I am really new to all of this. Any help and guidance is appreciated. I am running Windows 11.

**Comment by henryiii** [comment]
That package was last updated in 2013 and uses the `2to3` functionality that was removed a few years ago (see https://github.com/Ceasar/words/blob/4ef67ba6cca6fe5cfe67b068080a67d23e991908/setup.py#L30). You should find the source for the package (https://github.com/Ceasar/words) and update it for modern Python (you might need an older Python to run the 2to3 tool). I'm not sure the author is still around, but you could try to make a PR to see.
