### ISSUE TITLE
Updating a package

### ISSUE THREAD

**Issue by BubbleBubblePlayz** [pypa/packaging-problems#650]
### Problem description

I have a python script (that may be outdated) that compiles and uploads my package to pypi.org when I run it, but I have had trouble updating a package. Here is my folder tree:
![image](https://user-images.githubusercontent.com/107481819/223873922-84f84c46-1c34-4386-942e-06600f235b80.png)

**Comment by BubbleBubblePlayz** [comment]
nevermind, I fixed it

**Comment by merwok** [comment]
Good!  For your next ticket, please take care to give enough details about what you are doing and what problem or error message you are seeing.  «had trouble» is not enough for people to help.
