### ISSUE TITLE
Trouble with releasing the newer version of library

### ISSUE THREAD

**Issue by Tony14261** [pypa/packaging-problems#671]
### OS version

Windows 11

### Python version

Python 3.11.2

### Pip version

pip 23.1.2

### Guide link

https://packaging.python.org/en/latest/tutorials/packaging-projects/

### Problem description

I tried to publish my library the latest version but it said that the name already exists. I already changed the version of the project to a newer version but I still got the same error message

### Error message

```text
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for more information.
```

**Comment by henryiii** [comment]
Did you leave the old file in the dist folder then try to upload everything in dist, perhaps? You didn’t report exactly what you did in the issue, so can’t do better than guess.

**Comment by grandell1234** [comment]
Hello, try to change the version in pyproject.toml so it recognizes it as an update.

**Comment by Tony14261** [comment]
Thanks for all the helps! I've solved the issue and it works properly now.
