### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by SpeedyGo55** [pypa/packaging-problems#682]
### OS version

Win 11

### Python version

Python 3.11.4

### Pip version

pip 23.1.2

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

I followed the tutorial and uploaded it to test.pypi.org and succesfully installed my Package, but when I try to import it it gives me a Module Not Found Error. I made Sure it is installed with the same interpreter as i imported it but still nothing

### Error message

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cardstacks'
```

**Comment by merwok** [comment]
Can you give some info:
- link to the project on TestPyPI
- the command you used to install and its output
- output of `python -m site` (or python3 or py depending on what you use)

**Comment by SpeedyGo55** [comment]
Link: https://test.pypi.org/project/CardStacks/
I used the command from the tutorial.
The Output was the same as with other packages. No errors

**Comment by SpeedyGo55** [comment]
Got it working. I Used a setup.py and [this](https://betterscientificsoftware.github.io/python-for-hpc/tutorials/python-pypi-packaging/) tutorial.

**Comment by SpeedyGo55** [comment]
Got it Working. I used an Setup.py and [this](https://betterscientificsoftware.github.io/python-for-hpc/tutorials/python-pypi-packaging/) tutorial.
