### ISSUE TITLE
PyODBC -- No MS-Access Driver

### ISSUE THREAD

**Issue by ZotAlan** [pypa/packaging-problems#704]
### Problem description

Python 3.11.0
Win10 64bit
PyODBC

PIP installed PyODBC.   In Python and making a call to MS-Access get:  Error in Adding Data ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)'

Used pyodbc.drivers() which returned only SQL Server.    The above error makes sense, but where is the MS-Access driver?  

Thanks,
Argh.  :-)

**Comment by merwok** [comment]
I don’t know pyodbc or msaccess, but this does not seem like a Python packaging problem.
I suggest finding an issue tracker or support forum for these projects and asking there! Good luck 🙂

**Comment by ZotAlan** [comment]
Thanks.   You're right.  Somehow, thought I was in that area.  Must've gone click happy and gotten confused.
