### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by Hosna-abolhasani** [pypa/packaging-problems#707]
### OS version

12.4

### Python version

python 3.9.6

### Pip version

pip 23.3.1

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

i canot write my password

### Error message

```text
Registering nester to https://upload.pypi.org/legacy/
Server response (410): Project pre-registration is no longer required or supported, upload your files instead.
```

**Comment by merwok** [comment]
The problem description does not match the error message. It seems that you are using a `register` command, which has been deprecated for years and is not in the guide. Please follow the advice in the error message and only upload.
