### ISSUE TITLE
I can't register in pypi.org but I register in test.pypi.org

### ISSUE THREAD

**Issue by amirgard0** [pypa/packaging-problems#710]
### Problem description

I click the register button and it gives me an Error: "New user registration temporarily disabled. See https://pypi.org/help#admin-intervention for details. "
It's about 4 days and it is not fixed. 
in test.pypi.org I upload a project.

**Comment by sinoroc** [comment]
there is a statement here: https://status.python.org/

**Comment by JINO-ROHIT** [comment]
when will this be resolved?

**Comment by sinoroc** [comment]
@JINO-ROHIT The resolution date is written on the incident report.

**Comment by JINO-ROHIT** [comment]
resolved now, thanks
