### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by fauzisabran** [pypa/packaging-problems#720]
### OS version

Windows Version 10.0.22621.3007

### Python version

Python 3.12.0

### Pip version

pip 23.3.2

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

python running without output

### Error message

```text
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search). Please use https://pypi.org/search (via a browser) instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.
```

**Comment by pfmoore** [comment]
Does the error message not give you the information you need? It seems fairly self-explanatory to me.

**Comment by webknjaz** [comment]
XML-RPC has been removed from PyPI entirely.
