### ISSUE TITLE
pip subprocess to install build dependencies did not run successfully.

### ISSUE THREAD

**Issue by akinolaemmanuel49** [pypa/packaging-problems#721]
### Problem description

When trying to install the packaged library from test.pypi I get the following error.
```
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://test.pypi.org/simple/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

pyproject.toml
```
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "quest_maker_api_shared_library"
version = "0.0.2"
authors = [
    { name = "User Name", email = "username.example.com" },
]
description = "This package contains code shared by the Quest Maker microservices."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    # "bson==0.5.10",
    # "pydantic==2.5.3",
    # "PyJWT==2.8.0",
    # "pytest==7.4.4",
    "bson",
    "pydantic",
    "PyJWT",
    "pytest",
]
```

**Comment by sinoroc** [comment]
Test PyPI probably does not have the dependencies required for this operation. Test PyPI is not meant for this. You can check that the packaging metadata displays correctly on test PyPI before uploading to the real PyPI, and a bunch of limited other tests, but it is unlikely that test PyPI has all the dependencies needed to run a full "pip install" command, especially if a build step is required.

**Comment by akinolaemmanuel49** [comment]
Thanks, just tried it on PyPi and it works.

**Comment by Chuina12** [comment]
pip install --upgrade pip

**Comment by kamlesh-cegis** [comment]
(myenv) ubuntu@ip-172-31-35-19:~$ use : python.exe -m pip install --upgrade pip
Command 'use' not found, did you mean:
  command 'muse' from deb muse (4.2.1-1)
  command 'nse' from deb ns2 (2.35+dfsg-5)
  command 'ase' from deb ase (3.22.1-3)
  command 'fuse' from deb fuse-emulator-gtk (1.6.0+dfsg1-2)
  command 'fuse' from deb fuse-emulator-sdl (1.6.0+dfsg1-2)
Try: sudo apt install <deb name>

**Comment by henryiii** [comment]
Don’t prefix with `use : `, also you are on Linux so it’s “python” not “python.exe” (you should be able to skip the `.exe` on Windows too)

**Comment by merwok** [comment]
Don’t report the same thing in two issues!

**Comment by sshinde-se** [comment]
I got same error as below and **resolved the error after downgrading pip version from 24.1.2 to 22.1.0**. I am using python 3.11

```
`Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Looking in links:
      WARNING: Location '' is ignored: it is either a non-existing path or lacks a specific scheme.
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.`
```

**Comment by VincentOracle** [comment]
The [ast](https://docs.python.org/3/library/ast.html) page you linked is part of the Python standard library. You don't need to pip install anything to use it. Just import ast. The [ast pip package](https://pypi.org/project/AST/) you're downloading is unrelated and last released in 2017 so it's probably just broken.

**Comment by umairchanna57** [comment]
try this issue will be resolved
**pip install python-dotenv**

**Comment by kaizenkudo** [comment]
> try this issue will be resolved **pip install python-dotenv**

thanks it worked

**Comment by VincentOracle** [comment]
It is okay,,I have noted the error

**Comment by merwok** [comment]
Open a separate ticket for your specific problem.
Find the log file that pip tells you about and look at it, if you don’t see the solution then attach it to your ticket.

@henryiii can you lock this ticket?
