### ISSUE TITLE
fftw is not threadsafe

### ISSUE THREAD

**Issue by pstaten** [pypa/packaging-problems#723]
### Problem description

Hi! I learned - after using a pool to run stockwell simultaneously a few dozen times – that planner.c is not threadsafe. Is there a straightforward way to perform a stockwell analysis on multiple files simultaneously in parallel without trashing the .fftwisdom file?

**Comment by jeanas** [comment]
@pstaten This is the repository for a Python project template. It is likely that you're using a project where the author started with this template and forgot to update the project URLs. Please ask about your problem to the package author directly.
