### ISSUE TITLE
Labyrinth

### ISSUE THREAD

**Issue by BluCorbel31** [pypa/packaging-problems#724]
I have developed a defense system that automates encryption and decryption using watchdog and other libraries that because of systems event manager and observer can be used in conjunction with IDS and network scanners for times of breaches all with the def my handler (vast amount of parameters):
Please find my links below. 
There are videos on my YouTube channel for instructions if needed because of who you are I didn't want to insult you.

[](https://youtube.com/@TheMadHattersPlayground?si=BHEcHJV84AsG3pE0)

Please tell whoever developed the watchdog library they are a legend. 
Below is just the basic architecture this will be developed further and sold hopefully make money for me, PyPi and Python. This can also be developed in other languages but I did it in python as you the one I like as using this in conjunction with rust actually causes serious damage to the attacker rips up log files so rust up is understood and then encrypts them. 🤣🤣

[](https://github.com/BluCorbel31/RansomwareandRelease-/blob/main/ubuntu%2FLabyrinthReadMe.txt)

[](https://github.com/BluCorbel31/RansomwareandRelease-/blob/main/ubuntu%2FLabyrinth.py)

I'm not so sure about you but a python PyPi branded defense system sounds like money to me.
Many thanks,
@TheMadHattersPlayground.com,
CEO/Director/Founder,
Blu Corbel.

**Comment by jeanas** [comment]
The purpose of PyPI definitely isn't to endorse particular packages.
