### ISSUE TITLE
QGraphicsView() of PyQt6 or PyQt5 doesn't have canvas and the y axis is inverted, why?

### ISSUE THREAD

**Issue by DerrazRadhwane** [pypa/packaging-problems#728]
### Problem description

When set QGraphicsScene() as item into QGraphicsView() of PyQt5, 
1. the Y axis of the Scene is inversted, even if scale x and y, when dislaying images in the scene will be inversted.
2. The QGraphicsView() doesn't have canvas, cannot display dynamic xy grid, even when doing that using QGraphicsLin() and add them to scene, the grid of QGraphicsItem type, which i dont want it for some other use limitations.
3. Is  is possible to set x y to the normal state like xy cartesian system?
4. Is it possible to ass grid, ruler as built-in attributes to QGrphicsScene()?

**Comment by merwok** [comment]
I thinks this is the wrong forum! Your question should be asked in a PyQt support forum.
