### ISSUE TITLE
 HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/  

### ISSUE THREAD

**Issue by eyukselen** [pypa/packaging-problems#731]
### Problem description

I am getting " The user 'eyukselen' isn't allowed to upload to project 'xxx' " for a project name I found that is really short (3 letters) and not coming up as an existing package in pypi search and i want to use that name.  how  can I proceed? I can upload for other project names or same 3 letter project to test pypi.

**Comment by merwok** [comment]
Some names are prohibited. PEP 541 is the policy. At the moment there is no published list of names: https://github.com/pypi/warehouse/issues/4703

**Comment by jeanas** [comment]
Among possible reasons, PyPI has protection against typosquatting, by refusing to create packages with names very similar to existing ones.

You will need to rename your package, sorry.

**Comment by eyukselen** [comment]
thanks for quick response. sadly I am giving up on that awsome name  - (it will go to grave with me which was not a typo close to something else I believe) becuase of pep 541 section 305 paragraph 4.

**Comment by eyukselen** [comment]
thanks for quick response. sadly I am giving up on that awsome name - (it will go to grave with me which was not a typo close to something else I believe) becuase of pep 541 section 305 paragraph 4.

**Comment by merwok** [comment]
Out of curiosity, what are you calling section 305?

**Comment by eyukselen** [comment]
just a joke :D sorry.
