### ISSUE TITLE
Trouble with a packaging tutorial

### ISSUE THREAD

**Issue by ChnS-99** [pypa/packaging-problems#739]
### OS version

20.06

### Python version

3.8.10

### Pip version

24.0

### Guide link

https://packaging.python.org/en/latest/tutorials/packaging-projects/

### Problem description

Followed all the steps as mentioned in the article, but when trying to upload the files under "dist" using twine getting error. I have tried various commands

- python3 -m twine upload --repository testpypi dist/*
- twine upload dist/*
- twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
- twine upload -u YOUR-USERNAME -p YOUR-PASSWORD - repository-url https://test.pypi.org/legacy/ dist / *

it's not working and getting error.

### Error message

```text
Uploading distributions to https://test.pypi.org/legacy/
Enter your API token: 
Uploading addition_trial-0.0.1-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 kB • 00:00 • ?
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 403 Forbidden from https://test.pypi.org/legacy/            
         Invalid or non-existent authentication information. See                
         https://test.pypi.org/help/#invalid-auth for more information.
```

**Comment by merwok** [comment]
Do you enter an API token (created on Test PyPI) when you are prompted to?

**Comment by webknjaz** [comment]
TestPyPI has a separate account that requires getting a separate token.
