### ISSUE TITLE
I am not able to install packages from Python using pip

### ISSUE THREAD

**Issue by akashbuchi11** [pypa/packaging-problems#746]
### Problem description

Hello,
I haven't been able to download the requests package using the pip install command. I have checked its version and every other recommendation that I could have found on the web. However, it still shows the error :

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001E64478F080>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/requests/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001E64422D850>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/requests/

**Comment by sinoroc** [comment]
You have network connectivity issues.

**Comment by akashbuchi11** [comment]
Is it because I am connected to company's VPN?

**Comment by woodruffw** [comment]
A company's VPN or firewall is almost always the issue in this kind of scenario. Please coordinate with your company's IT to ensure that connections to PyPI are either not interfered with or are proxied/interposed correctly internally.
