### ISSUE TITLE
Latex rendering issue for project's README on PyPI website

### ISSUE THREAD

**Issue by tlunet** [pypa/packaging-problems#773]
### Problem description

Hi, I've recently uploaded a small package on PyPI for computational mathematics : [qmat](https://pypi.org/project/qmat/)

The main [README.md file](https://github.com/Parallel-in-Time/qmat/blob/main/README.md) contains some base formula using the latex `array` environment, that are rendered correctly on GitHub :

![image](https://github.com/pypa/packaging-problems/assets/12183839/a9e371e7-5124-414f-9e59-197281561c6b)

 but not on the PyPi website :

![image](https://github.com/pypa/packaging-problems/assets/12183839/04c6ea62-38fd-44fb-b9a8-24f6d09c1962)

Since PyPI markdown format is supposed to follow the format used by Github, I don't know if this is a bug with the current PyPI interface, or a formatting problem during packaging ?

> Don't know if this is where I should open this issue, hope that is the right place.

Thanks in advance for any help :smiley: 

PS : [pyproject.toml of the package](https://github.com/Parallel-in-Time/qmat/blob/main/pyproject.toml)

**Comment by sinoroc** [comment]
Bugs and feedback for PyPI: https://pypi.org/help/#feedback

> PyPI markdown format is supposed to follow the format used by Github

Is that true? I did not know that. Where did you get this info?

**Comment by tlunet** [comment]
https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

**Comment by sinoroc** [comment]
> > PyPI markdown format is supposed to follow the format used by Github
> 
> Is that true? I did not know that. Where did you get this info?

I guess I found my answer: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#creating-a-readme-file

**Comment by sinoroc** [comment]
Probably that "_[GitHub Flavored Markdown](https://github.github.com/gfm/)_" means it supports the same syntax or uses the same parser[^1], but it does not necessarily means that it supports the same plugins/integrations (such as Latex).

[^1]: for a very long time, there was no standard specification for Markdown just a reference implementation, and technically there still isn't a specification, there is one for a Markdown-similar language: CommonMark), but

**Comment by tlunet** [comment]
I does render correctly any other formula, for instance if I don't use the `array` environment and some `\\` characters for new rows ... seems that mathjax plugin is reading `\` instead of `\\` due to some strange text formatting ...

**Comment by tlunet** [comment]
Closed as opened in the right place : https://github.com/pypi/warehouse/issues/16134
