### ISSUE TITLE
V

### ISSUE THREAD

**Issue by Intekai** [pypa/packaging-problems#774]
### Problem description

The number of houses is wrong when generating the SVG file, e.g. it puts bull in house 8 ms the correct one is house 9.

**Comment by jeanas** [comment]
This issue tracker is about installing and distributing Python packages. For general Python questions, ask on https://discuss.python.org/c/users/7 and include all the details of your problem and your code.

**Comment by Intekai** [comment]
The problem is not python the code works it is the result that is wrong.

**Comment by merwok** [comment]
You are not in the right place to report this
