### ISSUE TITLE
Asistencia 

### ISSUE THREAD

**Issue by Barrz417** [pypa/packaging-problems#793]
https://github.com/Barrz417/gpt-computer-assistant/commit/43cafe387af25080d5ca53b774b49af21e1ae9ad

**Comment by abravalheri** [comment]
To be able to help we need a complete description that explains what trouble the user is getting.
I recommend adding the error messages and stack traces to the issue text.
Adding a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) is even better and in some cases fundamental...
