### ISSUE TITLE
Visiting https://pypa.io/ gives an error: "Error code: sec_error_expired_certificate"

### ISSUE THREAD

**Issue by hamzasheikh** [pypa/packaging-problems#81]
Firefox is showing this message:

pypa.io uses an invalid security certificate. The certificate expired on 12/12/15, 3:59 PM. The current time is 12/16/15, 4:27 PM. (Error code: sec_error_expired_certificate)

https://www.pypa.io/ is fine.

**Comment by hickford** [comment]
Oh yes https://pypa.io/

**Comment by daenney** [comment]
This is probably fallout when it was switched to using Fastly for the content. www.pypa.io has a certificate handed out to Fastly which is certified for both pypa.io and *.pypa.io. Though it's being used and presented for www.pypa.io, pypa.io doesn't point to Fastly. It's apparently still using the old infrastructure and serving an old, and now expired, certificate:

```
11:27:54 ~ $ host pypa.io
pypa.io has address 207.97.239.79
pypa.io has IPv6 address 2001:4802:7901::e60a:1375:0:7
pypa.io mail is handled by 10 in1-smtp.messagingengine.com.
pypa.io mail is handled by 20 in2-smtp.messagingengine.com.
11:27:56 ~ $ host www.pypa.io
www.pypa.io is an alias for c.global-ssl.fastly.net.
c.global-ssl.fastly.net has address 23.235.43.175
```

**Comment by brainwane** [comment]
Per pypa/pypa.io#21 there's currently an SSL problem but it's *different*, I believe.

**Comment by ewdurbin** [comment]
Same issue. Resolved! This will use LetsEncrypt! from now on.
