### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by sivasarans** [pypa/packaging-problems#817]
### OS version

windows 11

### Python version

3

### Pip version

pip 24.0

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

module import error / module not found
https://pypi.org/project/subseq-tamil/0.1.0/
pip install subseq-tamil==0.1.0

### Error message

```text
module not found
```

**Comment by henryiii** [comment]
You've named your file `subsequence.py.py`, it should have only one `.py`.

Please include a bit more of the error message next time, that would likely have clarified a bit.

**Comment by sivasarans** [comment]
Thanks for your faster reply, I corrected it and now works good.
