### ISSUE TITLE
Failed building wheel for mpi4py

### ISSUE THREAD

**Issue by Ujjwal10228** [pypa/packaging-problems#823]
### Problem description

![Error_message](https://github.com/user-attachments/assets/5155074c-9347-4b91-a6c4-3794b6758670)

Failed to built setup for pynuml on Ubunto even on following the guidlines of pynuml library page.

**Comment by henryiii** [comment]
You need to install MPI. The instructions are part way down in the image. `sudo apt install <some MPI implementation>`.

Next time, please copy and paste text instead, inside triple tick marks, like this:

````
```
some unformatted text
```
````
