### ISSUE TITLE
Error (500) when uploading sdists to PyPI

### ISSUE THREAD

**Issue by sloria** [pypa/packaging-problems#83]
Today I've been getting 500 errors when trying to upload sdist tarball distributions to PyPI.

I attempted to upload using twine, with the following commands:

```
python setup.py register sdist bdist_wheel
twine upload dist/*
```

And got the following error:

```
Uploading distributions to https://pypi.python.org/pypi
Uploading marshmallow-2.7.1-py2.py3-none-any.whl
HTTPError: 500 Server Error: Internal Server Error for url: https://pypi.python.org/pypi
```

I haven't seen this error prior to today.

**Comment by sloria** [comment]
As you can see on https://pypi.python.org/pypi/marshmallow/2.7.1 and https://pypi.python.org/pypi/apispec/0.10.0, the wheel distributions were successfully uploaded, but the sdists were not.

**Comment by sloria** [comment]
Seems like the issue may have resolved itself? I haven't been able to reproduce the issue, and I've successfully uploaded packages.

**Comment by ianmiell** [comment]
https://bitbucket.org/pypa/pypi/issues/217/upload-failed-500-internal-server-error

**Comment by xapple** [comment]
PyPI just seems to be under too heavily load since a couple weeks ? I keeps giving random 500 errors.

**Comment by ianmiell** [comment]
Still appears down - trying python-infra on freenode - surely others must be depending on this too?

**Comment by xapple** [comment]
Yeah it's strange because it's been having problems for a while now, but https://status.python.org always reports that everything is good. It's a mystery ?
