### ISSUE TITLE
Unclear (impossible?) to add header files to a setup.py Extension

### ISSUE THREAD

**Issue by pjz** [pypa/packaging-problems#84]
An existing package, dvdread, ('pip3 install dvdread') fails to install for me because it's missing a header file.  "Oh, that's probably a typo, I'll fix it and submit a PR," I say, unsuspectingly.  

...and then I got lost in a maze of twisty documentation, all different.  I'm not the only one:

http://stackoverflow.com/questions/6633624/how-to-specify-header-files-in-setup-py-script-for-python-extension-module

has pointers to a similar story.... and no clear, correct, answer.

**Comment by hickford** [comment]
I agree the documentation is lacking https://python-packaging-user-guide.readthedocs.io/en/latest/extensions/



I followed http://stackoverflow.com/questions/16854066/using-distutils-and-build-clib-to-build-c-library for my project https://github.com/hickford/primesieve-python/blob/v0.1.0/setup.py

    extension = Extension(
            "primesieve",
            ["primesieve/primesieve.cpp"],
            include_dirs=["lib/primesieve/include", "lib/primesieve/include/primesieve"],
            language="c++",
            )

**Comment by hickford** [comment]
What's the exact error message?

Reading https://github.com/cmlburnett/PyDvdRead/blob/master/setup.py it sets `include_dirs = ['/usr/include']`. Have you installed the [libdvdread-dev package](http://packages.ubuntu.com/xenial/amd64/libdvdread-dev/filelist) for your distro? The Python library looks for `/usr/include/dvdread/dvd_reader.h` 
https://github.com/cmlburnett/PyDvdRead/blob/master/src/dvdread.h

**Comment by pjz** [comment]
I do have libdvdread-dev installed; but the error is:
```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=1 -I/usr/include -I/usr/include/python3.5m -I/tmp/t1/include/python3.5m -c src/dvdread.c -o build/temp.linux-x86_64-3.5/src/dvdread.o
    src/dvdread.c:1:21: fatal error: dvdread.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
...which is looking for *dvdread.h*, which isn't being packaged up when you do `python setup.py sdist`.  Note you should be able to repro on most any x86 linux box by doing:

```
virtualenv --python=python3 /tmp/dtest
/tmp/dtest/bin/pip install dvdread
```
...and then watch it fail.

I also cloned that source repo down and then did `python setup.py sdist` and then inspected the result with `tar tzvf dist/dvdread-1.1.tar.gz` and to see
```
drwxrwxr-x pj/pj             0 2016-05-25 08:22 dvdread-1.1/
drwxrwxr-x pj/pj             0 2016-05-25 08:22 dvdread-1.1/src/
-rw-rw-r-- pj/pj         57766 2016-05-24 19:42 dvdread-1.1/src/dvdread.c
drwxrwxr-x pj/pj             0 2016-05-25 08:22 dvdread-1.1/dvdread/
-rw-rw-r-- pj/pj         14439 2016-05-24 19:42 dvdread-1.1/dvdread/objects.py
-rw-rw-r-- pj/pj          3292 2016-05-24 19:42 dvdread-1.1/dvdread/__init__.py
-rw-rw-r-- pj/pj          3195 2016-05-24 19:42 dvdread-1.1/README
-rw-rw-r-- pj/pj           376 2016-05-25 08:22 dvdread-1.1/PKG-INFO
-rw-rw-r-- pj/pj           817 2016-05-25 08:21 dvdread-1.1/setup.py
```
which, you'll note, does not include `src/dvdread.h`, the missing file in question.  So the question is now: how should one ship header files with your C extension?  In my naivete, I thought I could just add it to the `sources` keyword when creating the Extension in `setup.py`, and while that causes it to be put into the package, when one tries to install said package, you end up with:
```
  Running setup.py bdist_wheel for dvdread ... error
  Complete output from command /home/pj/src/PyDvdRead/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-c71nl4en-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpj0tsl4v5pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/dvdread
  copying dvdread/__init__.py -> build/lib.linux-x86_64-3.5/dvdread
  copying dvdread/objects.py -> build/lib.linux-x86_64-3.5/dvdread
  running build_ext
  building '_dvdread' extension
  error: unknown file type '.h' (from 'src/dvdread.h')
```
So that fails to install as well.

**Comment by hickford** [comment]
You're right `dvdread.h` is left out the sdist

I believe which files end up in the sdist is determine by the MANIFEST or MANIFEST.in file http://python-packaging-user-guide.readthedocs.io/en/latest/distributing/#manifest-in

**Comment by hickford** [comment]
Try changing setup.py to use setuptools rather than distutils

    from setuptools import setup, Extension

**Comment by pjz** [comment]
Using setuptools, the .h does indeed make it into the sdist, but it still doesn't install correctly:
```
pj@trireme:~/src/PyDvdRead$ ./env/bin/pip install dist/dvdread-1.1.tar.gz 
Processing ./dist/dvdread-1.1.tar.gz
Building wheels for collected packages: dvdread
  Running setup.py bdist_wheel for dvdread ... error
  Complete output from command /home/pj/src/PyDvdRead/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-h6dmzmwm-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp62yphtnjpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/dvdread
  copying dvdread/__init__.py -> build/lib.linux-x86_64-3.5/dvdread
  copying dvdread/objects.py -> build/lib.linux-x86_64-3.5/dvdread
  running build_ext
  building '_dvdread' extension
  error: unknown file type '.h' (from 'src/dvdread.h')
  
  ----------------------------------------
  Failed building wheel for dvdread
  Running setup.py clean for dvdread
Failed to build dvdread
Installing collected packages: dvdread
  Running setup.py install for dvdread ... error
    Complete output from command /home/pj/src/PyDvdRead/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-h6dmzmwm-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r_p7kd9r-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pj/src/PyDvdRead/env/include/site/python3.5/dvdread:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/dvdread
    copying dvdread/__init__.py -> build/lib.linux-x86_64-3.5/dvdread
    copying dvdread/objects.py -> build/lib.linux-x86_64-3.5/dvdread
    running build_ext
    building '_dvdread' extension
    error: unknown file type '.h' (from 'src/dvdread.h')
    
    ----------------------------------------
Command "/home/pj/src/PyDvdRead/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-h6dmzmwm-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r_p7kd9r-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pj/src/PyDvdRead/env/include/site/python3.5/dvdread" failed with error code 1 in /tmp/pip-h6dmzmwm-build/
```

**Comment by nschloe** [comment]
Like [many](https://stackoverflow.com/questions/6633624/how-to-specify-header-files-in-setup-py-script-for-python-extension-module) [others](https://bitbucket.org/blais/beancount/src/ccb3721a7811a042661814a6778cca1c42433d64/setup.py?fileviewer=file-view-default#setup.py-36), I've also bumped into this problem. My workaround: I copied all header files into one big `src/all.cpp`, and ship that. Works, but isn't pretty.

**Comment by st-pasha** [comment]
It's a quarter-past-2018 already, and this problem still remains at large? 

I tried the following, and it still didn't work (with python 3.6.0):
* Upgrading to the latest `setuptools` (39.0.1) and `pip` (10.0.1)
* Importing `Extension` from `setuptools` rather than from `distutils.core`
* Specifying `include_dirs` parameter when constructing the `Extension` object
* Specifying `depends` parameter when constructing the `Extension` object to the explicit list of header files that need to be included.

----

What did work was the following workaround:
```
def get_c_sources(folder, include_headers=False):
    """Find all C/C++ source files in the `folder` directory."""
    allowed_extensions = [".c", ".C", ".cc", ".cpp", ".cxx", ".c++"]
    if include_headers:
        allowed_extensions.extend([".h", ".hpp"])
    sources = []
    for root, dirs, files in os.walk(folder):
        for name in files:
            ext = os.path.splitext(name)[1]
            if ext in allowed_extensions:
                sources.append(os.path.join(root, name))
    return sources

setup(
    ...
    ext_modules=[
        Extension(
            ext_name,
            include_dirs=["c"],
            sources=get_c_sources("c", include_headers=(sys.argv[1] == "sdist")),
        ),
    ]
)
```
So in essence when `setup.py` is called in "sdist" mode I'm pretending that my headers are the sources. In all other modes I use the normal list of C sources.

**Comment by njsmith** [comment]
> It's a quarter-past-2018 already, and this problem still remains at large?

I read the thread and I actually can't tell what "this problem" is :-). I believe that:

* you should include your header files in the sdist by setting up MANIFEST.in
* you should not include the header files in the `sources=` kwarg
* you should include the header dir in the `include_dirs=` kwarg

Does that not work?

**Comment by pjz** [comment]
That is in fact not working.  The [project](https://github.com/cmlburnett/PyDvdRead) has a MANIFEST.in that says:
```
include README
include setup.py
recursive-include dvdread *.py
recursive-include src *.c *h
```
I'm a little unsure if the `include_dirs` value is correct; it's `['/usr/include']`

**Comment by st-pasha** [comment]
@pjz I think in your case the problem is that you have `*h` instead of `*.h`

@njsmith I managed to make the `MANIFEST.in` file work, although it took quite some effort. The major problem with MANIFEST.in is that this feature lacks clear documentation. At first I found [this one](https://docs.python.org/3.6/distutils/sourcedist.html), and it seemed pretty good. However the page says "Legacy version". The presumed [modern version](https://docs.python.org/3.6/distributing/index.html) of the same document lacks any information on manifests. The [packaging tutorial](https://packaging.python.org/tutorials/distributing-packages/) has a paragraph, with links to the "legacy version" mentioned above. The [setuptools documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html) says you don't need any MANIFEST.in at all. It even says
> ... be sure to ignore any part of the distutils documentation that deals with MANIFEST ...

Ok, so of all the documents that I found, the first "legacy" doc seemed the most comprehensive. "Maybe it's not too old", I thought. Turns out it is. More specifically, the `distutils` "sdist" command described in that doc is quite different from `setuptools` "sdist" command which is not described anywhere. They even claim the following in the docs:
> because setuptools’ approach to determining the contents of a source distribution is so much simpler, its sdist command omits nearly all of the options that the distutils’ more complex sdist process requires.

The problem with setuptools is that it includes by default certain files into the source distribution that must not be included (even if I have an explicit `MANIFEST.in` file); and at the same time fails to include the header files without which the distribution will fail to compile. There is no `--no-defaults` option. After some experimenting I found the only way to combat this behavior is to blacklist those files in the MANIFEST.in. I'm not sure whether this solution is future-proof, but it works for now.

I sure hope the documentation was more straightforward though!

**Comment by someburner** [comment]
> I sure hope the documentation was more straightforward though!

Agreed. Looking at docs, or even [the sample setup.py](https://github.com/pypa/sampleproject/blob/6a2444b88f48eaa1cf3a2f32fe8bbed8dad82801/setup.py#L154) would have you believe that `package_data` can handle this. I'm using `python3.6` and `package_data` would only include `.py` files, while c headers, `.h` would not work. I had to create `MANIFEST.in` with this:

```
include *.h
recursive-include *.h *.py
```

I will say I at least found it funny such a simple, basic, mind-numbing task is so complicated for poor `setuptools`.

**Comment by CallMeAlexO** [comment]
A solution that works for me, is one that was suggested on [this SO question](https://stackoverflow.com/a/8981036/5611506).

**Comment by moreati** [comment]
For future travellers, this can also happen if the `MANIFEST.in` is called something subtly different, e.g. `MANIFEST.IN` (note the case of .IN).

**Comment by ericzhng** [comment]
> A solution that works for me, is one that was suggested on [this SO question](https://stackoverflow.com/a/8981036/5611506).
> 
> ```
> setup(name='mypkg', ..., headers=['src/includes/header.h'])
> ```

Use headers work, thanks a lot! If I need to use headers from extern libraries in sdist, but not including the whole  extern library, is there any way to get around it?

**Comment by ericzhng** [comment]
> > I sure hope the documentation was more straightforward though!
> 
> Agreed. Looking at docs, or even [the sample setup.py](https://github.com/pypa/sampleproject/blob/6a2444b88f48eaa1cf3a2f32fe8bbed8dad82801/setup.py#L154) would have you believe that `package_data` can handle this. I'm using `python3.6` and `package_data` would only include `.py` files, while c headers, `.h` would not work. I had to create `MANIFEST.in` with this:
> 
> ```
> include *.h
> recursive-include *.h *.py
> ```
> 
> I will say I at least found it funny such a simple, basic, mind-numbing task is so complicated for poor `setuptools`.

Seems that using MANIFEST.in has no effect to sdist at all. Weird. Maybe I am doing something wrong.

**Comment by abravalheri** [comment]
> Seems that using MANIFEST.in has no effect to sdist at all

Hi @ericzhng , `MANIFEST.in` should work with `sdist` (reference: https://github.com/abravalheri/experiment-setuptools-package-data)

Maybe the problem is that the `MANIFEST.in` instructions are a bit problematic? Have you tried `global-include`?

**Comment by ericzhng** [comment]
@abravalheri use global-include works. If I just use the filename or wildcards, it doesn't work. I have to use package_data in setup to copy some header and md files.

**Comment by abravalheri** [comment]
Yeap, the instructions in `MANIFEST.in` are a bit difficult to grasp. A complete description is accessible in https://packaging.python.org/en/latest/guides/using-manifest-in/.

@ericzhng, I think you can obtain a reasonable result by ditching `MANIFEST.in` and using a VCS plugin like `setuptools-scm` or `setuptools-svn`, and a combination of `include_package_data=True` + `exclude_package_data`. Just note that by *data files* setuptools considers all non-Python files that are **inside** the package directory (not generally any file in your repository root).

**Comment by ericzhng** [comment]
@abravalheri Thanks. That is very helpful info for me. I have two other questions. 

I have my python files in a subfolder. When I run 'python setup.py sdist' / or 'py -m build', the python files are not packaged into .tar.gz file. I have to explicitly specify 'global-include src/*.py' to in MAINFEST.in to include them, is there a more elegant way to do so?

Second question is that when I "run pip install ." (in windows 10), the compiled .pyd files are all stored in build/lib.win-amd64-3.8, is there any way to make a copy of compiled .pyd file in my src subfolder, during the install process? Maybe a custom build_ext_class?

**Comment by ericzhng** [comment]
continuing my last, the reason for doing so is that this .pyd file will be explicitly needed in __init__.py. It is compiled from xxxx.pyx file. Basically it first generate a cpp file from .pyx, then into binary .pyd. Hope I am not confusing you.

**Comment by abravalheri** [comment]
> is there a more elegant way to do so?

Have you tried using `package_dir={"": "src"}`? There is documentation about this in: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#using-a-src-layout

I don't know if I understood the following questions, but I think that changing the `package_dir` configuration might also help with that...

**Comment by henryiii** [comment]
You never want binary files in your SDist, and very rarely will they be in your source folders. If you do an editable install (`pip install -e .`), the binary files will sit inside your source in the proper place for use locally. They should not show up there if you don't do an editable install.

**Comment by ericzhng** [comment]
> have my python files in a subfolder. When I run 'python setup.py sdist' / or 'py -m build', the python files are not packaged into .tar.gz file. I have to explicitly specify 'global-include src/*.py' to in MAINFEST.in to include them

Thanks for your answers. Weird, today I tried again, without package_dir, it was able to copy all py files to .tar.gz. Yesterday I guess it was broken. Also today, I cleaned up my setup.py a bit, and using MAINFEST.IN works like a charm. Sorry for not checking carefully.

**Comment by ericzhng** [comment]
> You never want binary files in your SDist, and very rarely will they be in your source folders. If you do an editable install (`pip install -e .`), the binary files will sit inside your source in the proper place for use locally. They should not show up there if you don't do an editable install.

Thanks. I didn't mean to copy pyd to sdist. I mean in build directory, .pyd file is outside the package. I want it to be moved inside the package. 

![image](https://user-images.githubusercontent.com/16161090/156693605-e25e0d11-35d8-4b1e-994d-aa6e894fd25e.png)

**Comment by ericzhng** [comment]
i guess never mind what I am asking. Moving it inside will distrub the module calling. I did the modification in "__init__.py", now it works fine. thanks!

**Comment by AdityaNPL** [comment]
Looks like C header files aren't recognised automatically by the setup-tools' default location algorithm.
The recommended solution is to use the  `MANIFEST.IN` file to specify which files should be pulled in.

ref:
https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html#controlling-files-in-the-distribution
