### ISSUE TITLE
bdist_wheel turns "_" into "-" inconsistently

### ISSUE THREAD

**Issue by janssen** [pypa/packaging-problems#85]
My setup.py says,

```
setup(name='goodstuff_v1',
      version='1.0',
```

But when I run bdist_wheel, I find this in metadata.json:

```
..."name": "goodstuff-v1", "provides": "goodstuff_v1 (1.0)", "version": "1.0"...
```

Where does that hyphen come from!?  And why is the "name" different from that in the "provides"?!

Python 2.7.11, wheel 0.29.0.

**Comment by McSinyx** [comment]
Hello there!  I'm a bit late to the party but I think this can be closed now.  As defined in [PEP 503](https://www.python.org/dev/peps/pep-0503/#normalized-names), `_` and `.` in names are to be normalized to `-`.
