### ISSUE TITLE
Pypi package size limit

### ISSUE THREAD

**Issue by yifeif** [pypa/packaging-problems#86]
Hi,

I'm running into the following issue when trying to twine upload a package around 80MB:
`HTTPError: 400 Client Error: distribution file too large for url: https://testpypi.python.org/pypi
`
What is the size limit for pypi package? Is there a way we can up the limit? Thanks.

**Comment by dstufft** [comment]
We can increase the limit on a package per package basis. I think the default limit is somewhere around 60MB? You'll have to upload to Warehouse (``upload.pypi.org/legacy/`` and ``test.pypi.org/legacy/``) instead of to current PyPI but it will still show up on both.

**Comment by yifeif** [comment]
Thanks @dstufft! Will I still be able to use twine or the upload process is completely different? 
I got the following by replacing with the given url,
`HTTPError: 404 Client Error: Not Found for url: https://testpypi.python.org/legacy`

**Comment by merwok** [comment]
The hostname in your error message is testpypi.python.org, but Donald’s message talks about test.pypi.org :)

**Comment by matham** [comment]
Our project has been waiting for this to be active but I hadn't realized this was already possible. How do we request a size increase for our project?

**Comment by dstufft** [comment]
@yifeif You can still use twine, but you need to use either ``https://test.pypi.org/legacy/`` or ``upload.pypi.org/legacy/`` for TestPyPI or PyPI (note the domain and trailing slash). You would also need to tell me the name of your project and why you need it increased (e.g. large image files, lots of compiled .so's, whatever) if you want the file size limit increased for that project.

@matham You can just ask me for one in this issue or via email or whatever. I just need to know the name of the project and why you need it increased (e.g. large image files, lots of compiled .so's, whatever).

**Comment by matham** [comment]
@dstufft that's great! 

The project name is `kivy.deps.gstreamer` https://pypi.python.org/pypi/kivy.deps.gstreamer. It's a dependency of the [kivy](https://github.com/kivy/kivy/) project and is used by the kivy project for video. The reason for the large size is that it includes all the gstreamer binaries and plugin dlls.

Currently we host it on our site and it's about 120MB. However,could you increase the limit to around 150MB in case the gstreamer distribution gets larger?

Thanks!

**Comment by yifeif** [comment]
Thanks @merwok and @dstufft! I was totally using the wrong sites :)

May I get a file size limit increased to 100MB for project 'tensorflow-gpu' https://pypi.python.org/pypi/tensorflow-gpu? It is currently at around 85MB.
In additional to the normal tensorflow package,  it has much bigger .so for all the GPU supports. Thanks!

**Comment by yifeif** [comment]
@dstufft gentle ping on the file size increase request. Much appreciated!

**Comment by dstufft** [comment]
Okay, I've set ``kivy.deps.gstreamer`` to 150MB and ``tensorflow-gpu`` to 100MB. Note: This will *only* take affect when uploading to the new site at ``https://upload.pypi.org/legacy/``, but the change will be reflected in both the old and the new site.

**Comment by yifeif** [comment]
Was able to upload to https://upload.pypi.org/legacy/ just now. Thanks so much @dstufft! 

One more request, can we have the same size increase at https://test.pypi.org/legacy/ as well?

**Comment by dstufft** [comment]
@yifeif done!

**Comment by yifeif** [comment]
Awesome. Thanks again for all your help @dstufft  :)

**Comment by matham** [comment]
@dstufft Thanks a lot!

**Comment by yifeif** [comment]
Hi @dstufft, we would like to expand tensorflow-gpu's support for more CUDA compute capabilities as mentioned in [this thread](https://github.com/tensorflow/tensorflow/issues/6914), which will cause our binary size to go up. Would it be possible to increase tensorflow-gpu size limit to 200MB? 
Sorry need to dig up this old thread and really appreciate the help!

**Comment by reuben** [comment]
Hi @dstufft,

We're trying to publish project deepspeech-gpu and are running into the same problem as tensorflow-gpu, as we also include a bunch of compiled libraries for CUDA support. Could you bump our limit to 200MB on upload.pypi.org and test.pypi.org?

Thanks!

**Comment by merwok** [comment]
New requests for different packages would need their own tickets.

**Comment by reuben** [comment]
Thanks. I filed #110

**Comment by HangJie720** [comment]
@dstufft! My Program is advanced tensorflow for edge computing, which is named as tensorflow-tflex, its size is 69.1M, could you increase the upload size limit? Thank you very much!
HTTPError: 400 Client Error: File too large. Limit for project 'tensorflow-tflex' is 60 MB. See https://test.pypi.org/help/#file-size-limit for url: https://test.pypi.org/legacy/

Package site: **https://pypi.org/project/tensorflow-tflex/#files**

**Comment by myhub** [comment]
@dstufft  My project is tr (https://pypi.org/project/tr/)
it is a deep learning based OCR system which include many .so files and big deep learning model parameter files(text line detect and text recognition), I want a size around 300Mb to store so many files, Thanks

**Comment by di** [comment]
Please open new issues for new limit requests.
