### ISSUE TITLE
file is uploaded to pypi but pip thinks it isn't when file is large

### ISSUE THREAD

**Issue by matham** [pypa/packaging-problems#87]
I have been encountering an issue when uploading large files to pypi. https://github.com/pypa/packaging-problems/issues/86 increased our size limit. However, when uploading a file that larger than the old limit this is what happens:

```
$ twine upload *
Uploading distributions to https://upload.pypi.org/legacy/
Uploading kivy.deps.gstreamer-0.1.12-cp36-cp36m-win32.whl
[================================] 121004467/121004467 - 00:00:46
Received "503: Service Unavailable" Package upload appears to have failed.  Retry 1 of 5
Uploading kivy.deps.gstreamer-0.1.12-cp36-cp36m-win32.whl
[================================] 121004467/121004467 - 00:00:24
HTTPError: 400 Client Error: File already exists. for url: https://upload.pypi.org/legacy/
```

It uploads the large file, which succeeds (as I verified manually on pypi), but it thinks it failed. Then it tries to upload again, but the file is already there so it fails the re-upload. This basically means that I need to upload the large files one by one as it fails after every one.

**Comment by dstufft** [comment]
This is going to be because the upload timed out waiting on a response while PyPI processed it. There's not a lot that can be done about it currently sadly.
