### ISSUE TITLE
PyPI size limit for ITK and SimpleITK

### ISSUE THREAD

**Issue by thewtex** [pypa/packaging-problems#88]
Hi,

Could the PyPI package size limit please be increased for ITK and SimpleITK?:

- https://pypi.python.org/pypi/itk
- https://pypi.python.org/pypi/SimpleITK

150 MB per package should be sufficient for the near future. These are large scientific packages:

- https://github.com/InsightSoftwareConsortium/ITKPythonPackage/releases/tag/latest
- https://sourceforge.net/projects/simpleitk/files/SimpleITK/1.0.0/Python/

Thank you!

CC: @dstufft @blowekamp @fbudin69500 @jcfr

**Comment by thewtex** [comment]
@dstufft , could the package size limit please be increased for these packages? Thank you!

**Comment by dstufft** [comment]
Sorry for the delay, both of these packages have been updated to allow 150MB each.

**Comment by blowekamp** [comment]
Thank you. For a second when I search PyPI, I was getting no results for SimpleITK/ITK, but all seems right now.
