### ISSUE TITLE
Do we hate Setuptools, Distribute, Disutils, or Distutils2?

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#9]
There have been a lot of failed starts, forks, etc in the packaging space. This has left users confused about what they should or shouldn't be using. We need a clear unified message.

**Comment by brainwane** [comment]
Now that the Python Packaging User Guide has moved to https://packaging.python.org/ , unless I am mistaken, we do have a clear unified message, or at least the skeleton of one, about what users should be doing. Therefore can we close this issue?

**Comment by ncoghlan** [comment]
Indeed, this has been resolved (at least at the core tools level)
