### ISSUE TITLE
PyPI size limit for PySpark

### ISSUE THREAD

**Issue by holdenk** [pypa/packaging-problems#90]
PySpark is a little under 200mb because it needs all of the Java parts of Spark with it to be usable. The Spark PMC publishes a pip installable package (which is currently used as the basis of a conda package), if it would be possible to get the file size limit increased for PySpark I would love to publish it on PyPI as well :)

**Comment by holdenk** [comment]
cc @rgbkrk

**Comment by rgbkrk** [comment]
Thanks for the CC, it would be good to see this able to be shipped on pypi.

**Comment by holdenk** [comment]
We could also work around this by allowing the file to be hosted on ASF infra if that would be easier, but I know that feature is deprecated so I figured file-size-limmit increase would be the best path forward.

**Comment by holdenk** [comment]
cc @dstufft

**Comment by dstufft** [comment]
I've increased the limit for pyspark to 250MB. Note, you'll need to use ``https://upload.pypi.org/legacy/`` as the upload URL *NOT* ``https://pypi.python.org/pypi`` for this limit to be honored.
