### ISSUE TITLE
PyPI test legacy size limit for mxnet packages

### ISSUE THREAD

**Issue by lxn2** [pypa/packaging-problems#91]
Hi @dstufft, as was done for the PyPI endpoints, could you help increase the size limit at the https://test.pypi.org/legacy/ endpoint for the following packages to 200mb?

`mxnet-cu75, mxnet-cu80, mxnet-cu75mkl, mxnet-cu80mkl`

The reason for the large package sizes is the size of the .so files that are shipped.

**Comment by dstufft** [comment]
Going to close this none of these projects exist on TestPyPI still. If you create them there feel free to reopen.
