### ISSUE TITLE
Pypi package size limit increase for TensorFlow GPU

### ISSUE THREAD

**Issue by yifeif** [pypa/packaging-problems#92]
There has been a lot of requests to expand TensorFlow's GPU build compute capability. @dstufft, could you help increase the limit for `tensorflow-gpu` to 200MB on both  https://upload.pypi.org/legacy/ and  https://test.pypi.org/legacy/?

Thanks in advance!

**Comment by dstufft** [comment]
Done.

**Comment by yifeif** [comment]
Thanks a lot @dstufft!
