### ISSUE TITLE
another size limit exception?

### ISSUE THREAD

**Issue by scottdraves** [pypa/packaging-problems#95]
I tried to upload a new python package with twine and got this error:
```
Uploading beakerx-0.1.0.dev0-py2.py3-none-any.whl
HTTPError: 400 Client Error: File too large. for url: https://upload.pypi.org/legacy/
```
Can we please get an exception to increase the size limit for this package?

Our wheel is 104MB, and will probably increase a bit over time.  It large because it includes a bunch of jars, as this package mostly consists of JVM kernels for Jupyter (https://github.com/twosigma/beakerx). It also has Python and JS, but it's the JARs that make it big.

We are planning to split it up into about 5 packages that will i think fit under the normal limit, but that is maybe a month away.

Thx

**Comment by dstufft** [comment]
You'll need to upload a small, dummy package first in order to get the name registered. Once you've done that I can increase the limit.

**Comment by scottdraves** [comment]
cool thx, will do & get back to you here.

**Comment by scottdraves** [comment]
ok here it is:
https://pypi.org/project/beakerx/

**Comment by dstufft** [comment]
Ok, you've been given a 150MB upload limit.

**Comment by scottdraves** [comment]
awesome, thank you!
