### ISSUE TITLE
Pypi package size limit exception for PyTorch

### ISSUE THREAD

**Issue by soumith** [pypa/packaging-problems#96]
Hi @dstufft 
Similar to https://github.com/pypa/packaging-problems/issues/92 , I'm requesting a size limit increase of the PyPI package `torch`'s wheels to 500MB. They stand at 444MB right now, and I am looking for a contingency buffer of an extra 46MB incase future releases grow unexpectedly.

The reason that our binaries are large is because:
1. we ship a lot of statically compiled CUDA kernels (80MB by themselves)
2. we depend on large other things: CUDA, CuDNN, etc. are quite large in dependencies.

If you could make an exception for us, I would be really grateful. We currently host and ship wheels via Amazon CDN, but it's a big ask from our users to ship simply as `pip install torch`. If there's anyway I can contribute to hosting costs for the binaries, I'm happy to do so.

**Comment by dstufft** [comment]
How often are you releasing torch?

**Comment by soumith** [comment]
once every 3 months.

**Comment by dstufft** [comment]
Would it be possible to have you shoot me an email at donald@python.org? I think we can do this, just want to run through a few things with you first.

**Comment by dstufft** [comment]
This has been updated and you should be able to release. If there's anything that you can do to keep the files smaller or move pieces that don't update as often into their own projects that would be appreciated.

**Comment by soumith** [comment]
Thank you so much Donald! much appreciated.

**Comment by soumith** [comment]
@dstufft Thanks to Warehouse, I am now able to upload wheels without having timeouts.
However, I run into "400 Client Error: File too large. Limit for project 'torch' is 60MB.", I wonder if the file size limit got reset somewhere. Can this be checked upon?
The actual package name is `torch` for the `PyTorch` project.

**Comment by di** [comment]
@soumith What is the difference between https://pypi.org/project/torch/ and https://pypi.org/project/pytorch/? It seems like the latter is the one that got the upload limit increase.

**Comment by soumith** [comment]
@di we created https://pypi.org/project/pytorch/ as a placeholder to give an error message if installed. The package name is `torch` and imported as `import torch`

**Comment by di** [comment]
@soumith OK, I've set the upload limit for `torch` on PyPI and TestPyPI to 500MB, and reset the limit for `pytorch` to 60MB. The same cautions about release frequency still apply, of course.
