### ISSUE TITLE
Can no longer edit package metadata on pypi.python.org

### ISSUE THREAD

**Issue by dhermes** [pypa/packaging-problems#97]
... and there is no edit button on warehouse.

When editing a package via

```
https://pypi.python.org/pypi?:action=submit_form&name={PKG}&version={VERSION}
```

and submitting by clicking the "Update Information" button, the end result is a 410 response with plaintext response

> Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)

----

## Why do I care?

Most PyPI packages I publish use the project `README` as the `long_description`, but a `README` typically has links / images that are tied to `master`, e.g.

- "build" status for CI
- RTD link (for `latest`)
- link to `LICENSE` file in repo

For some projects I have resorted to using a `README` template ([e.g.][1]) but in general, I have typically just worried about this after the fact by editing the package metadata in the UI. For example

-   swapping out a `master` LICENSE file
    ```
    https://github.com/{org}/{repo}/blob/master/LICENSE
    ```
    for the one specific to the `git` tag where the release was cut
    ```
    https://github.com/{org}/{repo}/blob/{TAG}/LICENSE
    ```
-   swapping out the generic "CI for the whole project"
    ```
    https://circleci.com/gh/{org}/{repo}
    ```
    for the specific build that was green for the tag build
    ```
    https://circleci.com/gh/{org}/{repo}/{SPECIFIC-BUILD-FOR-TAG}
    ```
-   swapping out the `latest` RTD
    ```
    https://{PKG}.readthedocs.io/en/latest/
    ```
    for the version-pinned docs specific to the release on PyPI
    ```
    https://{PKG}.readthedocs.io/en/{VERSION}/
    ```

/cc @jonparrott 

[1]: https://github.com/dhermes/bezier/blob/0.4.0/setup.py#L50-L58

**Comment by matham** [comment]
I'm not sure if you're aware, but you can do `python setup.py register` as many times as you like and it'll update the metadata.

**Comment by dhermes** [comment]
Ha DERP! I am now aware

**Comment by dhermes** [comment]
OK so I just tried that and also see a 410:

```
$ # I am in https://github.com/GoogleCloudPlatform/google-resumable-media-python
$ git log -1 --pretty=%H  # Where / when am I?
8625cf8f83d8d11caba328f55758f8b571ad1571
$ # Manually make some edits to README.rst
$ python setup.py register
running register
running egg_info
writing requirements to google_resumable_media.egg-info/requires.txt
writing google_resumable_media.egg-info/PKG-INFO
writing namespace_packages to google_resumable_media.egg-info/namespace_packages.txt
writing top-level names to google_resumable_media.egg-info/top_level.txt
writing dependency_links to google_resumable_media.egg-info/dependency_links.txt
reading manifest file 'google_resumable_media.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 2: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

warning: no previously-included files matching '__pycache__' found anywhere in distribution
writing manifest file 'google_resumable_media.egg-info/SOURCES.txt'
running check
Registering google-resumable-media to https://upload.pypi.org/legacy/
Server response (410): Project pre-registration is no longer required or supported, so continue directly to uploading files.
```

**Comment by matham** [comment]
Yeah, it confused me too, but it should still have updated the metadata.
Check the pypi page.

**Comment by dhermes** [comment]
I can confirm the [package metadata][1] **was not** updated (e.g. click the `LICENSE` link, it'll go to the `master` version, not the `0.2.0` version)

[1]: https://pypi.org/project/google-resumable-media/0.2.0/

**Comment by dhermes** [comment]
@matham It's also worth noting that the ["Migrating to PyPI.org" doc][1] says

> Explicit pre-registration of package names with the `setup.py register` command prior to the first upload is no longer required, and is not currently supported by the legacy upload API emulation on PyPI.org ... The solution is to skip the registration step, and proceed directly to uploading artifacts.

(I hadn't noticed this until just now)

[1]: https://packaging.python.org/guides/migrating-to-pypi-org/#registering-package-names-metadata

**Comment by matham** [comment]
Yeah, I saw that still it definitely worked for me a week ago. I did `python setup.py register` multiple times using my latest version of the project and it didn't show. But then I realized that I hadn't uploaded the wheels for that version so pypi wasn't showing that page so I uploaded the wheels with twine and then the updated metadata showed.

So I think the version has to match. But your master seems to have the same version as pypi so I'm not sure what is going on.

**Comment by dhermes** [comment]
But if I were to use `twine`, isn't that "bad form" to re-upload over existing wheel / sdist?

----

Maybe my workflow needs to change, but that's worth codifying somewhere. For example:

```
$ # Create branch JUST for the release
$ git checkout -b for-tag-x.y.z
$ # Modify setup.py and README.rst and anything else to be release specific
$ git add setup.py README.rst
$ git commit -m 'Making local modifications for x.y.z release.'
$ # Actually make the tag and do the release
$ git tag x.y.z
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

(I've recently seen Brett Cannon talk about always appending `dev` to the version while in `master`)

**Comment by matham** [comment]
I'm not sure I understand, why would there be an existing wheel/sdist? Do you mean the previous version?

My workflow is:

```
$ git checkout master
$ # edit version from x.y.z.dev0 to x.y.z in e.g. __init__.py
$ git add -p
$ git commit -m "Bump to x.y.z."
$ git tag -a vx.y.z -m "Tag x.y.z."
$ python setup.py sdist bdist_wheel
$ python setup.py register # if needed
$ twine upload dist/*
$ # edit version from x.y.z to x.y.z+1.dev0 in e.g. __init__.py
$ git commit -m "Bump to x.y.z+1.dev0."
$ git push origin master --tags
```

**Comment by dhermes** [comment]
> why would there be an existing wheel/sdist? Do you mean the previous version?

Yes, I was saying "if I were to use `twine`" to try to edit the metadata of an existing package (as you noted, when uploading with `twine`, the metadata gets set)

**Comment by matham** [comment]
I thought that when uploading with twine only the project version gets set based on the wheel name and not the rest of the metadata. I attributed the metadata update to the `register`, but I suppose it could be from twine (but I'm not sure how twine could change the metadata, it'd need to run setup.py, which I don't think it does). 

So I guess it's probably not twine that actually did the metadata update, it's just the twine wheel upload probably caused that version's metadata to display.

**Comment by brainwane** [comment]
I recognize that many package maintainers are used to being able to log in and update release descriptions via the web UI. Now, to update release metadata, you need to upload a new release; see [distutils-sig discussion](https://mail.python.org/pipermail/distutils-sig/2017-December/031826.html). This is a policy decision by the maintainers.

[Twine 1.10.0 is out](http://twine.readthedocs.io/) -- if you run into weird inconsistent metadata stuff when uploading with the new twine, please file an issue [at the twine repo](https://github.com/pypa/twine/issues).

Thanks.
