### ISSUE TITLE
Consider announce-only mailing list for packaging related issues

### ISSUE THREAD

**Issue by rsyring** [pypa/packaging-problems#98]
One of the difficulties of someone who packages Python software is the proliferation of outdated information and the sense of not knowing what is going on in the ecosystem.  More info here: https://github.com/pypa/packaging-problems/issues/21

I believe the current list are not ideal because they have too low signal-to-noise ratio for people who just want a "this is changing in Python package" emails:

* distutils-sig: way, way too much communication on very esoteric issues related to packaging.  I follow this to stay aware of what's going on, but there is so much noise.  I have to frequently ignore really, really long threads that I just don't care about.
* python announce: too much non-packing information that I just don't care about.  I don't want to sift through all those emails.

This would also be the place to send out deprecation notices.

This proposal was spurred by [this concern](https://gist.github.com/boppreh/ac7522b3a4ac46b4f6010eecddc57f21) and Donald's response:

> > I must have missed the deprecation period that preceded the complete removal of the old APIs. A friendly email would have been nice if you expect me to migrate to a new solution.
> 
> This is a hard balance to strike. When I have generated emails in the past I tend to get a slew of people berating me for sending them emails about things. Particularly for changes like this where there belief is that for most people, the impact should be minimal, if there is any at all. I do try to at least tweet and post to distutils-sig about possibly disruptive changes like this. For this specific change, that thread was at https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html.

**Comment by ncoghlan** [comment]
Also see: https://github.com/python/psf-infra-meta/issues/1

**Comment by ncoghlan** [comment]
pypi-announce@python.org exists now: https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/
