### ISSUE TITLE
Better error message: "only sdist, wheels, and eggs allowed since PEP 527"

### ISSUE THREAD

**Issue by rsyring** [pypa/packaging-problems#99]
[Original concern](https://gist.github.com/boppreh/ac7522b3a4ac46b4f6010eecddc57f21) and Donald's reply:

> > I try python setup.py bdist upload
> 
> As I mentioned above, we deprecated/removed everything but sdist, wheels, and eggs as per PEP 527. We could probably do better error messages here though.

I'm not sure what packaging tools would need to change (Twine, Setuptools, Warehouse) so I put the issue here.

**Comment by boppreh** [comment]
The error message appears to come from Warehouse, so I had an issue opened there a couple of days ago: https://github.com/pypa/warehouse/issues/2281

**Comment by brainwane** [comment]
Thanks, @rsyring and @boppreh! Issue fixed in pypa/warehouse#2387  so I'm going to go ahead and close the issue here.
